microsoft/vcpkg-tool

src/vcpkg/visualstudio.cpp

Previously, the v120 toolset was only detected by finding Visual Studio 2013 with `vswhere.exe`. Unfortunately, `vswhere.exe` is only available if Visual Studio 2017 (or higher) is installed. So, if you are using a configuration that has only ever had Visual Studio 2015 and Visual Studio 2013 installed, then the community triplet `x86-windows-v120` would fail with the error `Could not find Visual Studio instance with v120 toolset`. This can be easily [observed](https://ci.appveyor.com/project/Hoikas/appveyorvcpkg2013/builds/37646642) by attempting to use vcpkg on the "Visual Studio 2015" AppVeyor image. Now that bootstrapping no longer requires Visual Studio >= 2015 available, this also affects machines that only have Visual Studio 2013 installed... eg the "Visual Studio 2013" AppVeyor …

[visualstudio] Fix v120 toolset detection issue.

---

src/vcpkg/visualstudio.cpp

Previously, when users needed to bootstrap vcpkg with a copy of VS, this code was essentially never hit. Now that we are able to download a vcpkg binary, the user may only have non-Retail copies of MSVC or perhaps MinGW/Clang.

[vcpkg] Do not immediately fail at runtime if no Visual Studio has been found

---

.gitignore
src/vcpkg-test/binaryconfigparser.cpp
src/vcpkg/binarycaching.cpp

Adds a new binary cache provider (configured via `x-gcs`) to use
Google Cloud Storage as the backend. All uploads and downloads
are done via the `gsutil` tool.
I expect this PR to need a lot of additional work, mostly I am seeking
feedback.
There is plenty of room for optimization, this uploads and downloads
one object at a time, and does not take advantage of `gsutil` parallelization
either (aka the `-m` option).
Another future improvement would be to structure the cache to support
`gsutil rsync`.

[vcpkg] support Google Cloud Storage as binary cache

---

src/vcpkg/metrics.cpp

Prevent CURL hanging up without timeout when connection can't be established. Creating a deadlock on the filesystem when executed behind a proxy.
As requested by @JackBoosY, this is PR https://github.com/microsoft/vcpkg/pull/16499, retargeted to vcpkg-tool. Now with longer timeout.

Fix CURL filesystem deadlock with corporate proxy

---

src/vcpkg/base/system.process.cpp

vcpkg right now can't build CUDA ports with version 11.1 and 11.2, since the associated environment variables aren't being forwarded.

Add CUDA 11.1 and 11.2 to KEEP_ENV_VARS defaults

---

include/vcpkg/tools.h
src/vcpkg/tools.cpp

Part of the work for microsoft/vcpkg#16288

[tools] support gsutil

---

src/tls12-download.c
src/vcpkg/base/files.cpp
src/vcpkg/base/system.cpp
src/vcpkg/commands.add-version.cpp
src/vcpkg/commands.integrate.cpp
src/vcpkg/metrics.cpp

Otherwise, we hit issues like:
```
$ ./vcpkg x-add-version azure-kinect-sensor-sdk --overwrite-version
error removing file: /home/codespace/workspace/vcpkg/versions/a-/azure-kinect-sensor-sdk.json: No such file or directory
```
where afterwards the backup file exists and the original file has been removed. This is also just generally more "correct" and guards against process termination during the file write.

[x-add-versions] Perform atomic replacement of versioning files

---

src/vcpkg/cmakevars.cpp

this allows people to use, for example, IN_LIST

add cmake_minimum_required to vcpkg_tags

---

.gitignore
src/vcpkg/dependencies.cpp
src/vcpkg/install.cpp
src/vcpkg/portfileprovider.cpp
src/vcpkg/sourceparagraph.cpp

Adds telemetry for the following properties:
Name | Description
-- | --
`versioning-error-disabled` | User has declared  `builtin-baseline`, `version>=` or   `overrides` without enabling the versions feature flag
`versioning-error-no-baseline` | User has declared `version>=` or `overrides` but not a baseline
`versioning-error-baseline` | (**WIP**) User has declared an invalid baseline 
`versioning-error-version` | User has declared a constraint on a non-existing version
`manifest_version_constraint` | User has declared `version>=`

Add new telemetry points for versioning

---

CMakeLists.txt
azure-pipelines/pipelines.yml
azure-pipelines/signing.yml
cmake/utilities.cmake

Nobody needs to build it except us, so there's no need to.
Additionally, on mingw, tls12-download fails to build due,
so this also fixes our build on mingw.
Alternative fix to #31

don't build tls12-download unless it's needed

---

src/vcpkg/base/system.cpp
src/vcpkg/triplet.cpp

When running an x64 vcpkg binary on arm64, we should still have host processor be arm64
I'm not sure this is the way we should do this, but if we do decide to go this way this is how we should do it.
Fixes microsoft/vcpkg#16504

[osx] add support for rosetta

---

include/vcpkg/build.h
src/vcpkg/build.cpp
src/vcpkg/postbuildlint.cpp

Add vcpkg policy cmake helper port support

---

include/vcpkg/registries.h
src/vcpkg-test/registries.cpp
src/vcpkg/configuration.cpp
src/vcpkg/registries.cpp
src/vcpkg/vcpkgpaths.cpp

In the same vein as #21, this adds telemetry points for registries to see how people are using it :)

[registries] add metrics

---

src/vcpkg/paragraphs.cpp

This change resolves errors from RegistryEntry::get_path_to_version() when the default registry doesn't have a port for a name which is part of some extra registry but not listed in that registry's "packages" configuration field.
This is consistent with RegistrySet::registry_for_port() which only considers the the named packages from the extra registries.
Use case:
~~~
{
"default-registry": {
"kind": "filesystem",
"path": "/my/tiny/repository"
},
"registries": [
{
"kind": "git",
"repository": "https://github.com/microsoft/vcpkg",
"packages": [ "vcpkg-cmake", "vcpkg-cmake-config" ]
}
]
}
~~~

Use only named packages from extra registries

---

src/vcpkg/vcpkgpaths.cpp

Ensures that file endings are consistent between the ports and the versioned port under `versioning`.
Fixes https://github.com/microsoft/vcpkg/issues/16615#issuecomment-804928402 (verified locally). Before this fix, a patch with LF endings could end up with CRLF endings on Windows causing corrupt patch issues.

Disable git autocrlf when archiving tree

---

src/vcpkg/vcpkgpaths.cpp

`git fetch` normally refuses to deal with shallow repositories.
For vcpkg, this makes it impossible to use shallow clones of remote
registries such as `VCPKG_INSTALLATION_ROOT` on Azure Pipelines.
An extra parameter makes `git fetch` accept shallow repositories.

Allow shallow git registries

---

include/vcpkg-test/mockcmakevarprovider.h
include/vcpkg/cmakevars.h
include/vcpkg/commands.check-support.h
include/vcpkg/commands.setinstalled.h
include/vcpkg/dependencies.h
src/vcpkg-test/commands.cpp
src/vcpkg-test/plan.cpp
src/vcpkg-test/platform-expression.cpp
src/vcpkg-test/versionplan.cpp
src/vcpkg/build.cpp
src/vcpkg/cmakevars.cpp
src/vcpkg/commands.check-support.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.cpp
src/vcpkg/commands.setinstalled.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/install.cpp
src/vcpkg/platform-expression.cpp

`native` means "TARGET_TRIPLET == HOST_TRIPLET
the `x-check-support` command allows one to check if a port supports a platform.

[supports] Add `native` identifier expression and x-check-support command

---

include/vcpkg/binarycaching.private.h
src/vcpkg-test/binarycaching.cpp
src/vcpkg/binarycaching.cpp

This PR introduces an experimental workaround for the problem described in https://github.com/microsoft/vcpkg/issues/16579 by enabling a prefix to be added to all binary cached NuGet package ids. This enables multiple projects using the same NuGet feed to "see" a completely independent universe of cached packages and prevents all collisions.
To activate the workaround, simply set the environment variable `X_VCPKG_NUGET_ID_PREFIX` to a non-empty string. Package IDs will then be constructed as `<prefix>_<port>_<triplet>` instead of the default `<port>_<triplet>`.
@PazerOP I'd greatly appreciate it if you could try out this PR and confirm that it solves your issue. You will need to build the tool from source, which can be done by cloning this repo and using standard cmake.

[vcpkg] Introduce experimental workaround X_VCPKG_NUGET_ID_PREFIX

---

src/vcpkg/commands.add-version.cpp

Currently get_builtin_baseline is called for every port and 95% of the runtime
is spend inside of get_builtin_baseline when using --all
On my system now `./vcpkg x-add-version --all` runs 40 times faster, 300 ms instead of 12 seconds.

[vcpkg] x-add-version improve speed by calling get_builtin_baseline only once

---

azure-pipelines/end-to-end-tests-dir/versions.ps1
src/vcpkg/commands.add-version.cpp

[vcpkg] x-add-version now also checks if the manifest file is properly formatted

---

.gitignore

There are files create by the apple finder in every folder that you have opened with the finder

ignore .DS_store files

---

include/vcpkg/base/fwd/system.process.h
include/vcpkg/base/system.process.h
include/vcpkg/vcpkgpaths.h
src/vcpkg/commands.porthistory.cpp
src/vcpkg/commands.portsdiff.cpp
src/vcpkg/vcpkgpaths.cpp

This fixes some issues with patch files.

[git] always pass autocrlf=false

---

src/vcpkg/vcpkgcmdarguments.cpp

I don't know if my approach is the best one.  
Fixes:
:D

[vcpkg] allow --version to check the version

---

include/vcpkg/base/downloads.h
include/vcpkg/base/files.h
include/vcpkg/base/lockguarded.h
include/vcpkg/binarycaching.h
include/vcpkg/binarycaching.private.h
include/vcpkg/commands.xdownload.h
include/vcpkg/vcpkgcmdarguments.h
include/vcpkg/vcpkgpaths.h
src/vcpkg-test/commands.cpp
src/vcpkg-test/configparser.cpp
src/vcpkg/base/downloads.cpp
src/vcpkg/base/files.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/commands.cpp
src/vcpkg/commands.xdownload.cpp
src/vcpkg/install.cpp
src/vcpkg/tools.cpp
src/vcpkg/vcpkgcmdarguments.cpp
src/vcpkg/vcpkgpaths.cpp

Tool changes for https://github.com/microsoft/vcpkg/pull/13639.
See https://github.com/ras0219/vcpkg/blob/dev/roschuma/azblob-src/docs/users/config-environment.md#x_vcpkg_asset_sources for behavior docs.
The `X_VCPKG_ASSET_SOURCES` is designed to be similar to `X_VCPKG_BINARY_SOURCES` with the intent that they can share backends in the future.

[vcpkg] Add experimental $X_VCPKG_ASSET_SOURCES for source caching

---

src/vcpkg/base/system.process.cpp

When using `vcvarsall.bat` to obtain the Visual Studio environment variable fails, output the error message to notice user.
Fixes https://github.com/microsoft/vcpkg/issues/17319

Output error code when getting VS ENV failed

---

azure-pipelines/end-to-end-tests-dir/registries.ps1
include/vcpkg/registries.h
include/vcpkg/sourceparagraph.h
include/vcpkg/vcpkgcmdarguments.h
src/vcpkg-test/registries.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/install.cpp
src/vcpkg/registries.cpp
src/vcpkg/remove.cpp
src/vcpkg/sourceparagraph.cpp
src/vcpkg/update.cpp
src/vcpkg/vcpkgpaths.cpp

In addition, polish up several different areas:
- Fix problematic warnings about `"builtin-baseline"` when using `vcpkg-configuration.json`
- Block update & upgrade in manifest mode for future use
- Require baselines in builtin registry objects

Enable manifests, versions, and registries by default

---

azure-pipelines/end-to-end-tests-dir/binarycaching.ps1
azure-pipelines/end-to-end-tests-dir/clean-after-build.ps1
azure-pipelines/end-to-end-tests-prelude.ps1
include/vcpkg/base/util.h
include/vcpkg/build.h
include/vcpkg/dependencies.h
include/vcpkg/metrics.h
include/vcpkg/portfileprovider.h
include/vcpkg/vcpkgpaths.h
src/vcpkg-test/dependencies.cpp
src/vcpkg/base/files.cpp
src/vcpkg/cmakevars.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/install.cpp
src/vcpkg/portfileprovider.cpp

We're exceeding the 400GB temporary disk size in our CI right now and about half that is buildtrees we don't need:

Add --clean-non-downloads-after-build switch to be used by CI to reduce our disk consumption there.

---

src/vcpkg/build.cpp

- If HTTP(S)_PROXY already exist in environment variable, do not use IE Proxy auto detection. (https://github.com/microsoft/vcpkg-tool/pull/49)
- If the IE Proxy Setting is like: `http=127.0.0.1:8888;https=127.0.0.1:8888`, no longer add protocol prefix to each address.
Just for clearance, The current proxy behaviour will be (Windows Only):
- If HTTP(S)_PROXY presented in the environment variables, no longer enable #49.
- If no such variables, #49 detects Windows IE Proxy Settings and copies the proxy setting. When starting some build process, an env list will be built by vcpkg and passed to the child process. At that point, the copied proxy settings will be add to that env list by setting HTTP(S)_PROXY variables.

If HTTP(S)_PROXY already exist in environment variable, do not use IE Proxy (#49)

---

src/vcpkg/tools.cpp

Fixes https://github.com/microsoft/vcpkg/issues/17791
It may be a mistakes in previous code, the third part of version is getting from wrong element, that cause the inconsistency issue in tools required version with actual downloaded version.
Previously:
```
A suitable version of cmake was not found (required v3.20.0). Downloading portable cmake v3.20.0...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2-Linux-x86_64.tar.gz -> /home/kpa/Projekte/vcpkg/vcpkg/downloads/cmake-3.20.2-linux-x86_64.tar.gz
```
Currently:
```
A suitable version of cmake was not found (required v3.20.2). Downloading portable cmake v3.20.2...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2-Linux-x86_64.tar.gz -> …
```

[vcpkg] Fix the inconsistency issue in tools required version

---

src/vcpkg/commands.ci.cpp

#34 does not work correctly when host_triplet = target_triplet

---

.gitignore
CMakeLists.txt
cmake/utilities.cmake

This is a possible solution for improvement[ #17325 ](https://github.com/microsoft/vcpkg/issues/17325)
Note that this is a build option. Although it "looks" enabled by default, the full condition is in fact combined with `VCPKG_EMBED_GIT_SHA`, which is OFF by default.
Therefore on official builds it would be ON.

Add SourceLink

---

include/vcpkg/commands.init-registry.h
src/vcpkg-test/commands.cpp
src/vcpkg/commands.cpp
src/vcpkg/commands.init-registry.cpp
src/vcpkg/vcpkgcmdarguments.cpp

The next step is to support `x-add-version` in registries.

[vcpkg] add command init-registry

---

src/vcpkg/commands.integrate.cpp

On mac the `.bash_profile` file is used instead of the `.bashrc` file by the Terminal

vcpkg integrate bash: use ~/.bash_profile on macOS

---

src/vcpkg/postbuildlint.cpp

The current message is a bit repetitive.

Simplify the "invalid crt linkage" warning message

---

include/vcpkg-test/util.h
include/vcpkg/base/downloads.h
src/vcpkg-test/configparser.cpp
src/vcpkg/base/checks.cpp
src/vcpkg/base/downloads.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/commands.xdownload.cpp

- If any headers are specified, we use `curl.exe` on Windows. If we need this feature to support earlier than win10 without requiring the user to provide curl, we can look at finding a copy of curl to download on demand or to look at adding header support to the WinHTTP download.
- Future PRs will expose options for binarycaching and assetcaching to provide headers for use when connecting to the mirror (e.g. `Authorization: bearer <token>`).
Without debug output:
```
$ export X_VCPKG_ASSET_SOURCES=x-azurl,https://127.0.0.1,,readwrite
$ vcpkg x-download \
"--header=Authorization: bearer ABC123" \
--url=https://github.com/microsoft/vcpkg-tool/releases/download/2021-05-05- 
9f849c4c43e50d1b16186ae76681c27b0c1be9d9/tls12-download.exe \
tls12-download.exe \ …
```

[x-download] Implement `--header` argument

---

include/vcpkg/base/files.h
include/vcpkg/registries.h
include/vcpkg/vcpkgcmdarguments.h
include/vcpkg/vcpkgpaths.h
src/vcpkg/base/files.cpp
src/vcpkg/commands.add-version.cpp
src/vcpkg/commands.format-manifest.cpp
src/vcpkg/registries.cpp
src/vcpkg/vcpkgcmdarguments.cpp
src/vcpkg/vcpkgpaths.cpp

I have started with `format-manifest` and `x-add-version`. I would add support for more commands, but before that it would be cool if you can say if the current design is okay or if I should change it.

Support custom registries in commands

---

include/vcpkg/commands.xdownload.h
src/vcpkg-test/commands.cpp
src/vcpkg/commands.cpp
src/vcpkg/commands.xdownload.cpp
src/vcpkg/vcpkgcmdarguments.cpp

* Pass --vcpkg-root through recursive bits
* Change x-download into a basic command, meaning we don't need to make a vcpkgpaths for it (and its associated need of vcpkg roots etc.)
I'm pretty sure we should make `fetch` into a basic command too but that's more surgery

Fix x-download when downloads isn't in a vcpkg root

---

include/vcpkg/base/chrono.h
include/vcpkg/base/expected.h
include/vcpkg/base/lazy.h
include/vcpkg/base/sortedvector.h
include/vcpkg/base/system.print.h
include/vcpkg/commands.h
src/vcpkg/commands.ci.cpp
src/vcpkg/platform-expression.cpp

* use `struct` for declaring class types
* use `class` for declaring template parameters
* use `typename` for disambiguating in templates

switch to Casey convention for declarations

---

include/vcpkg/base/downloads.h
include/vcpkg/binarycaching.h
include/vcpkg/vcpkgpaths.h
src/vcpkg-test/configparser.cpp
src/vcpkg/base/downloads.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/commands.xdownload.cpp
src/vcpkg/vcpkgpaths.cpp

We leaked a SAS token, now expired, in CI, because we run downloads with debug turned on, and that printed the token. We shouldn't print the token even during debug, because that would let anyone who controls our command line, which is anyone, to print the token easily.

Respect secrets in debug output for downloads.

---

src/vcpkg/commands.search.cpp

See:
- microsoft/vcpkg#18648
- microsoft/vcpkg#18576 
- microsoft/vcpkg#18280
- microsoft/vcpkg#18165
- ...
The users don't know that the list is probably outdated and must be updated with `git pull`. So explain that.

vcpkg search: Users should use git pull to get the latest results

---

src/vcpkg-test/configparser.cpp
src/vcpkg/binarycaching.cpp

Related to this issue https://github.com/microsoft/vcpkg/issues/18483
As mentioned in the issue, ideally this timeout value could be configurable, but I'm not sure the best way to approach that in this code base. Help would be greatly appreciated!
Needs the extra second due to some potential issue with how NuGet calculates the timeout:
https://jfrog.com/knowledge-base/how-to-resolve-nuget-push-failures-after-5-minutes-even-though-timeout-value-is-set-as-greater-than-5-minutes-300-seconds/

binarycaching: Add NuGet timeout configuration entry

---

src/vcpkg/commands.init-registry.cpp

As a response to [this](https://github.com/microsoft/vcpkg-tool/pull/93#discussion_r658918215)

init-registry: registries can only be created at the root of a git repository

---

cmake/utilities.cmake
include/pch.h
include/vcpkg/base/cofffilereader.h
include/vcpkg/base/files.h
include/vcpkg/base/strings.h
src/vcpkg-test/files.cpp
src/vcpkg.cpp
src/vcpkg/base/cofffilereader.cpp
src/vcpkg/base/files.cpp
src/vcpkg/base/hash.cpp
src/vcpkg/base/strings.cpp
src/vcpkg/base/system.process.cpp
src/vcpkg/build.cpp
src/vcpkg/commands.format-manifest.cpp
src/vcpkg/metrics.cpp
src/vcpkg/postbuildlint.cpp

I did this work as a prerequiste of z-applocal in attempt to reduce code size; on Windows anyway it doesn't help much because we still depend on std::regex which drags in all of the locale support stuff. I still think it's a good change though.

Eliminate iostreams

---

src/vcpkg/cmakevars.cpp

When calling CMake to obtain triplet information a regression change from CMake 3.20.5 to 3.21.0-rc1
causes the tool to exit due to an exception.
This is due to the response containing a mixture of '\n' and  '\r\n' line endings.
After splitting the output on line feeds ('\n') each line is then trimmed of whitespace to remove
any carriage returns ('\r') or trailing whitespace. This could be fixed in CMake but this
change makes it robust.
This commit in CMake caused the fault: https://github.com/Kitware/CMake/commit/0a0a0f8a744e2bfa35cdbc90db6e4e23adadd59b
It is unlikely to change as they have added a new helper file for writing the terminal output.

Fixed issue with output from CMake 3.21.0

---

azure-pipelines/end-to-end-tests-dir/cli.ps1
azure-pipelines/end-to-end-tests-dir/fetch.ps1
src/vcpkg/archives.cpp

This PR adds `.msi` support to `vcpkg fetch` in order to enable upgrading 7zip to a more recent version (19.00). We must use the MSI package because it is one of the few formats that can be supported on a completely stock Windows machine.
Once this change is applied, we'll replace the 7zip entry in `vcpkgTools.xml` with:
```xml
<tool name="7zip" os="windows">
<version>19.00</version>
<exeRelativePath>Files\7-Zip\7z.exe</exeRelativePath>
<url>https://www.7-zip.org/a/7z1900-x64.msi</url>
<sha512>7837a8677a01eed9c3309923f7084bc864063ba214ee169882c5b04a7a8b198ed052c15e981860d9d7952c98f459a4fab87a72fd78e7d0303004dcb86f4324c8</sha512>
<archiveName>7z1900-x64.msi</archiveName>
</tool>
```
As a side benefit, this allows us to use 7zip to unpack `.nupkg` files in the future, since we will no …

Teach vcpkg fetch to handle msi files

---

src/vcpkg/build.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.integrate.cpp
src/vcpkg/export.cpp
src/vcpkg/export.ifw.cpp
src/vcpkg/export.prefab.cpp
src/vcpkg/install.cpp
src/vcpkg/metrics.cpp

In keeping with our desire to not say stdfs outside of files.h machinery, this PR removes unnecessary stdfs:: qualifications from copy_options.

stdfs::copy_options -> copy_options

---

cmake/utilities.cmake
include/vcpkg-test/util.h
include/vcpkg/base/files.h
include/vcpkg/base/hash.h
src/vcpkg-test/files.cpp
src/vcpkg-test/hash.cpp
src/vcpkg-test/util.cpp
src/vcpkg/base/files.cpp
src/vcpkg/base/hash.cpp
src/vcpkg/base/strings.cpp

test/files.cpp
Rather than try to read windows client specific registry keys as a means of predicting whether symlinks work, now that we distribute vcpkg in binary forms on Windows, we can assume it is built with a modern compiler, and thus with std::filesystem. This means we can detect the problematic condition by just attempting to create the symlink, and testing if we get ERROR_PRIVILEGE_NOT_HELD back.
utilities.cmake:
Delete handling for old compilers on Windows.
files.h and base/files.cpp:
Add create_directory_symlink called by tests, and the missing overloads of create_symlink.
Delete code blocks looking for defined(_WIN32) && !VCPKG_USE_STD_FILESYSTEM.
Fix bad format string in create_directory error message without enough %s.
Remove unnecessary regex_search for invalid chars. …

Make symlink tests work on all Windows versions

---

src/vcpkg/visualstudio.cpp

The v143 build tools [recently released](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-preview-2-is-out/) alongside VS 2022 preview 2, and vcpkg fails when explicitly passing the toolset to cmake via `-T v143`. Also fixes [vcpkg/#18987](https://github.com/microsoft/vcpkg/issues/18987).

Add support for MSVC v143 toolset

---

include/vcpkg/install.h
src/vcpkg-test/dependencies.cpp
src/vcpkg/commands.setinstalled.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/install.cpp

This PR adds tracking of top-level dependencies versus transitive dependencies through the versioned install planner. Then, after completing the "set-installed" algorithm, we print usage information for all top-level package specs.
Before:
```
PS C:\src\vcpkg\mtest> vcpkg install
Detecting compiler hash for triplet x86-windows...
All requested packages are currently installed.
Total elapsed time: 3.2 us
```
After:
```
PS C:\src\vcpkg\mtest> vcpkg install
Detecting compiler hash for triplet x86-windows...
All requested packages are currently installed.
Total elapsed time: 3.2 us
The package cpprestsdk:x86-windows provides CMake targets:
find_package(cpprestsdk CONFIG REQUIRED)
target_link_libraries(main PRIVATE cpprestsdk::cpprest cpprestsdk::cpprestsdk_zlib_internal …
```

Display usage information after installing in manifest mode

---

include/vcpkg/base/strings.h
src/vcpkg-test/dependencies.cpp
src/vcpkg/dependencies.cpp

Currently I can create the following vcpkg.json file and vcpkg runs without any errors or warnings:
```
{
...
"dependencies": [
{
"name": "qtbase",
"features": ["libdouble-conversion"]
},
]
}
```

vcpkg install: requesting non existing features should be an error

---

src/vcpkg/base/json.cpp

See title.
Before:
```
Failed to parse manifest at C:\src\vcpkg\mtest\vcpkg.json:
C:\src\vcpkg\mtest\vcpkg.json:10:30: error: Unexpected character; expected comma or close brace.
on expression:             "version": "1.0" // hello!
^
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```
After:
```
Failed to parse manifest at C:\src\vcpkg\mtest\vcpkg.json:
C:\src\vcpkg\mtest\vcpkg.json:10:30: error: Unexpected character; expected comma or close brace
vcpkg does not support c-style comments, however most objects allow $-prefixed fields to be used as comments.
on expression:             "version": "1.0" // hello!
^
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

Add more specific error message if user attempts to use comments in json

---

include/vcpkg/versiondeserializers.h
src/vcpkg-test/manifests.cpp
src/vcpkg/help.cpp
src/vcpkg/sourceparagraph.cpp
src/vcpkg/versiondeserializers.cpp

See title -- this was found as a stumbling point for new users to versioning. They wanted to just type what they saw in the version list (e.g. "1.2.0#1") but were slightly frustrated that it doesn't work.
This PR specifically allows users to use the `#N` syntax in all version fields for `"overrides": ` objects.
As a drive by, this PR removes the experimental notice for versioning.

Teach overrides to understand embedded port versions

---

include/vcpkg/vcpkgpaths.h
src/vcpkg/help.cpp
src/vcpkg/install.cpp
src/vcpkg/registries.cpp
src/vcpkg/sourceparagraph.cpp
src/vcpkg/vcpkgpaths.cpp

See title. Many of the error messages presented when working with baselines are confusing to first time users.
As a drive by, this also rewords `vcpkg help versioning` for more clarity (see code for exact changes).
I've also removed dead code left around by the pre-GA baseline specification of multiple baseline objects within the builtin baseline file. Today, `"builtin-baseline"` is required to be a git SHA and should never activate that code path.
_Before_
```
PS C:\src\vcpkg\mtest> vcpkg.old install
Error: Couldn't find explicitly specified baseline `"56bb45d27d8d5ddf8b66daa2a14d6293223f1cf5"` in the baseline file, and there was no baseline at that commit or the commit didn't exist. …
```

Improve error messages around versioning baselines

---

CMakeLists.txt

this is in line with that vcpkglib is _not_ a thing we want to ship
See the comments on PR #132

change the vcpkglib library to an object library

---

include/vcpkg/base/jsonreader.h
include/vcpkg/base/optional.h
include/vcpkg/base/strings.h
include/vcpkg/registries.h
src/vcpkg-test/registries.cpp
src/vcpkg/base/strings.cpp
src/vcpkg/registries.cpp

This also drops the dependency on path::iterator which means Bill doesn't have to implement it in project depath

Enforce cross platform paths in registries.

---

src/vcpkg/commands.integrate.cpp

vcpkg integrate: Add support for zsh

---

src/vcpkg/base/downloads.cpp

it might ease with errors like https://github.com/microsoft/vcpkg/issues/7207, https://github.com/microsoft/vcpkg/issues/18734
see also https://github.com/microsoft/vcpkg/pull/18171 for related issues with using vcpkg as a download tool

increase timeouts for downloads

---

src/vcpkg/base/downloads.cpp
src/vcpkg/base/files.cpp
src/vcpkg/base/system.process.cpp
src/vcpkg/registries.cpp
src/vcpkg/sourceparagraph.cpp
src/vcpkg/vcpkgpaths.cpp
src/vcpkg/versiondeserializers.cpp

These std::moves either had no effect or inhibited elision. See http://eel.is/c++draft/class.init#class.copy.elision-3

Remove "return std::move(local);"s.

---

CMakeLists.txt

Now this project can be easily installed with CMake:
```
cmake --install build --prefix install
```
Closes https://github.com/microsoft/vcpkg/issues/19114.

Implemented base CMake installation support

---

azure-pipelines/e2e_ports/version-files/transitive-constraints/ports/overlay-zlib/vcpkg.json
azure-pipelines/e2e_ports/version-files/transitive-constraints/ports/overlay/vcpkg.json
azure-pipelines/e2e_ports/version-files/transitive-constraints/vcpkg.json
azure-pipelines/end-to-end-tests-dir/versions.ps1
src/vcpkg/install.cpp
src/vcpkg/registries.cpp

This PR fixes two outstanding bugs with using versioning features in transitive manifests:
1. We previously required a `builtin-baseline` as part of transitive manifests if they provide `version>=`. This was a bug; we only need `builtin-baseline` for the top-level manifest because it is a non-transitive property.
2. Manifest mode users that aren't using versioning or registries encountered errors when trying to use transitive dependencies from the built-in registry that have version constraints. This was not desired, because manifest mode without versioning should act the same as classic mode. In this PR, I've implemented that behavior by appending the builtin ports directory as an overlay. This is likely incorrect with respect to classic mode registry configuration (adding a …

Fix versioning features of transitive manifests

---

include/vcpkg/base/files.h
src/vcpkg/base/files.cpp
src/vcpkg/vcpkgpaths.cpp

This change was extracted from adding the POSIX backend for filesystem to be easier to review. It moves everything related to file locking into files.cpp, and eliminates ifdefs in files.h for platform selection. It uses std::function to unlock the lock instead. Notably, this is the same number of virtual dispatches as before, and eliminates a theoretical lifetime problem where the Filesystem* did not outlive the ExclusiveFileLock type.

Preserve RAII for file locking through virtual dispatch.

---

include/vcpkg/base/files.h
src/vcpkg/base/files.cpp
src/vcpkg/base/hash.cpp

This is a follow-up to #141 which fixes a build break for conda-forge.
@wolfv can you try this PR out and confirm it fixes the conda-forge build?
See also https://github.com/microsoft/vcpkg-tool/pull/141#issuecomment-898264018.

Remove all uses of std::io_errc

---

include/vcpkg/build.h
src/vcpkg/build.cpp
src/vcpkg/commands.env.cpp

See title -- we previously would still enumerate the VS toolsets even if the triplet does not require one.

Do not consult vswhere.exe unless the triplet requests Visual Studio support

---

CMakeLists.txt
cmake/utilities.cmake

CMakeLists.txt:
1 Bump to 3.15
4 Turn on policy CMP0092 to disable default cmake warnings.
30 Remove previous now-redundant use of MSVC_RUNTIME_LIBRARY
99 Remove regex obsoleted by CMP0092
utilities.cmake
194 Remove clang 9.x development warnings workaround.
203 Remove /W3 when development warnings are off.

Use /MT and CMake 3.15.

---

include/vcpkg/install.h
src/vcpkg/commands.setinstalled.cpp
src/vcpkg/install.cpp

```
C:\Dev\vcpkg>.\vcpkg.exe x-set-installed zlib:x86-windows zlib:x64-windows
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
The following packages will be built and installed:
zlib[core]:x64-windows -> 1.2.11#11
zlib[core]:x86-windows -> 1.2.11#11
Using cached binary package: C:\Users\bion\AppData\Local\vcpkg\archives\ab\ab679b37f1c29aae19233bf1444eed9a72fe2e7e6e4b9f303b98b3ca7400129a.zip
Using cached binary package: C:\Users\bion\AppData\Local\vcpkg\archives\f9\f93940bf2cd0ef0a76754ef745b2139740e0a022fd1d67a6f05fe2d00e7a288c.zip
Starting package 1/2: zlib:x64-windows
Building package zlib[core]:x64-windows...
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package …
```

Don't print duplicate usage messages.

---

include/vcpkg/sourceparagraph.h
src/vcpkg/commands.ci.cpp
src/vcpkg/sourceparagraph.cpp

In order to build additional tooling on top of the vcpkg CI, we need to know the package hashes of what is being built. This PR introduces the ability for the CI to output the full set of computed hashes for the run, with a schema like:
```json
[
{
"name": "boost-vcpkg-helpers",
"triplet": "x64-linux",
"state": "pass",
"abi": "f9931d4a68e4136736dba6de934e450cb427df181c560f855510a3588f9b1fb0"
},
{
"name": "boost-config",
"triplet": "x64-linux",
"state": "pass",
"abi": "96b7c320891a2fb2d0abced0308c433d6ee6aab85404145f84c505fcd2fcedaa"
},
{
"name": "boost-preprocessor",
"triplet": "x64-linux",
"state": "pass",
"abi": "e236064d5bd096a970d4a01097e6e491d3aa099b8f2afa048150656a42a5559c"
}
]
```
For quick-and-dirty manipulation, this can be munged through `jq`, such as `jq '[.[].abi]' …

Introduce 'ci --output-hashes='

---

src/vcpkg-test/platform-expression.cpp
src/vcpkg/platform-expression.cpp

I've noticed people writing `arm & !arm64`, which just seems really unfortunate. Add an `arm32` platform identifier to mean exactly this.

[platform-expression] add arm32 platform identifier

---

src/vcpkg-test/manifests.cpp
src/vcpkg/sourceparagraph.cpp

It is not used and not described in the docs. I used `vcpkg format-manifest --all` with the new version and it doesn't reported a wrong file.

Manifests: Remove support for declaring features as lists

---

include/vcpkg/cmakevars.h
include/vcpkg/dependencies.h
include/vcpkg/sourceparagraph.h
src/vcpkg-test/dependencies.cpp
src/vcpkg-test/manifests.cpp
src/vcpkg/cmakevars.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/install.cpp
src/vcpkg/sourceparagraph.cpp

Fixes https://github.com/microsoft/vcpkg/issues/17651

 support-expressions: Add support expressions to features. Error when supports expression evaluates to false in classic and manifest mode.

---

include/vcpkg/build.h
src/vcpkg/build.cpp
src/vcpkg/install.cpp

When users report port build/install issues, it is often not obvious which features and package version they tried to install, even when they add command line output: versions and features are printed only early, for the "installation plan". This PR adds version and features to the *final output* statement, i.e. the instructions which information to include into an GH issue.
Tested with `install` and `build` command.
Example before this change:
~~~
$ ./vcpkg install qt5-base:x64-mingw-dynamic
Computing installation plan...
The following packages will be built and installed:
* openssl[core]:x64-mingw-dynamic -> 1.1.1l#1
* pcre2[core]:x64-mingw-dynamic -> 10.37
qt5-base[core]:x64-mingw-dynamic -> 5.15.2#11
* sqlite3[core]:x64-mingw-dynamic -> 3.36.0#1
* zstd[core]:x64-mingw-dynamic -> 1.5.0 …

Report features and version on build error

---

include/vcpkg/base/files.h
src/vcpkg-test/files.cpp
src/vcpkg-test/registries.cpp
src/vcpkg/base/files.cpp

This PR is part of the std::filesystem removal-on-POSIX project.
files.hpp:
* Delete update_existing because we do not use it.
* Deduplicate definition of preferred_separator.
files.cpp:
* Add PosixFd RAII type for file descriptors.
* Add ReadDirOp type for directory enumeration operations.
* Use PosixFd for existing file descriptor operations.
* Actually implement the enumeration operations.

Add posix-native get_Xxx_non?_recursive.

---

src/vcpkg/build.cpp
src/vcpkg/commands.ci.cpp

Before:
```
➜  vcpkg git:(update-proj4) ✗ vcpkg ci x64-osx
'vcpkg ci' is an internal command which will change incompatibly or be removed at any time.
Loading dependency information for 150 packages...
Error: v8[core] is only supported on '!(arm | arm64 | uwp | osx)'
```
After:
```
➜  vcpkg git:(update-proj4) ✗ vcpkg ci x64-osx
'vcpkg ci' is an internal command which will change incompatibly or be removed at any time.
Loading dependency information for 150 packages...
Loading dependency information for 408 packages...
Error: Unreachable code was reached
/Users/leanderSchulten/git_projekte/vcpkg-tool/src/vcpkg/platform-expression.cpp(415)
[1]    53038 abort      vcpkg ci x64-osx
```
The last error gets fixed in #147

[ci command] Dont exit when a port is not supported for given triplet

---

src/vcpkg/postbuildlint.cpp

As requested by https://github.com/microsoft/vcpkg/pull/20217#issuecomment-922664454

Suggest vcpkg_cmake_config_fixup rather than vcpkg_fixup_cmake_targets.

---

include/vcpkg/install.h
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.setinstalled.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/install.cpp

Fixes https://github.com/microsoft/vcpkg/issues/16850
Maybe somewhere internally a function need the current printed time, but as an end user I am only interested in the real "total elapsed time" and not how long some internally sub function needs.

Fix wrong "Total elapsed time" messages

---

src/vcpkg/binarycaching.cpp

After #40 we can set different prefixes for caching packages in nuget. It's working fine for push to cache. But restore from cache don`t working:
1. nuget download package with prefix from cache
2. but vcpkg don't see him - `Restored 0 packages from NuGet. Use --debug for more information.`
fix https://github.com/microsoft/vcpkg/issues/19095 and https://github.com/microsoft/vcpkg/discussions/19103

restore packages from nuget if X_VCPKG_NUGET_ID_PREFIX set

---

src/vcpkg-test/files.cpp
src/vcpkg/base/files.cpp

Resolves https://github.com/microsoft/vcpkg/issues/20546

In filesystem::remove, handle readonly bits correctly on Windows.

---

azure-pipelines/end-to-end-tests-dir/tool-ports.ps1
src/vcpkg.cpp

Fixes vpckg cmake output parsing breaking when cmake colorizes the output due to environment variable `CLICOLOR_FORCE`. 
Issue: https://github.com/microsoft/vcpkg/issues/20430

Always unset CLICOLOR_FORCE

---

src/vcpkg/commands.integrate.cpp

Without this, the integrate command fails if the user did not
already create the directory

Create the completions directory for fish before copying files

---

azure-pipelines/end-to-end-tests-dir/backcompat-helpers.ps1
azure-pipelines/pipelines.yml
azure-pipelines/signing.yml
src/vcpkg/build.cpp
src/vcpkg/install.cpp
src/vcpkg/postbuildlint.cpp
src/vcpkg/vcpkgcmdarguments.cpp

Note that they are still treated as errors for purposes of including a port in our curated catalog.
Improve the diagnostics for the pkgconfig check. Example:
```
billyoneal@Billys-MacBook-Pro vcpkg % ../vcpkg-tool/build/vcpkg install gtest --no-binarycaching
Computing installation plan...
The following packages will be built and installed:
gtest[core]:arm64-osx -> 1.11.0
Detecting compiler hash for triplet arm64-osx...
Starting package 1/1: gtest:arm64-osx
Building package gtest[core]:arm64-osx...
-- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/billyoneal/vcpkg/triplets/community/arm64-osx.cmake
-- Downloading https://github.com/google/googletest/archive/release-1.11.0.tar.gz -> …
```

Change post-build checks to be warnings rather than errors. 

---

src/vcpkg-test/util.cpp
src/vcpkg/postbuildlint.cpp

To fix ugly mixed separator output in error messages on windows, e.g.
~~~
-- Performing post-build validation
Import libs were not present in F:\vcpkg\packages\lapack-reference_x64-windows\debug/lib
~~~
(from https://github.com/microsoft/vcpkg/issues/21060)

Consistently construct paths using host's separator

---

src/vcpkg/postbuildlint.cpp

For example is now prints:
```
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/share/pkgconfig")
```
instead of 
```
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")
```

Empty dirs postbuild check: Improve suggestion

---

src/vcpkg/commands.add-version.cpp

This was the behavior before #126 got merged. This also solves https://github.com/microsoft/vcpkg/issues/16520#issuecomment-963141566

[x-add-version] ignore files in ports dir

---

src/vcpkg-test/json.cpp
src/vcpkg/base/json.cpp

Fixes https://github.com/microsoft/vcpkg/issues/20837.
It looks that parsing vcpkg.json may require more error handling.

return verbose error when json contains object with duplicated keys

---

include/vcpkg/sourceparagraph.h
src/vcpkg-test/configmetadata.cpp
src/vcpkg-test/manifests.cpp
src/vcpkg.cpp
src/vcpkg/configuration.cpp
src/vcpkg/registries.cpp
src/vcpkg/sourceparagraph.cpp

This PR makes the following changes:
* Adds "summary" as a text field.
* Adds "contacts" as a generic object field. In the future we will merge this with the "maintainers" field and have a proposed schema for it.
* Adds initial support for artifact registries.

Add new fields to vcpkg.json

---

include/vcpkg/tools.h
include/vcpkg/vcpkgcmdarguments.h
src/vcpkg/tools.cpp
src/vcpkg/vcpkgcmdarguments.cpp
src/vcpkg/vcpkgpaths.cpp

If a developer in a team has a different version of a abi relevant tool, the developer has
to rebuild every package because the developer only gets cache misses in the binary cache.
Add an option to force vcpkg to use the same version of a abi relevant tool so that you don't
get binary cache misses because of different abi relevant tools.

[tool cache] Add option to require exact versions for abi relevant tools

---

azure-pipelines/end-to-end-tests-dir/bundles.ps1
azure-pipelines/end-to-end-tests-dir/registries.ps1
azure-pipelines/end-to-end-tests-prelude.ps1
azure-pipelines/end-to-end-tests.ps1
include/vcpkg/vcpkgpaths.h
src/vcpkg/install.cpp
src/vcpkg/registries.cpp
src/vcpkg/vcpkgpaths.cpp

This bundle setting replaces the `BuiltinRegistry` with a `GitRegistry` pointed at `github.com/Microsoft/vcpkg`, enabling functional tool distribution without requiring the entire port history.
Some additional implementation notes:
- I enabled e2e tests outside the registries.ps1 suite to use the user cache -- these e2e tests are not testing the registries code, they are testing other behaviors and shouldn't need to constantly purge and re-download git repos.
- Management of `"builtin-baseline"` has been moved into `load_configuration()`, since it's morally the same as `"vcpkg-configuration"`
- This mode _requires_ a configured baseline even for commands like "search". Future work should address this.

Implement bundle.usegitregistry (continuation of read-only vcpkg)

---

src/vcpkg-test/platform-expression.cpp
src/vcpkg/platform-expression.cpp

This change implements support in platform expressions for binary logical operators (and, or) as defined by [Media Queries](https://www.w3.org/TR/css3-mediaqueries/#syntax).
We are extending current platform expressions as follows:
* for logical-and, 'and' is a synonym for '&'
* for logical-or, ',' is accepted, but has lower precedence than logical-and
* currently using both '&' and '|' in the same expression is disallowed unless parens are used to identify evaluation precedence; that constraint is preserved, but '&', 'and', and ',' can be freely mixed in a platform expression without the need for parens
The existing platform expression parser:
* does a left-to-right linear scan of the expression string
* assumes that logical operators are individual chars ('!', '&', '|')
* …

Support media queries binary logical operator syntax in platform expressions

---

include/vcpkg/base/chrono.h
include/vcpkg/base/files.h
include/vcpkg/base/json.h
include/vcpkg/base/jsonreader.h
include/vcpkg/base/system.process.h
include/vcpkg/base/unicode.h
include/vcpkg/globalstate.h
include/vcpkg/paragraphs.h
include/vcpkg/registries.h
include/vcpkg/vcpkgpaths.h
src/vcpkg.cpp
src/vcpkg/base/files.cpp
src/vcpkg/base/json.cpp
src/vcpkg/base/system.process.cpp
src/vcpkg/base/unicode.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.setinstalled.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/configuration.cpp
src/vcpkg/globalstate.cpp
src/vcpkg/install.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/portfileprovider.cpp
src/vcpkg/registries.cpp
src/vcpkg/vcpkgpaths.cpp

Results: `vcpkg search zlib` is 30x faster in my Linux docker container. The biggest sources of improvement were:
1. Eliminate uses of `std::regex`
2. Avoid loading and parsing the manifests multiple times
3. Optimize low level utf8 reader
I've also left in basic performance counters to enable future performance tracking and improvement.
Before perf work:
```
$ time vcpkg search zlib --debug
...
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 89751 us
[DEBUG] Time in JSON reader: 743202 us
[DEBUG] Time in filesystem: 12453 us
[DEBUG] Time in loading ports: 862885 us
[DEBUG] Exiting after 876.1 ms (876052 us)
real    0m0.878s
user    0m0.848s
sys     0m0.030s
```
After perf work:
```
$ time vcpkg search zlib --debug
...
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in …
```

Performance work on `vcpkg search` (30x improvement)

---

include/pch.h
include/vcpkg/base/expected.h
include/vcpkg/base/files.h
include/vcpkg/base/format.h
include/vcpkg/base/fwd/format.h
include/vcpkg/base/fwd/messages.h
include/vcpkg/base/messages.h
include/vcpkg/base/pragmas.h
include/vcpkg/base/stringliteral.h
include/vcpkg/base/strings.h
include/vcpkg/base/stringview.h
include/vcpkg/base/system.debug.h
include/vcpkg/base/system.print.h
include/vcpkg/base/zstringview.h
include/vcpkg/build.h
include/vcpkg/sourceparagraph.h
include/vcpkg/triplet.h
include/vcpkg/vcpkgpaths.h
include/vcpkg/visualstudio.h
src/vcpkg.cpp
src/vcpkg/base/messages.cpp
src/vcpkg/base/system.print.cpp
src/vcpkg/build.cpp
src/vcpkg/commands.env.cpp
src/vcpkg/install.cpp
src/vcpkg/registries.cpp
src/vcpkg/vcpkgpaths.cpp
src/vcpkg/visualstudio.cpp

This PR localizes information displayed about the Visual Studio instances on the machine and provides more context about why vcpkg was unable to locate an instance that matches the user's request.
As drive by's, this PR also:
1. Moves `StringView` to be more fundamental than `format`
2. Makes `Triplet` fmt-serializable by introducing a SFINAE specialization for string-like types. This specialization avoids needing the full boilerplate of defining an entire separate specialization for types that can be trivially converted to `StringView`s.

Provide better debug information about Visual Studio instances

---

include/vcpkg/vcpkgpaths.h
src/vcpkg/build.cpp
src/vcpkg/registries.cpp
src/vcpkg/vcpkgpaths.cpp

The primary change in this PR is very small: Add `$bundle.embeddedsha` to enable read-only vcpkg to provide useful error messages around baselines.
While investigating the general problem, I discovered several other functions that were generally 'unsafe' (they depend upon `root / ".git"`), but in the single context they're used are safe. I therefore refactored things to move those functions closer to their contexts and out of the public `VcpkgPaths::` interface.

Add 'embeddedsha' to record tested baseline for bundle

---

azure-pipelines/end-to-end-tests-dir/registries.ps1
src/vcpkg/registries.cpp

`m_files_impl` of the `BuiltinGitRegistry` was never initialized to a `BuiltinFilesRegistry` which results in a crash for several operations (such as search) if in a manifest directory with a builtin-baseline.

Fix crash in `vcpkg search` with `builtin-baseline`

---

azure-pipelines/signing.yml

Until you switch over to using a submodule, use clone/checkout to get the CE source code so that the set-version script in the build works correctly.

Clone, not fetch the ce repo when building

---

src/vcpkg/base/system.print.cpp

In a previous PR I changed `print2(Color)` to go through `msg::`, however I didn't change `print(...)` to also use the new printing mechanism. This resulted in strangely interleaved output on Windows since `msg::` doesn't go through the CRT.

Fix interleaving issue between `print2(...)` and `print2(Color,...)`

---

azure-pipelines/end-to-end-tests-dir/bundles.ps1
src/vcpkg/vcpkgpaths.cpp

Due to the new bundle functionality of `.vcpkg-root`, vcpkg now issues read requests for the file during startup. Unfortunately, this conflicts with manifest mode's use of the file as a synchronization mechanism (mutex).
This PR fixes the issue by separating the bundle definition into a different file `vcpkg-bundle.json` which lives alongside `.vcpkg-root`.

Hotfix #21604 race condition on .vcpkg-lock

---

azure-pipelines/end-to-end-tests-dir/registries.ps1
include/vcpkg-test/util.h
include/vcpkg/base/jsonreader.h
include/vcpkg/base/optional.h
include/vcpkg/configuration.h
include/vcpkg/documentation.h
include/vcpkg/fwd/configuration.h
include/vcpkg/registries.h
include/vcpkg/sourceparagraph.h
include/vcpkg/vcpkgpaths.h
src/vcpkg-test/configmetadata.cpp
src/vcpkg-test/manifests.cpp
src/vcpkg-test/registries.cpp
src/vcpkg-test/util.cpp
src/vcpkg/base/json.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/build.cpp
src/vcpkg/configuration.cpp
src/vcpkg/help.cpp
src/vcpkg/install.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/portfileprovider.cpp
src/vcpkg/registries.cpp
src/vcpkg/sourceparagraph.cpp
src/vcpkg/vcpkgpaths.cpp

This PR is the first in the direction of substantially reducing the prevalence of `VcpkgPaths` in all vcpkg-tool internal functions. 
Specifically, this PR splits out parsing of the configuration documents (`configuration.cpp` & `RegistryConfig`) from the actual runtime behavior objects (`registries.cpp` & `RegistrySet` et al). Splitting these up has several advantages:
1. The parser is no longer data dependent -- it is fully static and constant. This capability is required in order to switch to better encapsulate the true dependencies at instantiation time and avoid pushing `VcpkgPaths` or further dependencies into the parser as runtime data.
2. Re-serializing configuration is more accurate and doesn't require the runtime objects to retain serializing information (comments, etc)
3. The …

Refactor apart 'config data' from 'behavior object' for registries

---

src/vcpkg/install.cpp

Fixes Microsoft/vcpkg#21631
Fundamentally, this bad experience was driven by trying to use the generic argument parser for two different commands based on hidden runtime information. I've chosen to resolve this issue by accepting the superset of behavior and provide more specific error messages when the superset does not apply to this case.
Before:
```
/workspaces/manifest $ vcpkg install zlib
Error: 'install' requires 0 arguments, but 1 were provided.
Example:
vcpkg install --triplet x64-windows
Options:
--dry-run                       Do not actually build or install
--head                          Install the libraries on the command line using the latest
upstream sources
...
```
After:
```
/workspaces/manifest $ vcpkg install zlib
Error: In manifest mode, `vcpkg install` does not …
```

Fix #21631 by improving error messages

---

include/vcpkg/configuration.h
include/vcpkg/install.h
include/vcpkg/paragraphs.h
include/vcpkg/portfileprovider.h
include/vcpkg/registries.h
src/vcpkg-test/configmetadata.cpp
src/vcpkg-test/registries.cpp
src/vcpkg/commands.edit.cpp
src/vcpkg/configuration.cpp
src/vcpkg/install.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/portfileprovider.cpp
src/vcpkg/registries.cpp
src/vcpkg/vcpkgpaths.cpp

This follows up #275 by removing `VcpkgPaths` from the `RegistrySet` interfaces, enabling many functions to take a `RegistrySet` instead of a whole `VcpkgPaths`.

Remove VcpkgPaths from RegistrySet interfaces

---

src/vcpkg.cpp

Set `CLICOLOR=0` to force cmake to output "plain" text (without ANSI escape codes)
(see [Terminal.c](https://github.com/Kitware/CMake/blob/29c80aec94b3607f3aae82170f0b3d0804de2aea/Source/kwsys/Terminal.c#L176-L182))
On Linux (and likely on other non-Windows platforms), CMake may "colorize" the output depending on the terminal type. This creates problems when `vcpkg` attempts to parse the output from CMake ([ex](https://github.com/microsoft/vcpkg-tool/blob/1b7edfa7196228006613d96657492e78d3e22043/src/vcpkg/cmakevars.cpp#L260-L264))
This PR would fix https://github.com/microsoft/vcpkg/issues/20430

Fix the cmake's output for vcpkg_get_dep_info()

---

src/vcpkg-test/dependencies.cpp
src/vcpkg/dependencies.cpp

Currently, there is a bug in manifest mode where if the top level manifest marks a package as `"default-features": false`, all downstream dependencies upon defaults on that package _will be ignored_. For example,
toplevel -> A, B[core]
A -> B (including defaults)
Expected result: A, B[1,2,3,...]
Current result: A, B[core]
This PR fixes that issue to achieve the expected result.

Fix overpowered default-features = false specification in manifest mode

---

src/vcpkg/commands.dependinfo.cpp

In PR #74, we added an addtional option `x-tree` to command `depend-info` sub option `--sort` but lack of the usage message.
Add it now.

[depend-info] Add x-tree to the usage message

---

src/vcpkg/commands.dependinfo.cpp
src/vcpkg/dependencies.cpp

In PR https://github.com/microsoft/vcpkg-tool/pull/184, we terminate the command early according to the `supports` field in `CONTROL`/`vcpkg.json`, which affects the command `depend-info`, and it does not support the parameter `--allow-unsupported`.
Now these error messages are always treated as warnings.

[depend-info] Turn errors into warnings when querying dependencies of unsupported triplet

---

src/vcpkg.cpp

Currently vcpkg crashes while displaying the crash message :D 
For example:
```
libc++abi: terminating with uncaught exception of type fmt::v8::format_error: argument not found
[1]    41566 abort      vcpkg install --enforce-port-checks --allow-unsupported
```

Fix crash message, the variable has the name `version`

---

src/vcpkg/base/files.cpp

`copy_regular_recursive_impl` didn't ignore . and ..

fix: ignore . and .. when copy regular recursive.

---

include/vcpkg/vcpkgpaths.h
locales/en.json
src/vcpkg/install.cpp
src/vcpkg/vcpkgpaths.cpp

Currently there are regressions around vcpkg paths initialization order. Failures during manifest manipulation want to use git to give the user better error messages, but that requires accessing the ToolCache, which fundementally depends on VcpkgPaths.
The fundamental error here is that `.scripts` was being initialized later. I've taken a "correct-by-construction" approach to preventing this entire class of errors by:
1. Making as many of the members `const` as possible. This ensures they can't be "late initialized" in the wrong order.
2. As a consequence of (1), performing as much initialization in the initializer list as reasonable. GCC warns if the initializer list ordering does not match the member order, so it is easy to optically inspect and ensure there aren't incorrect data …

Clarify VcpkgPaths initialization order and const-ify

---

src/vcpkg/commands.integrate.cpp

1. Fix path separator: from `/` to `\\` on Windows
2. Create directory _appdata_dst_path_ when it doesn't exist.
3. Check all the filesystem operation and report error when they failed.
```
PS C:\dev\vcpkg\> vcpkg.exe integrate install
Error: Failed to copy file: C:\dev\vcpkg\vcpkg\scripts\buildsystems\tmp\vcpkg.user.targets -> C:\Users\helpdesk\AppData\Local\vcpkg/vcpkg.user.targets
```
Fixse https://github.com/microsoft/vcpkg/issues/22413

Fix path separators, create appdata_dst_path and check file operation return value

---

azure-pipelines/pipelines.yml
src/vcpkg/commands.generate-message-map.cpp

this prevents PowerShell from adding CRLFs when doing a `>`
cc @BillyONeal

[x-generate-default-message-map] allow writing to a file directly

---

include/vcpkg/base/expected.h

This fixes a build failure with clang.
```
[ 78%] Building CXX object CMakeFiles/vcpkg-test.dir/src/vcpkg-test/mockcmakevarsprovider.cpp.o
In file included from /home/pi/repos/vcpkg-tool/src/vcpkg-test/mockcmakevarsprovider.cpp:1:
In file included from /home/pi/repos/vcpkg-tool/include/vcpkg-test/mockcmakevarprovider.h:3:
In file included from /home/pi/repos/vcpkg-tool/include/vcpkg/cmakevars.h:10:
In file included from /home/pi/repos/vcpkg-tool/include/vcpkg/packagespec.h:3:
/home/pi/repos/vcpkg-tool/include/vcpkg/base/expected.h:208:29: error: no member named 'invoke' in namespace 'std'; did you mean '__invoke'?
return std::invoke(f, *m_t.get(), static_cast<Args&&>(args)...);
~~~~~^~~~~~
__invoke
/usr/bin/../lib/gcc/arm-linux-gnueabihf/8/../../../../include/c++/8/bits/invoke.h:89:5: …
```

Fix build failure for clang

---

src/vcpkg/base/system.process.cpp
src/vcpkg/binarycaching.cpp

Close https://github.com/microsoft/vcpkg/issues/21905 bullet point 1.  
Code 127 normally means `command not found`, but that does not really makes sense here. Sometimes (not often) `unzip` returns 127 and sometimes not, when you retry it the return code is 0. I have no idea what the problem could be, but this implements a workaround by retrying the command once on mac when the return code is 127.

Retry popen on 127 osx

---

include/vcpkg/packagespec.h
src/vcpkg/commands.ci.cpp
src/vcpkg/packagespec.cpp

This is an attempt to fix the crash/regression in the "ci" command caused by https://github.com/microsoft/vcpkg-tool/pull/298
I'm pretty sure this is not a correct fix but it at least makes the ci command seem to match the last known good commit.

Fix CI crash by ensuring the "core" feature is installed for all ports.

---

src/vcpkg/base/files.cpp

Allow to view stdout-*.log files while build is in progress

[Windows] Make stdout-*.log readable (open in shared for reading mode) and non-buffered

---

include/vcpkg/base/basic_checks.h
src/vcpkg/base/checks.cpp
src/vcpkg/base/files.cpp

For example before vcpkg failed with:
```
read_contents(): No such file or directory
```
Now vcpkg prints:
```
/Users/leanderSchulten/git_projekte/vcpkg-tool/src/vcpkg/build.cpp(1349): read_contents(""): No such file or directory
```

Improve printed filesystem error message

---

include/vcpkg/base/files.h
src/vcpkg-test/files.cpp
src/vcpkg/base/files.cpp

This PR implements `Files::get_regular_files_recursive_proximate`, which returns a list of all regular files from a subdirectory without that base path prepended. The result is the same as if you called
```
// pseudocode
files = Files::get_regular_files_recursive(dir);
for (auto& file : files) {
file = file.lexically_proximate(dir);
}
```
However it generates the desired contents directly instead of "subtracting" after the fact on Linux.
This is needed for #296

Files::get_regular_files_recursive_proximate

---

include/vcpkg/base/expected.h
include/vcpkg/binarycaching.h
include/vcpkg/fwd/binarycaching.h
src/vcpkg-test/binarycaching.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/build.cpp
src/vcpkg/commands.buildexternal.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.setinstalled.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/install.cpp

This is fallout from code review / investigation of https://github.com/microsoft/vcpkg-tool/pull/331
* It ensures the binary cache does reasonable things when an action's ABI is not established, as if it were `--head`, and adds tests.
* In support of those tests, the `VcpkgPaths` is sucked out of a parameter passed through the binary cache and is made a member of the providers if necessary.
<expected.h>: Add the missing T& overloads used elsewhere.
<binarycaching.h>:
* Remove VcpkgPaths from the IBinaryProvider interface; add it as a member of the concrete implementations.
* Hoist BinaryConfigParserState (formerly State in binarycaching.cpp) here. It would be nice to make this more shiny, but hiding the definition of this struct wasn't buying us too much, and being unable to test stuff …

Insert "--head" defenses into the binary cache and block "default" when calculating feature ABIs.

---

include/vcpkg/base/cofffilereader.h
src/vcpkg/base/cofffilereader.cpp
src/vcpkg/postbuildlint.cpp

This (hopefully) allows ARM64 Emulation Compatible binaries to pass post-build lint.
https://blogs.windows.com/windowsdeveloper/2021/06/28/announcing-arm64ec-building-native-and-interoperable-apps-for-windows-11-on-arm/

Add ARM64EC to the MachineType enumeration

---

src/vcpkg/tools.cpp

Proposed fix for: https://github.com/microsoft/vcpkg/issues/22041
As concisely stated by @BRKVings - There are two types of output:
- cmake3 version x.x.x
- cmake version x.x.x
But the current code can't handle the first case.
This minor annoyance, just turned into a hard-blocker for me. I am proposing a change, which works in a minimal-repro program in Visual Studio 2022. I'm not familiar with your code-base. Could someone please test and promote, or propose an alternative that is inline VCPkg style guidelines?
(2nd try).

(Fix 22041) - vcpkg install - cmake version check should NOT reject valid response. (2nd try)

---

azure-pipelines/signing.yml

The "2022-02-01" release is broken because the CE build thought the date was 2022-01-31, while the vcpkg.exe build thought it was 2022-02-01. See https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=5694458&view=results
The pipeline.startTime variable appears to be reevaluated each time a job starts, and refers to the *job* start time, not the overall pipeline start time, so when a build crosses 4PM pacific time it produced broken output.
This change gets the first arch_independent stage to write the value it used, and this is fed into the remaining stages.

Lock VCPKG_BASE_VERSION in the first job for use in subsequent jobs.

---

azure-pipelines/Format-CxxCode.ps1
azure-pipelines/e2e_ports/mismatched-version-database/vcpkg-configuration.json
azure-pipelines/e2e_ports/mismatched-version-database/vcpkg.json
azure-pipelines/e2e_ports/mismatched-version-database/vcpkg_registry/ports/arrow/portfile.cmake
azure-pipelines/e2e_ports/mismatched-version-database/vcpkg_registry/ports/arrow/vcpkg.json
azure-pipelines/e2e_ports/mismatched-version-database/vcpkg_registry/ports/bloom-filter/portfile.cmake
azure-pipelines/e2e_ports/mismatched-version-database/vcpkg_registry/ports/bloom-filter/vcpkg.json
azure-pipelines/e2e_ports/mismatched-version-database/vcpkg_registry/versions/a-/arrow.json
azure-pipelines/e2e_ports/mismatched-version-database/vcpkg_registry/versions/b-/bloom-filter.json
azure-pipelines/e2e_ports/mismatched-version-database/vcpkg_registry/versions/baseline.json
azure-pipelines/end-to-end-tests-dir/versions.ps1
include/vcpkg/base/fwd/format.h
include/vcpkg/base/messages.h
include/vcpkg/sourceparagraph.h
include/vcpkg/versions.h
locales/messages.json
src/vcpkg/dependencies.cpp
src/vcpkg/portfileprovider.cpp
src/vcpkg/registries.cpp
src/vcpkg/versions.cpp

Fixes https://github.com/microsoft/vcpkg/issues/20503.
The fundamental issue in the thread was that the user's versions database did not match the actual retrieved files. This PR addresses the problem by adding an integrity check to ensure that files retrieved from a registry match the version declared in that registry's database files.
Before:
```
❯ vcpkg install --triplet x64-windows
Error: Cycle detected during arrow:x64-windows:
bloom-filter:x64-windows
```
After:
```
❯ vcpkg install --triplet x64-windows
Error: Failed to load port from D:\src\cycle_detected\./vcpkg_registry\ports/arrow: version specs did not match: 'arrow@6.0.0.20210925#4' != 'arrow@6.0.0.20210925'
Error: Failed to load port from D:\src\cycle_detected\./vcpkg_registry\ports/arrow: version specs did not match: …
```

Add check to ensure loaded port matches the declared version

---

include/vcpkg/archives.h
include/vcpkg/base/fwd/system.process.h
src/vcpkg/archives.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/export.prefab.cpp

Move (un)zip functions to archive.h and checks if (de)compression fails

---

src/vcpkg/commands.find.cpp
src/vcpkg/commands.search.cpp

This switch was broken when json was moved to the overall command parser frontend.

Fix --x-json for vcpkg search and vcpkg find port.

---

src/vcpkg/build.cpp

This PR is a needed tool change to enable https://github.com/microsoft/vcpkg/pull/22831 and comes with the added benefit of removing duplicate toolchain selection logic across the many helper scripts. With this, ports and helpers may always assume that `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` is defined to the correct toolchain to pull in.
+@neumann-a for review

Move toolchain decision making entirely into the tool

---

src/vcpkg/base/system.process.cpp

Fixes compilation issues on FreeBSD 13.0 using Clang11
```cpp
/root/vcpkg-tool/src/vcpkg/base/system.process.cpp:836:13: error: use of undeclared identifier 'WIFEXITED'
if (WIFEXITED(exit_code))
^
/root/vcpkg-tool/src/vcpkg/base/system.process.cpp:838:25: error: use of undeclared identifier 'WEXITSTATUS'
exit_code = WEXITSTATUS(exit_code);
^
/root/vcpkg-tool/src/vcpkg/base/system.process.cpp:840:18: error: use of undeclared identifier 'WIFSIGNALED'
else if (WIFSIGNALED(exit_code))
^
/root/vcpkg-tool/src/vcpkg/base/system.process.cpp:842:25: error: use of undeclared identifier 'WTERMSIG'
exit_code = WTERMSIG(exit_code);
^
/root/vcpkg-tool/src/vcpkg/base/system.process.cpp:844:18: error: use of undeclared identifier 'WIFSTOPPED'
else if (WIFSTOPPED(exit_code))
^ …
```

Adds missing include for WIFEXITED on FreeBSD

---

src/vcpkg/archives.cpp

A potential fix for 
- https://github.com/microsoft/vcpkg/issues/19490 
- https://github.com/microsoft/vcpkg/issues/23284
Cf. https://github.com/microsoft/vcpkg/issues/19490#issuecomment-1053580397, https://devblogs.microsoft.com/setup/waiting-for-msiexec-exe-to-finish/

Run msiexec with start /wait

---

include/vcpkg/base/fwd/system.process.h
include/vcpkg/base/strings.h
include/vcpkg/base/system.process.h
src/vcpkg/archives.cpp
src/vcpkg/base/downloads.cpp
src/vcpkg/base/strings.cpp
src/vcpkg/base/system.process.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/build.cpp
src/vcpkg/cmakevars.cpp
src/vcpkg/commands.env.cpp
src/vcpkg/commands.integrate.cpp
src/vcpkg/commands.portsdiff.cpp
src/vcpkg/configure-environment.cpp
src/vcpkg/export.chocolatey.cpp
src/vcpkg/export.cpp
src/vcpkg/export.ifw.cpp
src/vcpkg/vcpkgpaths.cpp

Currently our PR and CI builds in the catalog repo are failing with the message:
````
Extracting 7zip...
msiexec failed while extracting 'D:\downloads\7z1900-x64.msi' with message:
T
##[error]vcpkg ci failed
````
Example: https://dev.azure.com/vcpkg/public/_build/results?buildId=68039&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=491b9f02-7edc-5990-cda1-511e95a3768e
The single character combined with msiexec being a Windows application suggests that it is trying to print UTF-16.
This change adds a new Encoding parameter to our cmd_execute_Xxx functions and passes in UTF-16 for msiexec.

Read msiexec output as UTF-16.

---

include/vcpkg/archives.h
include/vcpkg/base/system.h
include/vcpkg/fwd/tools.h
include/vcpkg/tools.h
src/vcpkg/archives.cpp
src/vcpkg/base/system.cpp
src/vcpkg/base/system.process.cpp
src/vcpkg/tools.cpp

This is a more targeted hotfix version of https://github.com/microsoft/vcpkg-tool/pull/404 as there are outstanding code review discussions there. (I do still intend to apply the changes therein but don't want code reviewers to feel like they can't say anything because it's resolving a high priority issue)

Use System32\tar.exe if present instead of 7zip for zip archives.

---

include/vcpkg/base/format.h

Some old code did `const char* top = data::digits[exp / 100]`;
in that case, `exp < 10000 => exp / 100 < 100`, and thus that was not _actually_ broken,
but the warning still fired so it had to be disabled.
However, in new code they now do:
`const char* top = digits2(to_unsigned(exp / 100))`,
and thus this warning is no longer hit.
Since this is a useful warning, we don't want to disable it,
and thus we are re-enabling it.

[format] remove disable 6385

---

include/vcpkg/base/jsonreader.h
include/vcpkg/base/optional.h
include/vcpkg/base/pragmas.h
include/vcpkg/base/system_headers.h
src/vcpkg-test/manifests.cpp
src/vcpkg-test/strings.cpp
src/vcpkg-test/system.cpp
src/vcpkg/base/files.cpp
src/vcpkg/base/system.process.cpp
src/vcpkg/export.cpp

try to find all the warnings that are still an issue in modern VS
Also, standardize on `VCPKG_MSVC_WARNING`

re-enable disabled warnings which are no longer relevant

---

include/vcpkg/archives.h
include/vcpkg/tools.h
src/vcpkg/archives.cpp
src/vcpkg/tools.cpp

Following up from https://github.com/microsoft/vcpkg-tool/pull/407#issuecomment-1058798498 and the continued issues with msiexec, this PR implements a stopgap solution until we can ship unzip functionality directly in the vcpkg binary.
The approach in this PR is:
1. Make the primary `7zip` tool come from the `.7z` archive
2. Move the existing msi-based acquisition to `7zip_msi`
3. Use `cmake` to extract `.7z` files
4. Special case extracting `cmake` to use the first of:
a. C:\Windows\System32\tar.exe
b. `7zip_msi`
This means that Windows 10 users should not run msiexec at all as part of the core operation of vcpkg. Windows 7 users will either need to install a recent version of CMake _or_ we will use msiexec. 7zip is 100% fetchable without msiexec once we have cmake, so we can still use …

Reduce msiexec round 2

---

locales/messages.en.json
locales/messages.json
src/vcpkg/commands.add.cpp

https://github.com/microsoft/vcpkg-tool/pull/301/ broke add artifact by flipping the sense of check_exit: it is "ensure that this is true" not "fail when this is true".
Drivebys: `add port` was also broken because it would try to add a port named "port".
60: Fix the flipped sense.
78: Replace fmap with a for loop starting at 1 to skip the selector.
80: Use Expected::value_or_exit which was equivalent to the previous behavior of printing the message followed by exit_fail.
84: Similarly combine printing msgAddTripletExpressionNotAllowed and exit_failure into msg_exit_with_message.
126: Similarly, write_contents' default behavior of exiting and printing the path in question with VCPKG_LINE_INFO was equivalent to checking error_code

Fix add artifact regression "you can only add one artifact at a time"

---

include/vcpkg/base/util.h
src/vcpkg/postbuildlint.cpp

The cofffilereader fails when reading .a files with 'Could not find proper second linker member'
Fixes https://github.com/microsoft/vcpkg/issues/23450

no lib arch checks for mingw

---

src/vcpkg/build.cpp

`vcpkg_find_acquire_program` takes care of it any way!

Remove ninja requirement

---

src/vcpkg/archives.cpp
src/vcpkg/base/system.process.cpp

https://github.com/microsoft/vcpkg/pull/23367 was a failure because we still end up trying to download portable git; however as some combination of changes in attempt to debug we drop all msiexec output on the floor now.
This reverts change to add start /wait, replaces nulls with ?s.

Revert start /wait for msiexec and change nulls to ? in UTF-8 mode.

---

src/vcpkg/base/system.process.cpp

This variable is used to point git towards a binary that
implements git's credential-manager interface, and can be used
by git to authenticate for private repositories.
Closes Microsoft/vcpkg#23225

Keep GIT_ASKPASS environment variable

---

azure-pipelines/end-to-end-tests-dir/ci.ps1
src/vcpkg/commands.ci.cpp

Processing triplet from command-arguments is a historical artifact from back when the ci command supported multiple triplets at once.

[ci] Change triplet to be processed the same way as how other commands get their triplet.

---

include/vcpkg/binarycaching.h
src/vcpkg/binarycaching.cpp

Sometimes it's essential to be able to read/write binary cache to AWS S3 anonymously (mostly read, I assume).
AWS cli tool requires to be run with --no-sign-request option to get anonymous access.
This PR adds new 'x-aws-config' option to configure AWS anonymous access.
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

Add AWS anonymous access when reading/writing binary cache to AWS S3.

---

include/vcpkg/base/parse.h
src/vcpkg/packagespec.cpp

In https://github.com/microsoft/vcpkg-tool/pull/345#discussion_r831389137 Nicole indicated that the workaround here to support features with _ in their names is no longer relevant because the feature in question was already renamed before versioning.
Since this is a change in the usable surface of the tool I extracted the change into its own more targeted PR.

Block features containing _ in their names.

---

README.md

While looking at the documentation on data collection, I noticed that the link to `privacy.md` was broken. This commit copies the file from `vcpkg` repository and fixes the link in `README.md`.

Copy privacy.md from vcpkg repo

---

CMakeLists.txt
include/vcpkg/base/stringliteral.h
include/vcpkg/base/stringview.h
src/vcpkg/base/messages.cpp

These changes address 2 issues that have blocked compilation on Raspberry Pi OS since Oct 29, 2021.
The first fix is found in StringView. With gcc 8.3, compilation failed due to ambiguous resolution of constructor overloads. This fix adds a new constructor for any type based on ZStringView. The template constructor allows the compilation to avoid a circular dependency that would be seen if the constructor was specifically written to use the ZStringView type. This addresses https://github.com/microsoft/vcpkg/issues/21142.
The second fix is the next issue that surfaces once the ambiguous issue is resolved. The fix is simply adding the atomic library to the link list for vcpkglb. This addresses https://github.com/microsoft/vcpkg/issues/22843.
The combo of these two fixes allows compilation …

Updated StringView and link list for vcpkglib

---

azure-pipelines/signing.yml

Azure DevOps Pipelines appears to treat 'empty string' as 'there is no default' and thus makes filling in VCPKG_BASE_VERSION required when queueing builds.
This change just sets the default to the string 'default' and treats that as a request for the automatically generated date version.

Allow manual queuing of signed builds without overriding the base version.

---

src/vcpkg/base/downloads.cpp

Without this option, curl does not create intermediate directories
and thus trying to retrieve binary cache from az blob storage
fails if the `buildtrees` and its various subdirectories for ports
are not already present.
The alternative is for vcpkg to create the intermediate dirs
explicitly, but we already use the option in `try_download_file`,
so there is no reason not to use it here as well.
-----
Tests: not sure how to add tests for this, if you have any ideas
I don't mind adding them.

Add --create-dirs to curl call in download_files_inner

---

CMakeLists.txt

Added missing CheckCXXSourceCompiles include.
Closes https://github.com/microsoft/vcpkg/issues/23842.

Added missing CheckCXXSourceCompiles include

---

include/vcpkg/base/cache.h
include/vcpkg/base/expected.h

ExpectedT tried to use enable_if but forgot the ::type, so no SFINAE was applied.

Fix broken SFINAE in expected, and consistently enable_if_t.

---

src/vcpkg/base/downloads.cpp

As far as I can tell, these are used as a combination of simple
disambiguation for the different curl callsites and a normalized
output prefix to be stripped later.
However, two functions, `url_heads_inner` and `download_files_inner`
ended up with the same guid, so I generated a new one for the
latter, so that they are unique again.

Change guid_marker in download_files_inner to be unique

---

cgmanifest.json

We are using outdated commit hashes for each of these dependencies in our cgmanifest.json;
this is an internal legal thing.

[cgmanifest] correct CommitHashes for catch2 and fmt

---

src/vcpkg/metrics.cpp

This allows us to distinguish between telemetry from old versions where this was untracked from new versions where the tracked properties are explicitly not used.

Always track properties with boolean value

---

azure-pipelines/e2e_ports/overlays/classic-versions-a/portfile.cmake
azure-pipelines/e2e_ports/overlays/classic-versions-a/vcpkg.json
azure-pipelines/e2e_ports/overlays/classic-versions-b/portfile.cmake
azure-pipelines/e2e_ports/overlays/classic-versions-b/vcpkg.json
azure-pipelines/end-to-end-tests-dir/classic-versions.ps1
include/vcpkg/binaryparagraph.h
include/vcpkg/dependencies.h
include/vcpkg/versions.h
locales/messages.en.json
locales/messages.json
src/vcpkg-test/binarycaching.cpp
src/vcpkg-test/dependencies.cpp
src/vcpkg-test/spdx.cpp
src/vcpkg/build.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/install.cpp
src/vcpkg/versions.cpp

This PR adds tracking for version constraints in classic mode so that they can be displayed to the user in case of a build failure. While it is by design that classic mode does not force users to rebuild dependencies that are out-of-date, knowing the version constraints is a big help for debugging.
The output could be rough in certain circumstances; it will display every non-identical broken constraint and won't deduplicate 'similar' ones. For example, if the immediate dependencies list contains 3 references to `curl` with constraints `>= 2`, `>= 2`, and `>= 3`, on build failure this would display two messages (one for `>= 2` and one for `>= 3`). This more complex deduplication is challenging to prove correct because we don't have schema information for installed packages. That said, it …

Warn on classic mode build failure if version constraints weren't met

---

CMakeLists.txt

Fix error: undefined reference to '__android_log_write'.

Link vcpkg-test to log library on Android

---

include/vcpkg/build.h
locales/messages.en.json
locales/messages.json
src/vcpkg/build.cpp
src/vcpkg/install.cpp

Resolves https://github.com/microsoft/vcpkg/issues/24029
Before (2022-03-30):
Currently: (vcpkg crashes, regression in 8e8fb17dde45aa1f5c05257377b959b8d583dcd5 )
After:

Add a build result type for removed.

---

src/vcpkg/base/hash.cpp
src/vcpkg/metrics.cpp

While doing some performance analysis, two global constructors showed up in the trace.
Changes:
1. Initialize the BCrypt algorithm handles on first use using function statics.
2. There is no need to initialize the `MetricsMessage` with a random id+timestamp -- those are always filled by `Metrics::enable()`.

Reduce work done in global constructors

---

include/vcpkg/base/util.h
locales/messages.en.json
locales/messages.json
src/vcpkg/install.cpp

As requested in https://github.com/microsoft/vcpkg/issues/20190#issuecomment-1092125077

Add heuristic message.

---

azure-pipelines/e2e_ports/integrate-install/NoProps.vcxproj
azure-pipelines/e2e_ports/integrate-install/Project1.vcxproj
azure-pipelines/e2e_ports/integrate-install/VcpkgTriplet.vcxproj
azure-pipelines/e2e_ports/integrate-install/VcpkgTriplet2.vcxproj
azure-pipelines/e2e_ports/integrate-install/VcpkgUseStatic.vcxproj
azure-pipelines/e2e_ports/integrate-install/VcpkgUseStatic2.vcxproj
azure-pipelines/e2e_ports/integrate-install/VcpkgUseStaticManifestHost.vcxproj
azure-pipelines/end-to-end-tests-dir/fetch.ps1
azure-pipelines/end-to-end-tests.ps1
azure-pipelines/pipelines.yml

* Change PlatformToolset to v143.
* Make e2e tests figure out the right Triplet to use on their own (previously, the vs-integration tests only passed given x86-windows so we may as well just lock it to that)
* Provide a default WorkingRoot in a reasonable place.
* Add CMake entries to the vcpkgTools.xml used in testing so that the tests pass if CMake is needed to extract a zip.

Fix end to end tests on VS2022 only systems.

---

azure-pipelines/signing.yml
vcpkg-init/lock-versions.ps1
vcpkg-init/vcpkg-init
vcpkg-init/vcpkg-init.ps1

Implements https://devdiv.visualstudio.com/DevDiv/_backlogs/backlog/Vcpkg%20Package%20Manager/Scenarios/?workitem=1527667

Update when the user runs a new copy of vcpkg-init rather than just assuming things are already OK.

---

include/vcpkg/base/hash.h
src/vcpkg/base/hash.cpp
src/vcpkg/commands.add.cpp
src/vcpkg/commands.find.cpp

introduced in https://github.com/microsoft/vcpkg-tool/commit/0840ffdf10c20c23fc5b9a048e1d7f896e3e76b1
These commands called into CE bits, and exit_with_code, while holding the lock. This causes an immediate crash on shutdown because the lock is reentered. This change ensures that a minimal amount of code runs while holding the lock.

Fix crash-on-shutdown around all "CE" powered commands

---

src/vcpkg/tools.cpp

If VCPKG_FORCE_SYSTEM_BINARIES is not set, then always use downloadable tool defined in vcpkgTools.xml
This effectively prevents vcpkg from using installed system binaries that can cause errors if their version if greater than vcpkg requested one. A recent example is a change in CMake that broke vcpkg.
This also fixes https://github.com/microsoft/vcpkg/issues/17712

Fix #17712: Always using downloadable tool

---

locales/messages.en.json
src/vcpkg/cmakevars.cpp

When `VCPKG_FORCE_SYSTEM_BINARIES` is set and cmake is not installed, the install command will stop and no specific information is printed:
```pwsh
PS F:\vcpkg> .\vcpkg.exe install ctemplate
Computing installation plan...
PS F:\vcpkg>
```
Output with `--debug`:
```pwsh
PS F:\vcpkg> .\vcpkg.exe install ctemplate --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Failed to open: F:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=0, usegitregistry=0, embeddedsha=nullopt
[DEBUG] Using builtin-ports: F:\vcpkg\ports
[DEBUG] Using installed-root: F:\vcpkg\installed
[DEBUG] Using buildtrees-root: F:\vcpkg\buildtrees …
```

Output error text if cmake failed during triplet var detection

---

include/vcpkg/commands.setinstalled.h
src/vcpkg/commands.setinstalled.cpp
src/vcpkg/install.cpp

I tried to run `--only-downloads` in manifest mode with `cmake -DVCPKG_INSTALL_OPTIONS='--only-downloads' ..`. It fails: I found it was because the `keep_going` option was always `Install::KeepGoing::NO` in manifest mode. [A conversation on Discord](https://discord.com/channels/400588936151433218/687365466422902841/977233093649903626) confirmed that this behavior was a bug and not "by design".
This pull request solves this bug.

Fix --only-downloads and --keep-going in manifest mode

---

src/vcpkg/archives.cpp

Error message in `extract_tar_cmake` was copied over from `extract_tar` without changing the name of the tool from `tar` to `CMake`

[archives] Fix typo

---

src/vcpkg/dependencies.cpp

Currently, Expected<T> has a bug for references, in that it is default constructible, but references shouldn't be default constructible. (This is hidden because we store a pointer internally).
In VersionedPackageGraph::require_port_version, an ExpectedS<T&> is default constructed, which is in the "impossible" state of neither having a stored T (since references can't be default constructed), but also not being assigned an error state.
This change hoists the only place where the ExpectedS could contain an error into an early-return, allowing a plain pointer to be used, and avoiding constructing the impossible thing.
(The bug in Expected that allowed this to happen is fixed in https://github.com/microsoft/vcpkg-tool/pull/511 , but this change was tricky enough I thought extracting it for …

Don't attempt to default-construct a reference.

---

src/vcpkg/tools.cpp

Resolves https://github.com/microsoft/vcpkg/issues/24950
This "to_printf_arg" thing needs to die.

Avoid returning the address of a temporary.

---

src/vcpkg/binarycaching.cpp

Currently when downloading file while doing binary caching lookup fails with an error because there is a cache miss, msbuild interprets this as an error and fails the build step. Also, this adds a fatal error message in the log that is usually not ok because cache miss is a normal and expected situation.
This PR adds a stat operation before actual file download on cache lookup to eliminate fatal error and prettify log a little.
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

[AWS] Stat file before downloading it when doing binary cache lookup.

---

src/vcpkg/base/system.process.cpp
src/vcpkg/commands.civerifyversions.cpp

Fixes these warnings when compiling with GCC 11:
```
[build] /vcpkg/commands.civerifyversions.cpp: In function ‘vcpkg::ExpectedS<std::__cxx11::basic_string<char> > vcpkg::Commands::CIVerifyVersions::verify_version_in_db(const vcpkg::VcpkgPaths&, std::map<std::__cxx11::basic_string<char>, vcpkg::Version, std::less<void> >, vcpkg::StringView, const vcpkg::Path&, const vcpkg::Path&, const string&, bool)’:
[build] /vcpkg/commands.civerifyversions.cpp:93:41: warning: loop variable ‘control_file’ of type ‘const string&’ {aka ‘const std::__cxx11::basic_string<char>&’} binds to a temporary constructed from type ‘const char* const’ [-Wrange-loop-construct]
[build]    93 |                 for (const std::string& control_file : {"CONTROL", "vcpkg.json"})
[build]       | …
```

Fix Linux warnings

---

CMakeLists.txt
src/vcpkg-fuzz/main.cpp
src/vcpkg.manifest

This enables vcpkg to be longPathAware, opts in to current Windows behavior, and the current heap implementation.
Drive by fix for:
```
FAILED: CMakeFiles/vcpkg-fuzz.dir/src/vcpkg-fuzz/main.cpp.o
/usr/bin/c++  -DFMT_LOCALE -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -I../include -I_deps/fmt-src/include -O3 -DNDEBUG   -Wall -Wextra -Wpedantic -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-redundant-move -Wmissing-declarations -Werror -std=c++17 -MD -MT CMakeFiles/vcpkg-fuzz.dir/src/vcpkg-fuzz/main.cpp.o -MF CMakeFiles/vcpkg-fuzz.dir/src/vcpkg-fuzz/main.cpp.o.d -o CMakeFiles/vcpkg-fuzz.dir/src/vcpkg-fuzz/main.cpp.o -c ../src/vcpkg-fuzz/main.cpp
../src/vcpkg-fuzz/main.cpp: In function ‘int main(int, char**)’:
../src/vcpkg-fuzz/main.cpp:214:5: error: ‘args’ may be …
```

Add vcpkg application manifests.

---

ce/ce/archivers/git.ts
ce/ce/artifacts/activation.ts
ce/ce/cli/command-line.ts
ce/ce/constants.ts
ce/ce/installers/git.ts
ce/ce/main.ts
ce/ce/session.ts
ce/ce/vcpkg.ts
include/vcpkg/archives.h
include/vcpkg/base/fwd/messages.h
include/vcpkg/base/messages.h
include/vcpkg/tools.h
include/vcpkg/vcpkgpaths.h
manual-testing/git-install-sources.md
src/vcpkg/archives.cpp
src/vcpkg/base/messages.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/build.cpp
src/vcpkg/buildenvironment.cpp
src/vcpkg/commands.fetch.cpp
src/vcpkg/commands.integrate.cpp
src/vcpkg/commands.regenerate.cpp
src/vcpkg/configure-environment.cpp
src/vcpkg/export.chocolatey.cpp
src/vcpkg/export.cpp
src/vcpkg/export.ifw.cpp
src/vcpkg/export.prefab.cpp
src/vcpkg/tools.cpp
src/vcpkg/vcpkgpaths.cpp

* Adds `--x-from-script` to `fetch` to make some attempt to make stdout only the resulting path so that scripts can embed fetching paths:
* Teaches "ce" to look for `VCPKG_COMMAND` to find a vcpkg to launch, and to call `vcpkg fetch git` to get git's path.
* (Drive by) Fix vcpkg's mapping for the regenerate command.
* (Drive by) Spell check a few things.

[vcpkg-artifacts] Find git using `vcpkg fetch git`.

---

src/vcpkg/portfileprovider.cpp

In OverlayProviderImpl::load_all_control_files, overlay directories are consulted in consecutive order. Each consulted directory overwrites any overlays that were visited previously. This means that given multiple overlays, the last one wins.
However, in OverlayProviderImpl::load_port, the overlay directories are still consulted in consecutive order, but the first one is chosen. This means that the result will be different than load_all_control_files if multiple overlays contain the same port.
Based on e2e tests, the intent appears to be that the first overlay wins, so we need to do load_all_control_files in reverse order.

Load overlay ports in the correct order.

---

src/vcpkg/commands.ci.cpp

Fixes https://github.com/microsoft/vcpkg/pull/24526#issuecomment-1116847668,
`Error: 'method' is a duplicate attribute name.`
In today's tool output I found this pattern:
~~~xml
<test name="elfutils:x64-linux" method="elfutils[core]:x64-linux" time="11" method="Fail">
~~~
where I expected [this pattern](https://github.com/microsoft/vcpkg/pull/23477#issuecomment-1068657817):
~~~xml
<test name="abseil:x64-windows" method="abseil[core]:x64-windows" time="13" result="Pass">
~~~

Fix xunit output errors, trim result list

---

include/vcpkg/tools.h
src/vcpkg/tools.cpp

Add Python3WithVEnvProvider which is python with venv/pip support.
`expresif` artifacts, and a few ports that want to talk to `pip` need a `venv`-enabled copy of Python. `venv` is typically a separate apt package, so we don't want to change the behavior of the existing "python" tool name / behavior. This adds `python_with_venv` which is python with `pip` and `venv`.
To test on Windows, cherry pick https://github.com/BillyONeal/vcpkg/commit/d0525e0f8ede44a6407ddfad0e8217a237d3cae7 into your vcpkg-root.

Add "vcpkg fetch python3_with_venv" which is a venv-enabled python.

---

include/vcpkg/base/downloads.h
include/vcpkg/binarycaching.h
src/vcpkg/base/downloads.cpp
src/vcpkg/binarycaching.cpp

Fixes https://github.com/microsoft/vcpkg-tool/pull/558#issuecomment-1158239080
There were actually two issues: 
1. Headers are send twice
2. azure blob headers meant for put requests are also send in get requests (I didn't know that and thought it would be ok to also send them in get requests)

Fixes azure blob binary caching by not sending put headers for get requests and by sending headers only once

---

src/vcpkg/visualstudio.cpp

Then the arm64 version of the compiler is used

Detect arm64 VS 2022

---

azure-pipelines/end-to-end-tests-dir/fetch.ps1

Azure Pipelines has started putting a ninja on the PATH which causes the fetch test that assumes it needs to download ninja to fail. For example: https://dev.azure.com/vcpkg/public/_build/results?buildId=74025&view=results
```
2022-06-22T02:18:32.8686866Z D:\a\1\s\build.x86.debug\vcpkg.exe --triplet x86-windows --x-buildtrees-root=D:\a\1\s\build.x86.debug\work\testing\buildtrees --x-install-root=D:\a\1\s\build.x86.debug\work\testing\installed --x-packages-root=D:\a\1\s\build.x86.debug\work\testing\packages --overlay-ports=D:\a\1\s\azure-pipelines/e2e_ports/overlays --overlay-triplets=D:\a\1\s\azure-pipelines/e2e_ports/triplets fetch ninja --vcpkg-root=D:\a\1\s\build.x86.debug\work\testing
2022-06-22T02:18:32.9948628Z C:\ProgramData\Chocolatey\bin\ninja.exe
2022-06-22T02:18:33.0083411Z …
```

Fix fetch tests on systems that already have Ninja on the PATH.

---

src/vcpkg/postbuildlint.cpp

This was discovered in attempting to update the Windows SDK in https://github.com/microsoft/vcpkg/pull/25260/ ; this Windows SDK has arm64x libraries that contain both arm64 and arm64ec architecture code.

Don't crash when there is more than one architecture type in a lib.

---

include/vcpkg/base/jsonreader.h
include/vcpkg/base/messages.h
include/vcpkg/paragraphs.h
include/vcpkg/sourceparagraph.h
src/vcpkg-test/manifests.cpp
src/vcpkg/base/json.cpp
src/vcpkg/base/messages.cpp
src/vcpkg/base/parse.cpp
src/vcpkg/commands.add.cpp
src/vcpkg/commands.civerifyversions.cpp
src/vcpkg/commands.format-manifest.cpp
src/vcpkg/commands.porthistory.cpp
src/vcpkg/install.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/sourceparagraph.cpp

SPDX license parsing warnings were being emitted directly to stdout during manifest deserialization. We should never do this.
Drive-by fixes:
1. I've added a missing trailing newline as part of `print_error_message()`.
2. Added detection of `error: ` as another valid "error" message.
New behavior:
```
$ vcpkg format-manifest vcpkg.json
/workspaces/vcpkg-tool/vcpkg.json: $.license (an SPDX license expression): warning: Unknown license identifier 'hello'. Known values are listed at https://spdx.org/licenses/
on expression: hello
^
Failed to parse manifest file: /workspaces/vcpkg-tool/vcpkg.json
error: while loading /workspaces/vcpkg-tool/vcpkg.json:
$ (a manifest): missing required field 'name' (an identifier)
$ (a manifest): expected a versioning field (example: version-string)
```

Never print directly from deserialization code

---

README.md

Following the instructions as-is fails because of junction points.
```powershell
rmdir : C:\Users\bemcmorr\.vcpkg\node_modules\vcpkg-ce\common\temp\node_modules\.pnpm\node_modules\keyv is an NTFS
junction point. Use the Force parameter to delete or modify this object.
At line:1 char:1
+ rmdir -recurse ~/.vcpkg
+ ~~~~~~~~~~~~~~~~~~~~~~~
```

Fix removal instructions for PowerShell

---

src/vcpkg/base/system.mac.cpp

Treat FreeBSD like macOS (which is accurate in terms of development!) in the code to determine the MAC address of a network interface.
With this change, vcpkg-tool compiles fine on FreeBSD 13. The test suite passes.

Add FreeBSD support

---

src/vcpkg/metrics.cpp

Fix regression where the `"time"` field in our metrics message was left empty.

[telemetry] Initialize timestamp in metrics message

---

src/vcpkg/install.cpp

The usage files in microsoft/vcpkg have an extra empty line between `xy provides CMake targets` and the `find_package` line.

Fix formatting for usage suggestion

---

cmake/Findfmt.cmake
include/vcpkg/base/fwd/format.h

* Fixed build against packaged fmt 9.1.0.
* Updated bundled fmt to version 9.1.0.
* Performed refactoring of `Findfmt.cmake`.
Closes https://github.com/microsoft/vcpkg/issues/25673
Copy of #634.

Updated fmt to version 9.1.0

---

src/vcpkg/commands.integrate.cpp

After the PR https://github.com/microsoft/vcpkg-tool/pull/619, the prompt information after executing `./vcpkg integrate install` under windows becomes the following:
The information here is all crowded together and the user experience will be bad.
For fixing this issue, I've added two newlines here, and the modified result looks like this:

Optimize the message of integrate install

---

include/vcpkg/metrics.h
src/vcpkg-test/metrics.cpp
src/vcpkg/commands.zpreregistertelemetry.cpp
src/vcpkg/metrics.cpp

This exposes that the lists of all metrics are actually std::arrays, which allows for compile time enforcement of properties like:
* All metrics have entries in the name list
* COUNT is the last entry in the enum list
* All string metrics have corresponding example values

Statically enforce some metrics properties at compile time.

---

include/vcpkg/commands.setinstalled.h
src/vcpkg/commands.setinstalled.cpp
src/vcpkg/install.cpp

#697 changed vcpkg's behavior.
It used to be possible to call `$VCPKG_ROOT/vcpkg install --only-downloads`  and get an exit code of `0`. This could be useful to, for instance, download dependencies' sources in order to scan them with [Snyk](https://snyk.io/).
After #697, the exit code is now `1`, and the GitHub Workflow fails before the Snyk scan.
I do not change the behavior of `--keep-going`, but I re-establish the original behavior of `--only-downloads`. Hence, `$VCPKG_ROOT/vcpkg install --only-downloads` succeeds with the exit code `0`.
I tested that the fix behaves as expected manually, making sure that I get an exit code of `1` without the fix and an exit code of `0` with the fix.
c.c. @ras0219-msft from #697 and @BillyONeal from our discussion on Discord.

Get exit code of 0 with --only-downloads option

---

vcpkg-init/mint-standalone-bundle.ps1

Olga discovered that vcpkg-cmake expects a LICENSE.txt in `VCPKG_ROOT`. This includes that in the standalone bundle.
See https://github.com/microsoft/vcpkg/blob/57d3194e702a2959e86a6748999ad71fc24f7922/ports/vcpkg-cmake/portfile.cmake#L13

Add LICENSE.txt to the one-liner.

---

include/vcpkg/commands.setinstalled.h
src/vcpkg/commands.setinstalled.cpp
src/vcpkg/install.cpp

Simple change to support --no-print-usage for manifest-mode installs.

Add option --no-print-usage to disable manifest-mode usage info

---

ce/ce/artifacts/artifact.ts
ce/ce/cli/commands/activate.ts

```
$ type .\vcpkg-configuration.json
{
"default-registry": { /* ... */ },
"registries": [ /* ... */ ],
"demands": {
"example:hello": {
"error": "example:hello matched"
},
"example:world and x86": {
"error": "example:world & x86 matched"
},
"example:world and x64": {
"error": "example:world & x64 matched"
},
"arm": {
"error": "arm matched"
}
}
}
$ vcpkg activate --example hello
warning: vcpkg-artifacts are experimental and may change at any time.
ERROR: c:\Dev\test\vcpkg-configuration.json - example:hello matched
$ vcpkg activate --example world
warning: vcpkg-artifacts are experimental and may change at any time.
ERROR: c:\Dev\test\vcpkg-configuration.json - example:world & x64 matched
$ vcpkg activate --example world --x86
warning: vcpkg-artifacts are experimental and may change at any …
```

Check for error, warning, and message in vcpkg-configuration.json.

---

azure-pipelines/e2e_ports/version-variable/version-date/portfile.cmake
azure-pipelines/e2e_ports/version-variable/version-date/vcpkg.json
azure-pipelines/e2e_ports/version-variable/version-semver/portfile.cmake
azure-pipelines/e2e_ports/version-variable/version-semver/vcpkg.json
azure-pipelines/e2e_ports/version-variable/version-string/portfile.cmake
azure-pipelines/e2e_ports/version-variable/version-string/vcpkg.json
azure-pipelines/e2e_ports/version-variable/version/portfile.cmake
azure-pipelines/e2e_ports/version-variable/version/vcpkg.json
azure-pipelines/end-to-end-tests-dir/version-variable.ps1
src/vcpkg/build.cpp

This is a frequently requested feature. With this one can use the `${PORT_VERSION}` variable inside `portfile.cmake` to get the currents port version.

pass VERSION to cmake when building port

---

CMakeLists.txt

Require explicit extensions for source files, do not guess.
The extra calls to GetFileAttributesW significantly slow down cmake on Windows. https://gitlab.kitware.com/cmake/cmake/-/issues/23154

Set CMP0115 to new

---

include/vcpkg/base/expected.h
include/vcpkg/base/git.h
include/vcpkg/base/messages.h
include/vcpkg/vcpkgpaths.h
locales/messages.en.json
locales/messages.json
src/vcpkg-test/expected.cpp
src/vcpkg/base/git.cpp
src/vcpkg/base/messages.cpp
src/vcpkg/vcpkgpaths.cpp

Appends an additional error message when a built-in repository error occurs and vcpkg is cloned into a shallow repository.
Rough implementation. 
Improvements to how we handle versioning errors can be made but I believe is better to wait until #556 is merged to make more extensive changes. 
On baseline not in git history:
On version not in git history:

[versioning] Add message when vcpkg is cloned to a shallow repository

---

.gitignore
include/vcpkg/base/system.h
include/vcpkg/cgroup-parser.h
include/vcpkg/metrics.h
src/vcpkg-test/cgroup-parser.cpp
src/vcpkg.cpp
src/vcpkg/base/system.cpp
src/vcpkg/cgroup-parser.cpp
src/vcpkg/metrics.cpp

Implement basic container detection heuristics:
Working on Linux container:
Working on Windows container

[Telemetry] Detect if vcpkg is running in a container

---

src/vcpkg/base/json.cpp
src/vcpkg/portfileprovider.cpp

This is a more efficient approach

Use make_unique instead of reset

---

docs/localization.md

This PR adds documentation for how to change the language in vcpkg ( i.e., documenting our use of the VSLANG environment variable).

Documenting our use of VSLANG

---

ce/ce/registries/ArtifactRegistry.ts

This fixes being unable to add / use / etc. artifacts filtered for a particular registry.
Before:
```
PS C:\Dev\test> ..\vcpkg\vcpkg.exe find artifact gcc
warning: vcpkg-artifacts are experimental and may change at any time.
Downloading vcpkg-ce bundle 2022-10-17...
Artifact                     Version         Summary
microsoft:compilers/arm/gcc  2020.10.0       GCC compiler for ARM CPUs.
arm:gcc                      10.3.0-2021.10  GCC compiler for ARM CPUs.
PS C:\Dev\test> ..\vcpkg\vcpkg.exe find artifact arm:gcc
warning: vcpkg-artifacts are experimental and may change at any time.
Artifact  Version         Summary
arm:gcc   10.3.0-2021.10  GCC compiler for ARM CPUs.
PS C:\Dev\test> ..\vcpkg\vcpkg.exe add artifact arm:gcc
warning: vcpkg-artifacts are experimental and may change at any …
```

Treat * as 'no filter' when searching a registry for versions.

---

cmake/Findfmt.cmake

`VCPKG_FMT_URL` must not be cached because it the cached value breaks contributors when `fmt` and its SHA512 sum is updated.

Unbreak fmt upgrades

---

include/vcpkg/base/chrono.h
src/vcpkg/base/chrono.cpp

As requested by https://github.com/microsoft/vcpkg-tool/pull/723#discussion_r1010268400

Don't store a nontrivial type in std::atomic.

---

include/vcpkg/export.prefab.h

Similar to `system_headers.h`, but in the header which actually uses `major` and `minor`.

Fix macro warnings

---

include/vcpkg/base/files.h
src/vcpkg-test/binarycaching.cpp
src/vcpkg-test/dependencies.cpp
src/vcpkg-test/files.cpp
src/vcpkg/archives.cpp
src/vcpkg/base/cofffilereader.cpp
src/vcpkg/base/downloads.cpp
src/vcpkg/base/files.cpp
src/vcpkg/base/json.cpp
src/vcpkg/base/unicode.cpp
src/vcpkg/build.cpp
src/vcpkg/cmakevars.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.fetch.cpp
src/vcpkg/commands.find.cpp
src/vcpkg/commands.format-manifest.cpp
src/vcpkg/commands.regenerate.cpp
src/vcpkg/export.prefab.cpp
src/vcpkg/install.cpp
src/vcpkg/packagespec.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/sourceparagraph.cpp
src/vcpkg/vcpkglib.cpp
src/vcpkg/vcpkgpaths.cpp

In these places, emplace_back seems to be more efficient than push_back, and the better choice.
We can also improve performance further by reserving the size we know the vector will be so we do not have to waste time resizing.

Make pushing back to vectors more efficient

---

ce/ce/cli/commands/acquire.ts
ce/ce/cli/commands/add.ts
ce/ce/cli/commands/use.ts

Before:
```
PS C:\Dev\test> type .\vcpkg-configuration.json
{
"default-registry": {
"kind": "git",
"baseline": "e2667a41fc2fc578474e9521d7eb90b769569c83",
"repository": "https://github.com/microsoft/vcpkg"
},
"registries": [
{
"kind": "artifact",
"location": "https://aka.ms/vcpkg-ce-default",
"name": "microsoft"
}
],
"requires": {
}
}
PS C:\Dev\test> C:\Dev\vcpkg\vcpkg.exe add artifact microsoft:pico-sdk
warning: vcpkg-artifacts are experimental and may change at any time.
Artifact                        Version    Status        Dependency  Summary
microsoft:compilers/arm/gcc     2020.10.0  installed                 GCC compiler for ARM CPUs.
microsoft:tools/kitware/cmake   3.20.1     installed                 Kitware's cmake tool
microsoft:raspberrypi/pico-sdk  1.3.0      will install …
```

Fix "add" adding transitive dependencies with "undefined" versions.

---

azure-pipelines/end-to-end-tests-prelude.ps1
azure-pipelines/end-to-end-tests.ps1

Currently it is really hard to read the output because it is only a wall of text. 
Another improvement would be to not print the output of vcpkg twice.

e2e tests: Color output

---

include/vcpkg/tools.h
src/vcpkg/archives.cpp
src/vcpkg/tools.cpp

A user provided CMake can be used to extract vcpkg's copy of CMake during the `downloads/tools` bootstrap process.
The current fallbacks are:
* System32/tar
* User CMake
* 7zip MSI

Use system CMake to unpack if available during 7z bootstrap

---

src/vcpkg/base/system.process.cpp

This were broken in #397
cc @BillyONeal

Use unique identifier to match return codes in the output

---

src/vcpkg/build.cpp
src/vcpkg/cmakevars.cpp
src/vcpkg/vcpkgpaths.cpp

We can pass each part directly instead of creating tuples or objects directly

No need to make tuples or objects in emplace-back

---

include/vcpkg/base/fwd/system.process.h
include/vcpkg/build.h
include/vcpkg/fwd/binaryparagraph.h
include/vcpkg/fwd/build.h
include/vcpkg/fwd/packagespec.h
include/vcpkg/fwd/triplet.h
include/vcpkg/fwd/vcpkgpaths.h
include/vcpkg/installedpaths.h
include/vcpkg/packagespec.h
include/vcpkg/triplet.h
include/vcpkg/vcpkgpaths.h
src/vcpkg/export.prefab.cpp
src/vcpkg/help.cpp
src/vcpkg/vcpkgpaths.cpp

Also:
* Delete the `details::` namespace here which saves us a whole indent for this file.
* Reorder several functions marked static to be within the unnamed namespace, and drop static.
* Avoid forward declaring entities that VcpkgPaths does not own.
No function bodies are edited.

Reorder VcpkgPaths cpp to match the h.

---

ce/ce/archivers/tar.ts
ce/custom/tar-stream/package.json

I'm not sure about the exact cause of this failure but I suspect it's a change from node version since that's the only thing we've changed:
```
1) TarBzUnpacker
UnpacksLegitimateSmallTarBz:
Error: Premature close
at new NodeError (node:internal/errors:393:5)
at Stream.<anonymous> (node:internal/streams/pipeline:352:14)
at Stream.emit (node:events:525:35)
at Stream.stream.destroy (C:\Dev\vcpkg-tool\ce\common\temp\node_modules\.pnpm\through@2.3.8\node_modules\through\index.js:84:12)
at _end (C:\Dev\vcpkg-tool\ce\common\temp\node_modules\.pnpm\through@2.3.8\node_modules\through\index.js:67:14)
at Stream.stream.end (C:\Dev\vcpkg-tool\ce\common\temp\node_modules\.pnpm\through@2.3.8\node_modules\through\index.js:74:5)
at ProgressTrackingStream.onend (node:internal/streams/readable:705:10)
at …
```

Fix build breaks discovered on Node 18.x

---

include/vcpkg/portfileprovider.h
include/vcpkg/vcpkgpaths.h
src/vcpkg/build.cpp
src/vcpkg/commands.buildexternal.cpp
src/vcpkg/commands.check-support.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.dependinfo.cpp
src/vcpkg/commands.edit.cpp
src/vcpkg/commands.env.cpp
src/vcpkg/commands.find.cpp
src/vcpkg/commands.info.cpp
src/vcpkg/commands.setinstalled.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/export.cpp
src/vcpkg/install.cpp
src/vcpkg/portfileprovider.cpp
src/vcpkg/remove.cpp
src/vcpkg/update.cpp
src/vcpkg/vcpkgpaths.cpp

This removes a ton of false dependencies from portfileprovider et al. (portfile provider needs git infrastructure?!), and avoids actually trying to parse and resolve registries in commands that don't actually care.

Delete VcpkgPaths from portfileprovider machinery.

---

src/vcpkg/base/checks.cpp
src/vcpkg/base/cofffilereader.cpp

Fixes https://github.com/microsoft/vcpkg-tool/pull/710/files#r1051638592

Print proper error messages if there is an error.

---

src/vcpkg/base/system.process.cpp

Before this PR, using `set VCPKG_KEEP_ENV_VARS=PATH` would result in two copies of `PATH` in the environment block. This had (mostly) the correct results for windows processes which would take the first value, however msys2's bash takes the last value and thus has an incredibly mysterious behavior of apparently resetting the path.
This is a targeted fix for the PATH variable, however a more comprehensive rework of how the environment is handled is needed to ensure correct handling of all variables -- see https://github.com/microsoft/vcpkg-tool/pull/424.

Correct handling of PATH in VCPKG_KEEP_ENV_VARS

---

include/vcpkg/commands.bootstrap-standalone.h
src/vcpkg/commands.bootstrap-standalone.cpp
src/vcpkg/commands.cpp
vcpkg-init/vcpkg-init
vcpkg-init/vcpkg-init.ps1

We're planning to start using this flag from a VS Code extension in January, so it probably shouldn't have the `z-` prefix any more.
cc @microsoft/embedded-dev

Remove z- prefix from bootstrap-standalone command

---

src/vcpkg/base/stringview.cpp

This gives a 3.3x performance improvement: https://quick-bench.com/q/RXyLBXqCsm-QHSHGxBDSou6N_Fs
Also gets rid of `/home/vsts/work/1/s/src/vcpkg/base/stringview.cpp:32:50: runtime error: null pointer passed as argument 2, which is declared to never be null`
Code used for benchmarking:
```c++
#include <cstring>
struct SV {
const char* data = nullptr;
std::size_t size = 0;
bool operator==(const SV& other) const noexcept
{
return size == other.size && memcmp(data, other.data, size) == 0;
}
};
struct SV_2 {
const char* data = nullptr;
std::size_t size = 0;
bool operator==(const SV_2& other) const noexcept
{
if (size == 0 && other.size == 0) return true;
return size == other.size && memcmp(data, other.data, size) == 0;
}
};
static void StringCreation(benchmark::State& state) {
for (auto _ : …
```

Avoid calling memcmp for empty string views

---

src/vcpkg/base/system.process.cpp

Fixes build failure on FreeBSD 13.1-RELEASE as described by microsoft/vcpkg#28535.
Basically declares the missing `environ` variable the same way it is done on OS X, and the call to an invalid Path constructor in FreeBSD-specific code.

Fix build on FreeBSD 13.1-RELEASE

---

azure-pipelines/signing.yml
ce/assets/package.json
ce/ce/artifacts/activation.ts
ce/ce/fs/filesystem.ts
ce/ce/package.json
ce/ce/util/channels.ts
ce/common/config/rush/pnpm-lock.yaml

Fixes signed builds. The previous prepare-deploy was attempting to remove what it thought was a phantom dependency on the typescript compiler from the deployed output. This failed because the DevDiv build lab pushed out changes that blocked the unrestrained dependency on rimraf used by that script. This change drops the dependency on ee-ts which created the need to include the typescript compiler in the first place.
Also fixed test failures that ee-ts was apparently hiding?!

Remove the ee-ts dependency.

---

azure-pipelines/e2e_projects/applocal-test/build/build.bat
azure-pipelines/e2e_projects/applocal-test/plugins/azure_kinect_sensor_sdk/build.bat
azure-pipelines/end-to-end-tests-dir/z-applocalcpp.ps1

In https://github.com/microsoft/vcpkg-tool/pull/864#issuecomment-1404436205 I noted that these tests fail on my machine before making any changes; I'm not sure why, but when I try to run with cmd manually (outside of vcpkg env) I get the same "the filename, directory name, or volume label syntax is incorrect" error that vcpkg env gives.
This change just makes the batch files know the right path to use themselves rather than needing it passed in by the caller, so we don't need to deal with so many levels of confusing escaping.

Avoid needing to triple escape paths in z-applocal tests.

---

azure-pipelines/pipelines.yml
azure-pipelines/signing.yml

All but 1 generated alert was in meson:

Run CodeQL on the build, not on test collateral.

---

src/vcpkg-test/files.cpp
src/vcpkg/base/files.cpp

If you cannot read a dir, you cannot deal with its entries (without knowing them in advance). 
To fix CI errors after failed bazel build in previous run. Example from [x64-linux raw log](https://dev.azure.com/vcpkg/public/_build/results?buildId=84154&view=logs&j=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad):
~~~
2023-01-25T08:40:22.5334048Z ##[section]Starting: *** Test Modified Ports
2023-01-25T08:40:22.5340577Z ==============================================================================
2023-01-25T08:40:22.5340937Z Task         : PowerShell
2023-01-25T08:40:22.5341095Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2023-01-25T08:40:22.5341325Z Version      : 2.212.0
2023-01-25T08:40:22.5341482Z Author       : Microsoft Corporation
2023-01-25T08:40:22.5341634Z Help …

Fix removal of unreadable directories

---

src/vcpkg-test/plan.cpp
src/vcpkg/dependencies.cpp

Currently the command simply fails to execute.

vcpkg upgrade: Handle the removal of features in new port versions

---

src/vcpkg/base/system.process.cpp

Currently all handles are inherited to child processes. For more information see https://discord.com/channels/400588936151433218/687365466422902841/1072485165491814430

Only inherit the handles that are really needed.

---

src/vcpkg/commands.integrate.cpp

Resolves https://github.com/microsoft/vcpkg/issues/27832

Defend against missing directories in `vcpkg integrate install`.

---

include/vcpkg/base/messages.h
include/vcpkg/base/system.process.h
include/vcpkg/binaryparagraph.h
include/vcpkg/build.h
include/vcpkg/paragraphparser.h
include/vcpkg/sourceparagraph.h
locales/messages.json
src/vcpkg-test/paragraph.cpp
src/vcpkg/base/messages.cpp
src/vcpkg/base/system.process.cpp
src/vcpkg/binaryparagraph.cpp
src/vcpkg/build.cpp
src/vcpkg/commands.integrate.cpp
src/vcpkg/commands.portsdiff.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/sourceparagraph.cpp
src/vcpkg/statusparagraph.cpp
src/vcpkg/tools.cpp

and replace static const std::strings with StringLiterals.
Saves about 5kb of executable size and several dynamic initializers.

Delete vestigial alias port parts

---

include/vcpkg/base/messages.h
include/vcpkg/base/system.h
src/vcpkg.cpp
src/vcpkg/base/system.cpp
src/vcpkg/triplet.cpp

This PR allows building vcpkg on RISC-V machines. Tested with Ubuntu 22.04.1 LTS (GNU/Linux 5.19.0-1012-generic riscv64) and SiFive U74-MC.

Add initial risc-v support

---

include/vcpkg/dependencies.h
locales/messages.json
src/vcpkg/commands.dependinfo.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/install.cpp

Currently `vcpkg install gtk[introspection] --allow-unsupported` yields:
```
warning: gobject-introspection is only supported on '!static & (native | (windows & x86))', which does not match arm64-osx. This usually means that there are known build failures, or runtime problems, when building other platforms. Proceeding anyway due to `--allow-unsupported`.
warning: gobject-introspection is only supported on '!static & (native | (windows & x86))', which does not match arm64-osx. This usually means that there are known build failures, or runtime problems, when building other platforms. Proceeding anyway due to `--allow-unsupported`.
warning: gobject-introspection is only supported on '!static & (native | (windows & x86))', which does not match arm64-osx. This usually means that there are …
```

Print unsupported warnings only once

---

azure-pipelines/end-to-end-tests-dir/ci.ps1
src/vcpkg/commands.ci.cpp

Between https://github.com/microsoft/vcpkg-tool/pull/856 and https://github.com/microsoft/vcpkg-tool/pull/899

Fix stealth merge conflict

---

include/vcpkg/base/cofffilereader.h
src/vcpkg/base/cofffilereader.cpp

This fixes a regression I introduced in https://github.com/microsoft/vcpkg-tool/pull/834 . (Specifically, this was always broken but now we are exposing ICU's x64-windows binaries to this code)
try_read_image_config_directory checked for a LOAD_CONFIG data directory, but didn't check that it was non-nullptr, like the import and export checks did. Extract a common function to make it easier to verify that we always do this.
```
C:\Dev>dumpbin /imports "C:\Dev\vcpkg\packages\icu_x64-windows\bin\icudt72.dll" Microsoft (R) COFF/PE Dumper Version 14.34.31942.0 Copyright (C) Microsoft Corporation.  All rights reserved.
Dump of file C:\Dev\vcpkg\packages\icu_x64-windows\bin\icudt72.dll
File Type: DLL
Summary
1DCE000 .rdata
1000 .rsrc
C:\Dev>
```

Fix ICU post build checks.

---

azure-pipelines/e2e_projects/overlays-project-config-embedded/vcpkg.json
azure-pipelines/e2e_projects/overlays-project-with-config/vcpkg.json
azure-pipelines/end-to-end-tests-dir/binarycaching.ps1
azure-pipelines/end-to-end-tests-dir/build-missing.ps1
azure-pipelines/end-to-end-tests-dir/bundles.ps1
azure-pipelines/end-to-end-tests-dir/cli.ps1
azure-pipelines/end-to-end-tests-dir/registries.ps1
azure-pipelines/pipelines.yml
azure-pipelines/signing.yml

Fixes macos failures caused by Azure Pipelines removing pkgconfig by default, and hopefully speeds some bits up a bit by building less.

Make e2e tests depend on fewer external resources.

---

azure-pipelines/end-to-end-tests-dir/bundles.ps1
include/vcpkg/base/messages.h
include/vcpkg/base/system.h
include/vcpkg/bundlesettings.h
include/vcpkg/vcpkgpaths.h
locales/messages.json
src/vcpkg-test/bundlesettings.cpp
src/vcpkg.cpp
src/vcpkg/base/messages.cpp
src/vcpkg/base/system.cpp
src/vcpkg/bundlesettings.cpp
src/vcpkg/commands.edit.cpp
src/vcpkg/vcpkgpaths.cpp
vcpkg-init/mint-standalone-bundle.ps1

When deployed with Visual Studio, we should listen to the privacy setting like the rest of Visual Studio:
This required moving the bundleconfig to "next to the .exe" rather than "within vcpkg_root", and corresponding test changes, since we need to know information out of the bundle before we know where VCPKG_ROOT is (and maybe for commands that don't need VCPKG_ROOT in the first place).
This also changes `--no-disablemetrics` to force enable metrics if the user does that for some reason, even if there's a file named vcpkg.disable-metrics.
Drive bys:
* test_registry_key and get_registry_string where leaktrocities.
* get_registry_string was racy.
* get_registry_string accepted REG_MULTI_SZ despite that not actually being a string type. (It's `vector<string>`)
Example output when enabled: …

Disable metrics when the user is not opted in to Visual Studio telemetry when deployed w/VS.

---

docs/vcpkg_catalog_release_process.md
docs/vcpkg_tool_release_process.md

https://github.com/microsoft/vcpkg/pull/28350 deleted these files without replacement on "learn" because they are internal-to-the-vcpkg-team docs, so they really belong here in the tool repo anyway.

Resurrect release process documentation.

---

include/vcpkg/base/system.h
src/vcpkg/base/system.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/configure-environment.cpp
src/vcpkg/vcpkgpaths.cpp

which allows artifacts to work when VCPKG_ROOT is read only.
Example with official build:
```
PS C:\Dev\vcpkg-tool\out\build\x64-Debug-Official-2022-11-10> .\vcpkg.exe find artifact gcc --debug
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\Dev\vcpkg-tool\out\build\x64-Debug-Official-2022-11-10\vcpkg-bundle.json
[DEBUG] Failed to open: C:\Dev\vcpkg-tool\out\build\x64-Debug-Official-2022-11-10\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset …
```

Don't extract vcpkg-artifacts under VCPKG_ROOT

---

ce/ce/cli/command-line.ts
ce/ce/constants.ts
ce/ce/session.ts
include/vcpkg/vcpkgpaths.h
src/vcpkg/configure-environment.cpp
src/vcpkg/vcpkgpaths.cpp

Smoke test demonstration. Note: debug: [00:00.08] Loaded global configuration file 'c:\Users\bion\.vcpkg\vcpkg-configuration.json'
```
PS C:\Dev\vcpkg-tool> get-command cmake
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     cmake.exe                                          3.25.2.0   C:\Program Files\CMake\bin\cmake.exe
PS C:\Dev\vcpkg-tool> .\out\build\x64-Debug\vcpkg.ps1 use cmake --debug
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\Dev\vcpkg-tool\out\build\x64-Debug\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, …
```

Don't put global vcpkg-configuration.json in VCPKG_ROOT if readonly

---

azure-pipelines/signing.yml
src/vcpkg/configure-environment.cpp
vcpkg-init/lock-versions.ps1
vcpkg-init/mint-standalone-bundle.ps1
vcpkg-init/vcpkg-cmd.cmd
vcpkg-init/vcpkg-init
vcpkg-init/vcpkg-init.ps1

* Use `mktemp` for the temp path on *nix
* Use `Path::GetTempPath()` and `%TEMP%` to set the postscript rather than something under `VCPKG_ROOT`.
* Fix `#endif` typo from https://github.com/microsoft/vcpkg-tool/pull/938
* Change version locking to a file in the "standalone bundle" rather than one the bootstrap script creates so that we don't need to write when we aren't bootstrapping and the Visual Studio installer creates it for us.
* Separate out the `.cmd` that does the postscript dance from the installer `.cmd`. This allows the "installer" `.cmd` to print no output when no args are supplied. (Otherwise we can't distinguish here between 'invoked by doskey, print what vcpkg.exe with no arguments does' and 'invoked by user to install into the shell')
* Delete `--remove-vcpkg`. It doesn't …

Fix bootstrap wrapper scripts to tolerate deployment within readonly VCPKG_ROOT.

---

src/vcpkg/base/downloads.cpp
src/vcpkg/base/hash.cpp
src/vcpkg/configure-environment.cpp
vcpkg-init/vcpkg-init.ps1

Should fix https://github.com/microsoft/vcpkg/issues/26172
Helps debug https://github.com/microsoft/vcpkg/issues/30051

Add additional logging and defenses to artifacts use.

---

src/vcpkg-test/chrono.cpp
src/vcpkg/base/chrono.cpp

Fixes https://github.com/microsoft/vcpkg-tool/pull/909#issuecomment-1471964306
Before:
```
Detecting compiler hash for triplet arm64-osx...
The following packages will be rebuilt:
boost-uninstall[core]:arm64-osx -> 1.81.0#2
Removing 1/2 boost-uninstall:arm64-osx
Elapsed time to handle boost-uninstall:arm64-osx: 1.88325 ms
Restored 0 package(s) from /Users/leanderSchulten/.cache/vcpkg/archives in 682.708 us. Use --debug to see more details.
Attempting to fetch 1 package(s) from HTTP servers
Restored 0 package(s) from HTTP servers in 210.244292 ms. Use --debug to see more details.
Installing 2/2 boost-uninstall:arm64-osx...
Building boost-uninstall[core]:arm64-osx...
warning: -- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] …
```

Fix the formatting of duration

---

src/vcpkg/build.cpp

For example [here](https://github.com/microsoft/vcpkg/issues/30190) the generated log excerpts was to short and did not contain the error. Therefore we should generate longer log excerpts. The generated issue is still short enough (there are at most 4 logs(err.log, out.log, cmake cache (dbg+rel, but very short))) 50'000 each <  [262,144 max length](https://github.com/orgs/community/discussions/27190#discussioncomment-3254953)

Github issue template: Loger logs excerpts

---

CMakeLists.txt

Otherwise you get a lot of warnings like
```
clang: warning: precompiled header '/Users/leanderSchulten/git_projekte/build-vcpkg-tool-No_QT-Debug/CMakeFiles/vcpkglib.dir/cmake_pch_arm64.hxx.pch' was ignored because '-include /Users/leanderSchulten/git_projekte/build-vcpkg-tool-No_QT-Debug/CMakeFiles/vcpkglib.dir/cmake_pch_arm64.hxx' is not first '-include'
```

Fix precompiled headers on unix

---

NOTICE.txt
azure-pipelines/signing.yml
cgmanifest.json
vcpkg-init/mint-standalone-bundle.ps1

Also removes the dynamically generated NOTICE.txt in favor of a checked in copy, which removes a very flaky external service from our signed builds.
Examples of the latter failing builds:
* https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7231484&view=results
* https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7343418&view=results
* https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7461428&view=results
Also adds CMakeRC that was missing.
Resolves https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1635356

Update vcpkg's Third Party Notices file to include artifacts parts.

---

include/vcpkg/base/messages.h
src/vcpkg/build.cpp
src/vcpkg/commands.dependinfo.cpp
src/vcpkg/dependencies.cpp

In https://github.com/microsoft/vcpkg-tool/pull/936/ , I accidentially forgot the return.
Additional related fixes:
* add [[nodiscard]] to the formatters; note that nodiscard was already in use in strings.h: https://github.com/microsoft/vcpkg-tool/blob/65fcbac58785083569ce63ad4a9255044bf6c35b/include/vcpkg/base/strings.h#L66
* fix a couple of places that were printing a debug message just before "Checks::unreachable" to include that in the Checks::unreachable output instead of a separate debug statement.
Thanks to @Neumann-A for pointing out this bug over Discord and @autoantwort for pointing out which line was messed up after I localized it to #936 .

Fix VersionConstraintUnresolvable message being dropped.

---

src/vcpkg/commands.integrate.cpp

* Move the "tmp" directory to the normal place we do temp things.
* Fix not clearing the tmp directory after use. Fixes https://github.com/microsoft/vcpkg/issues/10537 .
* For MSBuild 14, only use a tmp directory at all if we need to do the file copy from an elevated prompt instead of always using a temp directory.
* For MSBuild != 14, just write the files into the correct place rather than writing to a temp place then copying over.
* For MSBuild all, reuse that on Windows `user_configuration_home` is already `%LOCALAPPDATA\vcpkg` instead of deriving that path all over the place.
* `StringLiteral`-ize create_nuget_props_file_contents since it was a constant.
* Remove noexcept from functions that allocate and return `std::string`s.
* In integrate project, put the resulting nupkg in CWD …

integrate install/project: Don't write to VCPKG_ROOT.

---

src/vcpkg/postbuildlint.cpp

This code crashes due to the unescaped curly braces--this fixes it

fix crash in postbuiltlint

---

azure-pipelines/signing.yml

After a recent key leak GitHub has rotated its RSA key, so the fingerprint has changed as well. We shouldn't be advertising the revoked one's as acceptable.
- New keys: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints.
- Related article: https://www.bleepingcomputer.com/news/security/githubcom-rotates-its-exposed-private-ssh-key/

Update GitHub's RSA fingerprint after the key leak

---

CMakeSettings.json
src/vcpkg/base/cmd-parser.cpp
src/vcpkg/vcpkgcmdarguments.cpp

This was discovered in smoke testing of the artifacts feature. Artifacts was unable to download anything because it passes `--z-machine-readable-progress` which failed with:
```
PS C:\Dev\vcpkg-tool> C:\Users\bion\.vcpkg\vcpkg.exe x-download c:\Users\bion\.vcpkg\downloads\vcpkg.ce.default-registry.zip --z-machine-readable-progress --skip-sha512 --url=https://aka.ms/vcpkg-ce-default
error: unexpected switch: --z-machine-readable-progress
example:
vcpkg x-download <filepath> [--sha512=]<sha512> [--url=https://...]...
example:
vcpkg x-download <filepath> --skip-sha512 [--url=https://...]...Options:
--x-asset-sources=...           Add sources for asset caching. See 'vcpkg help assetcaching'.
--binarysource=...              Add sources for binary caching. See 'vcpkg help binarycaching'. …
```

Fix handling of z- switches.

---

src/vcpkg-test/strings.cpp

Add `numeric` include for `std::iota`. This currently makes the following pipeline fail on Windows (Azure):
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=681447&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802

Add <numeric> to strings.cpp for std::iota

---

azure-pipelines/pipelines.yml

GCOV is causing a lot of builds to fail randomly and succeed on retry. This PR removes it.
e.g. https://dev.azure.com/vcpkg/public/_build/results?buildId=87614&view=logs&j=d6955a24-b4a1-58cd-bf05-f0addec06f6d&t=234a88e1-e3e9-55cf-a2d8-fa41708c6fae

Remove gcov due to flakiness

---

CMakeSettings.json
azure-pipelines/pipelines.yml
azure-pipelines/signing.yml
azure-pipelines/vs-insertion/vcpkg.nuspec

When we first set vcpkg's executable architecture to x86, we chose that option because it was the only way we could build that would run on all Windows.
Since then, arm64 has gained the ability to run amd64 programs, and arm has lost relevancy. Platforms like nanoserver without a wow64 subsystem are also increasing in importance. And we don't really expect x86 hosted dev boxes to be a thing in 2023.
See also: https://github.com/microsoft/vcpkg-tool/pull/972 (no plans to change official compiler to clang-cl though)
Resolves https://github.com/microsoft/vcpkg/issues/25521

Change official releases to amd64.

---

include/vcpkg/base/expected.h

I've observed that intellisense in VS2022 previews can't see through calls to `ExpectedT::then`. Switching to `typename invoke_result<>::type` fixes this.

Avoid invoke_result_t to fix VS2022 intellisense

---

include/vcpkg/base/strings.h
include/vcpkg/binaryparagraph.h
src/vcpkg-test/strings.cpp
src/vcpkg/base/json.cpp
src/vcpkg/base/strings.cpp
src/vcpkg/binaryparagraph.cpp
src/vcpkg/build.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.integrate.cpp
src/vcpkg/commands.xdownload.cpp
src/vcpkg/export.chocolatey.cpp
src/vcpkg/export.prefab.cpp
src/vcpkg/input.cpp
src/vcpkg/sourceparagraph.cpp
src/vcpkg/triplet.cpp
src/vcpkg/vcpkglib.cpp
src/vcpkg/vcpkgpaths.cpp

- Remove unneeded specialization of append_internal
- Instead of recursive templates, use pack expansion
- Remove unused Strings::escape_string
- Remove no-op transformer in Strings::join
- Don't require pointer parameter to trim_all_and_remove_whitespace_strings -- rename as "inplace" for consistency
- Fuse some loops

Assorted small improvements.

---

CMakeLists.txt

The vcpkglib target generates a precompiled header, which later during the build process is consumed by the vcpkg-target target.
However, vcpkglib is compiled with threading support, while vcpkg-test is not, causing the PCH being rejected.
Enforce multithreadened target mode to all vcpkglib consumers by marking its' Threads::Threads dependency public
Fixes: microsoft/vcpkg#30863

Expose vcpkglib's Threads dependency

---

include/vcpkg/base/messages.h
include/vcpkg/dependencies.h
include/vcpkg/packagespec.h
include/vcpkg/statusparagraph.h
src/vcpkg-test/binarycaching.cpp
src/vcpkg-test/dependencies.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/export.cpp
src/vcpkg/packagespec.cpp
src/vcpkg/remove.cpp
src/vcpkg/statusparagraph.cpp

This PR is a reduced set of changes from https://github.com/microsoft/vcpkg-tool/pull/1022.
- Simplify `to_output_string()` implementations
- Extract `PackageAction`, which can be shared between `AlreadyInstalledAction` (future) and `InstallPlanAction`
- Extract `BasicAction`, which is shared amongst all action types. This alllows deduplication of `XYZAction::compare_by_name`.
- Remove default constructors from some action types (w/tweaking tests)

Extract BasicAction/PackageAction in preparation for splitting action types

---

azure-pipelines/end-to-end-tests-dir/overlays.ps1
src/vcpkg/commands.update-baseline.cpp
src/vcpkg/vcpkgpaths.cpp

This PR fixes a bug where the command `x-update-baseline` makes overlay-triplet paths absolute in vcpkg-configuration.json.

x-update-baseline should not make overlay-triplet paths absolute

---

src/vcpkg/commands.integrate.cpp

When running for the first time (file _C:\Program Files (x86)\MSBuild\\...\vcpkg.system.props_ doesn't exist), the `integrate install` command must be executed twice.
```
> .\vcpkg.exe integrate install
failed to install system targets file to C:\Program Files (x86)\MSBuild/Microsoft.Cpp/v4.0/V140/ImportBefore/Default/vcpkg.system.props
> .\vcpkg.exe integrate install
Applied user-wide integration for this vcpkg root.
...
```
Yet _vcpkg.system.props_ was correctly installed on the first try. The error message is incorrect. This appears to be a regression caused by #937. The final exit check in  `integrate_install_msbuild14()` should be conditional.

'integrate install' needs to be run twice.

---

src/vcpkg/commands.integrate.cpp

Change the order of operations in `integrate install`.
Currently, MSBuild14 is configured first. This can be a problem because MSBuild14 files are deployed under _C:\Program Files (x86)\MSBuild_. In many environments, this folder is not user-writable. In essence, this means that `integrate install` must be run with elevated privileges, otherwise the command is aborted almost immediately.
On the other hand, vcpkg integration for subsequent versions (MSBuild15+) only need access to `%LOCALAPPDATA%`, which is user-writable and likely to succeed.
With this change, `integrate install` still exits with an error for non-admin user, but at least results in a working integration for anyone targeting VS2017 and later.
Another approach would be to simply log failures in `integrate_install_msbuild14` …

Improve integrate install for non-admin users.

---

.github/workflows/build.yaml
.gitignore
azure-pipelines/signing.yml

* .gitignore temporary files created in OneLocBuild, example warnings: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7591437
* Update SDL tools versions.
* Bump the timeout so that CI has time to complete. (Example timeout run: https://github.com/microsoft/vcpkg-tool/actions/runs/4875682141/jobs/8698197334 )

Infrastructure Updates

---

src/vcpkg-test/util.cpp

Fix vcpkg issue: https://github.com/microsoft/vcpkg/issues/31454, add `include <numeric>` to `util.cpp` for `std::iota`.
```
vcpkg-test/util.cpp(278): error C2039: 'iota': is not a member of 'std'
vcpkg-test/util.cpp(278): error C3861: 'iota': identifier not found
```

Add <numeric> to util.cpp for std::iota

---

src/vcpkg/configuration.cpp

Aggregates can no longer have user-declared constructors in C++20, but this type relies on aggregate initialization.

Keep LocationAndRegistry an aggregate in c++20

---

azure-pipelines/end-to-end-tests-dir/format-manifest.ps1

Resolves output like
```
2023-05-18T00:52:19.4251966Z warning: in the working copy of '3fd/vcpkg.json', LF will be replaced by CRLF the next time Git touches it
2023-05-18T00:52:19.4372050Z warning: in the working copy of '7zip/vcpkg.json', LF will be replaced by CRLF the next time Git touches it
2023-05-18T00:52:19.4386085Z warning: in the working copy of 'ableton-link/vcpkg.json', LF will be replaced by CRLF the next time Git touches it
2023-05-18T00:52:19.4398373Z warning: in the working copy of 'ableton/vcpkg.json', LF will be replaced by CRLF the next time Git touches it
2023-05-18T00:52:19.4410932Z warning: in the working copy of 'abseil/vcpkg.json', LF will be replaced by CRLF the next time Git touches it
2023-05-18T00:52:19.4422736Z warning: in the working copy of …
```

Turn off autocrlf in format-manifest test.

---

include/vcpkg/commands.install.h
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/commands.remove.cpp
src/vcpkg/commands.set-installed.cpp
src/vcpkg/postbuildlint.cpp

@autoantwort reports in https://github.com/microsoft/vcpkg-tool/pull/1057/files#r1210842149 that we fail to account for upgraded packages in the new binary caching strategy because we blow away the extracted bits on the remove package action.
```
PS C:\Dev\vcpkg> .\vcpkg x-set-installed 'sqlite3' && .\vcpkg x-set-installed 'sqlite3[dbstat]'
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
The following packages will be removed:
boost-array:x64-windows
boost-assert:x64-windows
boost-bind:x64-windows …
```

Fix binary caching for 'upgrade'd packages

---

CMakePresets.json

There is a typo in macos-ci preset. the hostOs should be one of `macOS`, `Windows`, `Linux`. But the original CMakePresets.json turns out to be `MacOS`, which should be `macOS`. This fixes CMakePresets.json validation.
On vscode a error message turns out:
```
[presetController] Unsupported presets detected in ***/vcpkg-tool/CMakePresets.json. Support is limited to features defined by version 4.
[presetController]  >> /configurePresets/16/vendor/microsoft.com~1VisualStudioSettings~1CMake~11.0/hostOS: should be equal to one of the allowed values
[presetController]  >> /configurePresets/16/vendor/microsoft.com~1VisualStudioSettings~1CMake~11.0/hostOS: should be array
[presetController]  >> /configurePresets/16/vendor/microsoft.com~1VisualStudioSettings~1CMake~11.0/hostOS: should match some …
```

Fix typo in CMakePresets.json

---

azure-pipelines/nuget-package.signproj
azure-pipelines/signing.yml

Resolves https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1833480

Add VS Insertion NuGet Package Signing

---

docs/vcpkg_tool_release_process.md

Delete note about running the artifacts tests before shipping a tool now that GitHub Actions runs that on every PR.

Delete artifacts note from ship checklist

---

src/vcpkg/base/files.cpp
src/vcpkg/commands.install.cpp

Current situation: 
If a package gets installed, all files are copied from the packages folder to the installed dir. 
Current problem: 
Duplicating files consumes a lot of unnecessary disk space. It also results in unnecessary read and write operations on the hard disk.
Solution:
Instead of copying the file, create a hard link. If a hard link is not possible (for example if the two folders are on different disks), copy the file. 
Concerns:
If a file on windows is opened without the `FILE_SHARE_DELETE` flag, a file is an executable that is executed or a loaded dll, the file can not be deleted even it would only reduce the hard link count by 1 without deleting the file finally. If this would be the case for a file in the installed dir vcpkg could not delete the packages folder and build new …

Installation from packages to installed: Hard link files instead of copy

---

include/vcpkg/base/system.process.h
src/vcpkg-test/cgroup-parser.cpp
src/vcpkg/base/system.process.cpp

This is psychic debugging as to why we occasionally have OOM recently. Example: https://github.com/microsoft/vcpkg/pull/31770/checks?check_run_id=14302512642

Telemetry: defend against parent process loops

---

include/vcpkg/sourceparagraph.h
src/vcpkg-test/manifests.cpp
src/vcpkg/sourceparagraph.cpp

Fixes 2. of https://github.com/microsoft/vcpkg/issues/31820#issuecomment-1582173121

Allow license expressions in features

---

CMakeLists.txt

spawn.h is only available on Android P and later (API level 28).
While Termux is on API level 24.

[vcpkg-tool] Fix undefined symbol `posix_spawn` for Termux build.

---

src/vcpkg/postbuildlint.cpp

Fixes vcpkg issue https://github.com/microsoft/vcpkg/issues/32261, update the hint of installing license.

Update license install hint

---

CMakeLists.txt

Hi, sorry to bother again. This is just a minor issue, but
`if(ANDROID)` is equal to `if(CMAKE_SYSTEM_NAME STREQUAL "Android")`
https://cmake.org/cmake/help/v3.26/variable/ANDROID.html
and `CMAKE_SYSTEM_NAME STREQUAL "Linux"` is unnecessary.

Simplify CMake Android detection.

---

include/vcpkg/base/expected.h
include/vcpkg/base/message-data.inc.h
locales/messages.json
src/vcpkg/tools.cpp

Fixes https://github.com/microsoft/vcpkg/issues/31292 and https://github.com/microsoft/vcpkg/issues/26377

ToolCache: Better explain errors.

---

include/vcpkg/vcpkgpaths.h
src/vcpkg/base/system.process.cpp
src/vcpkg/registries.cpp
src/vcpkg/vcpkgpaths.cpp

Helps work on https://github.com/microsoft/vcpkg/issues/31133 : Reduces `vcpkg find port zlib` with a blank git trees cache to around 2 minutes from 4.5 minutes on my 12900HX laptop.
Implements https://stackoverflow.com/questions/72521247/how-do-i-extract-a-tree-ish-to-a-directory

Use git read-tree rather than git archive + untar to extract trees.

---

src/vcpkg/archives.cpp
src/vcpkg/base/json.cpp
src/vcpkg/base/system.process.cpp
src/vcpkg/commands.ci-verify-versions.cpp
src/vcpkg/commands.edit.cpp
src/vcpkg/commands.env.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/commands.integrate.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/versions.cpp

- Fix more cases of unneeded copies due to missing &
- Prefer move over copy
- Cosmetic change: Prove that C++17's `reference_type emplace_back()` actually works
https://en.cppreference.com/w/cpp/compiler_support/17#C.2B.2B17_library_features
Search for [P0084R2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0084r2.pdf).

Cleanup: `T&`, `std::move`, `ref_t emplace_back(...)`

---

include/vcpkg/base/downloads.h
src/vcpkg/base/downloads.cpp
src/vcpkg/commands.set-installed.cpp

We started to use the `dependencygraph` internally. It worked for some of our repositories, but for some other, it failed with no message, even when using `--debug`:
```shell
" 2>&1) # last line of the popen call
[DEBUG] 
Dependency graph submission failed.
```
To understand the issue, I tried running the command `curl` directly (in a GitHub workflow) and I got `curl: Argument list too long`, which hinted that maybe we were hitting a limit on the `command` length with `popen`. I made the modifications I suggest in this pull request, and this indeed resolve the issue:
```shell
[DEBUG] 1288: popen( curl -w "\\nfcfad8a3-bb68-4a54-ad00-dab1ff671ed2%{http_code}" -X POST -H "Accept: application/vnd.github+json" -H "Authorization: ***" -H "X-GitHub-Api-Version: 2022-11-28" …
```

[dependencygraph] Fix "command line too long" when sending to GitHub's dependency-graph API

---

src/vcpkg/vcpkgcmdarguments.cpp

Reverts https://github.com/microsoft/vcpkg-tool/pull/1131
Do not merge until we have the OK from Privacy folks.

Enable GitHub telemetry.

---

include/vcpkg/registries.h
src/vcpkg-test/registries.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/registries.cpp

This fixes a bug I discovered while implementing the `git mktree` stuff.
Commands that tried to get all port names considered the ports declaration in registries to be the literal list of ports available in that registry, even though we added wildcards that make that not true any longer.
Moreover, when we do autocomplete operations, we need to make sure we never hit the network.
Before / broken:
* Searching for 'be' can't find any ports starting with this
* autocomplete suggests package names with *s in them which clearly aren't packages
<details>
```console
PS C:\Dev\test> type .\vcpkg-configuration.json
{
"default-registry": null,
"registries": [
{
"kind": "git",
"baseline": "156b8935542c119471a8b8d702bc42146a8f0e4c",
"repository": "https://github.com/microsoft/vcpkg",
"packages": …
```

Fix search-by-name commands broken by wildcard packages feature.

---

include/vcpkg/base/cofffilereader.h
include/vcpkg/base/fwd/system.h
src/vcpkg/base/system.cpp
src/vcpkg/postbuildlint.cpp
src/vcpkg/triplet.cpp

This PR allows using vcpkg on LoongArch machines (loongarch32/64). Tested with Gentoo Linux 2.14 (loongarch64 GNU/Linux / Loongson-3A5000-HV-7A2000-1w-V0.1-EVB)
Tested ports:
```
vcpkg list
7zip:loongarch64-linux                            22.01#1             Library for archiving file with a high compressi...
bzip2:loongarch64-linux                           1.0.8#4             bzip2 is a freely available, patent free, high-q...
bzip2[tool]:loongarch64-linux                                         Builds bzip2 executable
curl:loongarch64-linux                            8.2.0               A library for transferring data with URLs
curl[non-http]:loongarch64-linux                                      Enables protocols beyond HTTP/HTTPS/HTTP2
curl[openssl]:loongarch64-linux …
```

Add loongarch64 support

---

include/vcpkg/paragraphs.h
src/vcpkg/commands.edit.cpp

rather than trying to look in the registry set for its autocomplete.
The edit command doesn't understand registries, and certainly has no reason to actually parse all the registries' ports.

Fix edit to only list builtin ports 

---

include/vcpkg/portfileprovider.h
src/vcpkg-test/dependencies.cpp
src/vcpkg/portfileprovider.cpp

Tests don't want to provide "load all" operations, so the interface they speak shouldn't have them.

Restore LSP on PortfileProvider infrastructure.

---

include/vcpkg/binaryparagraph.h
src/vcpkg-test/dependinfo-graphs.cpp
src/vcpkg/base/xmlserializer.cpp
src/vcpkg/binaryparagraph.cpp
src/vcpkg/commands.cache.cpp
src/vcpkg/commands.check-support.cpp
src/vcpkg/commands.ci-verify-versions.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.create.cpp
src/vcpkg/commands.dependinfo.cpp
src/vcpkg/paragraphs.cpp

- `BinaryParagraph(Paragraph)` --> `BinaryParagraph(Paragraph&&)`
- Add missing &
- Use `std::move`
- Initialize string instead of default-initialize + append

Cleanup: Move instead of copy and use XMLWriter for DGML

---

include/vcpkg/base/strings.h
src/vcpkg-test/files.cpp

From https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206 
> A sequence of zero or more non- <newline> characters plus a terminating <newline> character.
We should also accept the line that ends with `eof`. 
Main motivation: `fs.write_lines(path, fs.read_lines(path))` should result in the same file. Currently a new line is added.
input -> current / new lines -> current / new output:
\<empty file> -> "" / ∅ -> "\n" / \<empty file> 
"Hello\n" -> "Hello", "" / "Hello" -> "Hello\n\n" / "Hello\n"
"test\nHello" -> "test", "Hello" -> "test\nHello\n" / "test\nHello\n"

Use posix definition of a line

---

cgmanifest.json
cmake/Findfmt.cmake
include/vcpkg/base/messages.h

The fmt library has pushed a breaking change in its minor version 10.1.0.
Cause of the build error with fmt 10.1.0: https://github.com/fmtlib/fmt/commit/8f18e72df576ebfbd088a57a5c6cae8d4d0fc3dc
Even though this code was safe, the changes to improve safety broke `vcpkg::msg::format`. My Solution is to simply store all arguments in `args` in a tuple then unpack it in `fmt::make_format_args` using an index sequence.
This changes makes it compatible with fmt 10.1.0, and upgrades the library.

Update fmt to 10.1.0

---

include/vcpkg/fwd/vcpkgcmdarguments.h
include/vcpkg/vcpkgcmdarguments.h
src/vcpkg-test/arguments.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/vcpkgcmdarguments.cpp

Debug with e.g. 
`./vcpkg.exe install zlib --x-cmake-debug \\.\pipe\tespipe;zlib`
for portfile debugging
`./vcpkg.exe install zlib --x-cmake-configure-debug \\.\pipe\tespipe;zlib`
for debugging cmake configure of the port
(In Git bash `\` needs to be escaped to `\\`)
or more general
`./vcpkg.exe install zlib --x-cmake(-configure)-debug <valid_pipe_name>(;semicolon_seperated_list_of_ports_to_debug)`
for debugging cmake configure of the port
Requires external cmake debugger to attach to the opened pipe to continue execution (which is why I did not write tests for it since it would at least require two seperate process started at the right time to test this.). 
Docs PR https://github.com/microsoft/vcpkg-docs/pull/143

Introduce --x-cmake-debug and --x-cmake-configure-debug

---

vcpkg-artifacts/cli/artifacts.ts

The `acquireArtifacts` function calls stop on the ProgressRenderer when there is an error. Previously, stop was not implemented on the NoTtyProgressRenderer. This meant the progress continued to be reported after the download had failed.

Clean up NoTtyProgressRenderer timeout on error

---

vcpkg-artifacts/main.ts

Commands such as `vcpkg activate` now exit with an exit code of `1` if the command method throws an exception. Previously, the exit code was always `0`.

Return a non-zero exit code on error

---

src/vcpkg/archives.cpp

Fixes https://github.com/microsoft/vcpkg/issues/33714
In the past this was not a thing because files were copied to the installed folder, but now they are hard linked, so this restores the old behavior. 7z does not restore file modification dates: https://sourceforge.net/p/sevenzip/feature-requests/1174/

Don't restore modification times of files in zip

---

include/vcpkg/registries.h
include/vcpkg/versions.h
src/vcpkg-test/registries.cpp
src/vcpkg/commands.add-version.cpp
src/vcpkg/commands.ci-verify-versions.cpp
src/vcpkg/registries.cpp
src/vcpkg/versions.cpp

The registries machinery like version database parsing is annoying to reuse because it has this VersionDbEntry type which can represent version records in both filesystem and git registries, forcing all callers that interact with everything to special case both or otherwise tolerate 'silent UB' all over the place. I found that all callers always pass constant values, meaning this all can be totally separate functions and structs, thus eliminating that entire class of error.
This also means that the interface most clients *want*, 'get_builtin_versions', now maps closely to what the actual implementation is doing.
This also means that reading git registries no longer requires clients to cough up a meaningless 'root' variable.
This also means that callers like add-version and …

Burninate VersionDbType control coupling.

---

src/vcpkg/commands.new.cpp

vcpkg new should validate name as an identifier. 
Before:
```
vcpkg new --name HelloWorld --version 1.0
```
After:
```
vcpkg new --name HelloWorld --version 1.0
error: "HelloWorld" is not a valid identifier. Identifiers must be lowercase alphanumeric+hypens and not reserved (see https://learn.microsoft.com/vcpkg/commands/new for more information)
```

vcpkg new / validate name

---

docs/vcpkg-schema-definitions.schema.json

This is what the product does, see tests:
https://github.com/microsoft/vcpkg-tool/blob/785af0d180135ea93077c364445e879eb75dd1b4/src/vcpkg-test/manifests.cpp#L335-L433

Correct schema for version overrides to show that they accept a schemed version

---

src/vcpkg/commands.install.cpp

Allows stuff like --trace etc. be used in manifest mode. Don't see a reason to add extra commands for all possible cmake options to vcpkg if it can be passed via --x-cmake-args.

--x-cmake-args: Only imply editable if a variable is being set

---

include/vcpkg/base/parallel-algorithms.h
src/vcpkg/base/system.process.cpp
src/vcpkg/postbuildlint.cpp

In #694 I proposed the use of parallel for_each for some use cases. The problem was that it was possible that the program is exited during a loop iteration.
Here I checked that functions inside the loop don't exit.
I observed that checking for absolute paths is the post build check that needs by far the longest time. This check opens almoast every non-binary file that a port installed and searches for absolute paths. This results in linear complexity. If a file isn't too big, parsing doesn't take that long but it adds up if there are multiple header files. Using parallel for_each as proposed here can therefore lead to significant speedup. The speedup increases with number and size of installed header files. I observed ~3x speedup for nlohmann-json:x64-windows (release build).
Note that …

Search for absolute paths in parallel

---

CMakeLists.txt
azure-pipelines/end-to-end-tests-dir/edit.ps1
src/test-editor.c
src/vcpkg/base/system.process.cpp

Fix edit command I broke in https://github.com/microsoft/vcpkg-tool/commit/81c8bedf74dd27b9c00b25e787256d98464e85d0
`PROC_THREAD_ATTRIBUTE_HANDLE_LIST` rejects a list of length `0`. Instead, just pass false to bInheritHandles in the CreateProcess call.

Fix edit command.

---

include/vcpkg/base/fwd/system.h
src/vcpkg-test/system.cpp
src/vcpkg/base/system.cpp
src/vcpkg/platform-expression.cpp
src/vcpkg/triplet.cpp

After making the modifications, I tested fmt, spdlog, bzip2, zlib, openssl, libcurl, cpr, protobuf, qt5-base, and ffmpeg, and they all work correctly.
```bash
$ gcc -dM -E - < /dev/null | grep mips
#define _MIPS_TUNE "mips64r2"
#define __mips_abicalls 1
#define __mips_no_madd4 1
#define __mips_fpr 64
#define __mips__ 1
#define mips 1
#define _MIPS_ARCH "mips64r2"
#define __mips_isa_rev 2
#define __mips64 1
#define _mips 1
#define __mips_hard_float 1
#define __mips 64
```
install spdlog success
```
$ ./vcpkg install spdlog
Computing installation plan...
The following packages will be built and installed:
spdlog:mips64-linux -> 1.12.0
Detecting compiler hash for triplet mips64-linux...
Restored 0 package(s) from /home/user/.cache/vcpkg/archives in 24.9 us. Use --debug to see more details. …
```

add mips64 target support

---

azure-pipelines/end-to-end-tests-dir/commands.extract.ps1
src/vcpkg/base/system.process.cpp
src/vcpkg/tools.cpp

Attempts to resolve https://github.com/microsoft/vcpkg/issues/33904
@Neumann-A can you check that this fixes it for you?

Don't inherit the same handle more than once.

---

src/vcpkg/postbuildlint.cpp

Resolves https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1901356
See also https://github.com/microsoft/vcpkg/pull/34481

Add base64.h, Makefile, Makefile.am, and Makefile.in to the banned header list.

---

include/vcpkg/sourceparagraph.h
include/vcpkg/versions.h
src/vcpkg-test/dependencies.cpp
src/vcpkg-test/manifests.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/sourceparagraph.cpp
src/vcpkg/versions.cpp

Another extraction from https://github.com/microsoft/vcpkg-tool/pull/1210/

Use Version in DependencyOverride rather than reinventing it.

---

src/vcpkg/commands.z-changelog.cpp

Drive by: get rid of from/to
Thanks to @autoantwort for pointing this out.

Fix the changelog updated ports count.

---

azure-pipelines/end-to-end-tests-dir/registries.ps1
azure-pipelines/end-to-end-tests-dir/versions.ps1
azure-pipelines/end-to-end-tests-prelude.ps1
include/vcpkg/vcpkgpaths.h
src/vcpkg/commands.ci-verify-versions.cpp
src/vcpkg/commands.portsdiff.cpp
src/vcpkg/registries.cpp
src/vcpkg/vcpkgpaths.cpp

Use the git repo of `--x-builtin-ports-root` and `--x-builtin-registry-versions-dir` when talking about port commit shas and version tree shas, respectively.
I believe this is necessary to make the instructions in https://learn.microsoft.com/vcpkg/produce/publish-to-a-git-registry#4---update-the-versions-database actually work.
This also reduces the number of things that assume VCPKG_ROOT is a git repo. (Since it is not when we are shipped in VS or acquired with the one liner)
Another extraction from https://github.com/microsoft/vcpkg-tool/pull/1210 .

Use ports-root and registry-versions git repos.

---

src/vcpkg/commands.ci.cpp

Detected because I got [this](https://github.com/microsoft/vcpkg/pull/34702#issuecomment-1778369624) comment a ci was green.

Ci: also output "Regression: marked as fail but not supported" when there are no other errors

---

include/vcpkg/sourceparagraph.h
src/vcpkg-test/manifests.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/sourceparagraph.cpp

Another extraction from https://github.com/microsoft/vcpkg-tool/pull/1210 .

Push ExpectedL into the SourceControlFile::parse family.

---

include/vcpkg/base/expected.h
include/vcpkg/base/optional.h
src/vcpkg/base/system.process.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/sourceparagraph.cpp

1. Optional and expected were not properly forwarding noexcept for their special member functions, so is_nothrow_move_constructible_v<Expected<T>> was false for all T. (This has bad implications if the expecteds are in a vector)
2. system.process.cpp uses a 32k stack buffer but it's the "top" of the stack so we don't care.
3. dependencies.cpp was calling std::move() on a constant variable `info_ptr->default_features`; I changed the declarations to better show that this was const.
4. (Drive by) All users of make_optional were actually doing emplacement.

Fix VS static analyzer warnings.

---

CMakeLists.txt

Probably fixes https://github.com/microsoft/vcpkg-tool/pull/1256#issuecomment-1785445189
Target `vcpkg-test` doesn't declare build dependencies on test executables. As a result, unit tests fail if those executables were missing.

Fix unit tests

---

include/vcpkg/base/strings.h
src/vcpkg-test/strings.cpp
src/vcpkg/base/strings.cpp
src/vcpkg/postbuildlint.cpp

Using `std::boyer_moore_horspool_searcher` results in approx. 3x speedup of `Strings::contains_any()` which is used by `contains_any_ignoring_c_comments()` during post build lint.
Note that this search algorithm is only useful when dealing with long strings: [cppreference](https://en.cppreference.com/w/cpp/utility/functional/boyer_moore_horspool_searcher)

Use different search algorithm in `Strings::contains_any`

---

azure-pipelines/e2e-ports/overlays/set-detected-head-version/portfile.cmake
azure-pipelines/e2e-ports/overlays/set-detected-head-version/vcpkg.json
azure-pipelines/end-to-end-tests-dir/classic-versions.ps1
include/vcpkg/commands.build.h
include/vcpkg/versions.h
src/vcpkg-test/versions.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/versions.cpp

Alternative resolution of https://github.com/microsoft/vcpkg-tool/pull/1259
This adds a test that we store the detected build tree version, and adds paranoia defenses that the resulting version can at least be interpreted as a `version-string`.

Clarify BuildInfo::version's purpose.

---

include/vcpkg/commands.build.h
include/vcpkg/commands.install.h
include/vcpkg/commands.set-installed.h
src/vcpkg-test/issue_body.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/commands.set-installed.cpp

In the past I sometimes got errors like 
```
➜  vcpkg git:(test-features) ✗   gh issue create -R microsoft/vcpkg --title "[llvm] Build failure" --body-file /Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/vcpkg/issue_body.md
Creating issue in microsoft/vcpkg
GraphQL: Body is too long (maximum is 65536 characters) (createIssue)
```
With this PR the body size is enforced and dynamically distributed between the logs that are copied into the issue body.

Fix github issue body size

---

src/vcpkg-test/issue_body.cpp
src/vcpkg/commands.build.cpp

Interestingly this is `1` on my mac and crashes on msvc (welcome UB).

create_github_issue: Fix div by zero

---

vcpkg-artifacts/vcpkg.ts

A quick PR to guard from running the promise `reject()` function straight after the `resolve()` function.

Return after resolving promise

---

include/vcpkg/vcpkgcmdarguments.h
src/vcpkg/vcpkgcmdarguments.cpp

Use the repository ID to differentiate projects using vpckg in an ADO or GitLab CI environments.

Add unique repository ID detection in ADO and GitLab

---

azure-pipelines/end-to-end-tests-dir/e2e-registry.ps1
azure-pipelines/end-to-end-tests-dir/upgrade.ps1
include/vcpkg/binaryparagraph.h
include/vcpkg/dependencies.h
src/vcpkg-test/dependencies.cpp
src/vcpkg/binaryparagraph.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/commands.list.cpp
src/vcpkg/commands.owns.cpp
src/vcpkg/dependencies.cpp

In https://github.com/microsoft/vcpkg/pull/35164 there was some confusion where a customer thought `vcpkg ci` was building an old version of openvino because we only printed the version to build for the `--dry-run` prepass and didn't print the version to build for the actual build. The customer thought we were building the old version rather than the new version as a result.
This change ensures we print the version we are discussing after "Installing" or "Building" and consistently uses the "packagespec@version" form in all the places. For consistency the "packagespec -> version" form we used in a few places is replaced with the @ form.

Print "@version" when talking about port versions more frequently.

---

include/vcpkg/base/message-data.inc.h
include/vcpkg/base/system.h
locales/messages.json
src/vcpkg.cpp
src/vcpkg/base/system.cpp

A customer reported a problem where sometimes `vcpkg-cmake` can't detect that Ninja is safe to use. There, despite being on an amd64 system, this block didn't detect that things were OK:
https://github.com/microsoft/vcpkg/blob/08c4e71048eb54733d9b180a28b9b1d7ce637454/ports/vcpkg-cmake/vcpkg_cmake_configure.cmake#L55-L61
We are unable to replicate the problem, but suspect that they may be in an environment where `PROCESSOR_ARCHITECTURE` isn't set properly, similar to what we experienced in https://github.com/microsoft/vcpkg-tool/pull/769 .
Try to fix this problem by explicitly setting it to what it should be.
Before:
```console
PS D:\vcpkg> rm env:PROCESSOR_ARCHITECTURE
Remove-Item: Cannot find path 'Env:\PROCESSOR_ARCHITECTURE' because it does not exist.
PS D:\vcpkg> rm …
```

Reset PROCESSOR_ARCHITECTURE on start

---

include/vcpkg/commands.build.h
include/vcpkg/commands.z-extract.h
include/vcpkg/commands.z-generate-message-map.h
include/vcpkg/vcpkgcmdarguments.h
src/vcpkg-test/arguments.cpp
src/vcpkg-test/commands.extract.cpp
src/vcpkg-test/dependencies.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.cpp
src/vcpkg/commands.export.cpp
src/vcpkg/commands.help.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/commands.remove.cpp
src/vcpkg/commands.z-applocal.cpp
src/vcpkg/commands.z-extract.cpp
src/vcpkg/commands.z-generate-message-map.cpp
src/vcpkg/configure-environment.cpp
src/vcpkg/vcpkgcmdarguments.cpp

Use `StringLiteral` for the switches and settings arrays.

StringLiteral for command switches and settings

---

src/vcpkg/commands.build.cpp

```console
commands.build.cpp
E:\Repro\RWC\vcpkg_tool_repro\vcpkg-tool\src\vcpkg\commands.build.cpp(1498,68): error C7595: 'fmt::v10::basic_format_string<char,const std::string &>::basic_format_string': call to immediate function is not a constant expression
E:\Repro\RWC\vcpkg_tool_repro\vcpkg-tool\include\vcpkg\base\stringview.h(33,62): note: failure was caused by a read of a variable outside its lifetime
E:\Repro\RWC\vcpkg_tool_repro\vcpkg-tool\include\vcpkg\base\stringview.h(33,62): note: see usage of 'details_start'
E:\Repro\RWC\vcpkg_tool_repro\vcpkg-tool\src\vcpkg\commands.build.cpp(1498,68): note: the call stack of the evaluation (the oldest call first) is
E:\Repro\RWC\vcpkg_tool_repro\vcpkg-tool\src\vcpkg\commands.build.cpp(1498,68): note: while evaluating function 'const char …
```

Fix use-out-of-constexpr lifetime detected by prerelease MSVC

---

vcpkg-artifacts/constants.ts

Arm has a new more general URL for hosting our artifact registry. This PR updates the default configuration to use the new URL.
The old URL remains functional for backwards compatibility.

Update default arm registry to new URL

---

src/vcpkg/base/system.process.cpp

Fix https://github.com/microsoft/vcpkg/issues/34442
Use namespaces `::` to limit repeated calls to SDK `TlHelp32.h` function names:
`TlHelp32.h`: 
```
#ifdef UNICODE
#define Process32First Process32FirstW
#define Process32Next Process32NextW
#define PROCESSENTRY32 PROCESSENTRY32W
#define PPROCESSENTRY32 PPROCESSENTRY32W
#define LPPROCESSENTRY32 LPPROCESSENTRY32W
#endif  // !UNICODE
```

[vcpkg] Avoid name conflicts with sdk functions

---

CMakeLists.txt

We have no reason to build vcpkg as arm64ec, but the C++ compiler team have asked us to make this work since they use us as a test case.
Unfortunately, CMake's defaults ( https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Platform/Windows-MSVC.cmake#L243 ) take the pretty names AMD64 and ARM64EC which we use in the COFF file reader. This removes those defines.
Thanks to Wei Lin Wang for the bug report and @markle11m for help.

Allow vcpkg to be built arm64ec.

---

src/vcpkg/commands.install.cpp

If vcpkg is in editable mode or has disabled compiler tracking, the package ABI message will be empty.

Fix empty ABI string

---

include/vcpkg/base/util.h
include/vcpkg/commands.build.h
include/vcpkg/commands.set-installed.h
include/vcpkg/fwd/build.h
src/vcpkg-test/ci-baseline.cpp
src/vcpkg-test/xunitwriter.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/ci-baseline.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/commands.set-installed.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/postbuildlint.cpp
src/vcpkg/xunitwriter.cpp

I observed that some of our enum classes like DryRun use PascalCase like most of our type names, and others used ALL_CAPS_SNAKE_CASE. I resolved in favor of PascalCase since enum classes are already prefixed and thus unworried about conflicts.
(Visual Studio Control+R Control+R made most of these edits :))

Use less shouty enums.

---

src/vcpkg/base/system.cpp

vcpkg overrides Ninja's logic to guess the ideal number of threads to use.
Unfortunately the C++ `std::thread::hardware_concurrency()` doesn't take into account the platform specific CPU affinity.
This means that starting a container (docker or systemd-nspawn) with specific CPUs assigned will attempt to start more threads than usable.
The common use-case would be for CI, where you have limited resources and worse than just suboptimal number of threads you can actually go out of memory with current behavior.
This can of course be manually fixed by setting the environment variable `VCPKG_MAX_CONCURRENCY` but it seems reasonable to ignore CPUs we can't use anyway, like Ninja [does](https://github.com/ninja-build/ninja/blob/fd7067652cae480190bf13b2ee5475efdf09ac7d/src/util.cc#L798).
Ninja …

Take CPU set into account when determining concurrency on Linux.

---

include/vcpkg/base/files.h
include/vcpkg/base/parallel-algorithms.h
src/vcpkg/base/files.cpp
src/vcpkg/postbuildlint.cpp

* Don't open multiple handles to the same file when looking for absolute paths.
* Don't use `std::future`.

Try to fix macOS hang when building Python 2

---

src/vcpkg/platform-expression.cpp

@kobykahane Or do you prefer that `arm64` also matches `arm64ec`

Add arm64ec platform expression

---

vcpkg-init/vcpkg-init.ps1

Add quotes around the VCPKG_ROOT and Z_POWERSHELL_EXE variable path assignments.
Without adding quotes around the set variable path assignments, paths that contain a close parenthesis character `)` would cause the command/batch file to exit prematurely and vs batch call chains (e.g., vcvarsall.bat) to fail.

Add quotes around the VCPKG_ROOT and Z_POWERSHELL_EXE variable path assignments.

---

CMakePresets.json

Before:
Creates a directory called `out\\build\\macos-ci`
After:
Creates a directory in `out`/`build`/`macos-ci`
:)

Fix macos-ci preset

---

src/vcpkg/postbuildlint.cpp

DLLs can be in static triplets if BuildPolicy::DLLS_IN_STATIC_LIBRARY is turned on. Those DLLs should still have CRT and architecture checked, that sort of thing.
Static libs can be in dynamic triplets, and their CRT linkage still needs to match.

DLL policies should apply in static triplets, lib policies should apply in dynamic triplets.

---

azure-pipelines/end-to-end-tests-dir/registries.ps1
src/vcpkg/portfileprovider.cpp

Fixes this issue reported in the vcpkg project:
https://github.com/microsoft/vcpkg/issues/36994
The "entry" function does not return an error but an empty RegistryEntry in some situations, needs to be checked for.
An alternative solution would be to refactor all registry implementations to never return an empty RegistryEntry, but an error instead. 
That should be done in a separate issue after this fix is merged.

Fixed crash on non-existent port with version override

---

azure-pipelines/signing.yml

This gets rid of needing to talk to Key Vault, and reuses the same base with which we test Android over in github.com/microsoft/vcpkg

Adopt CBL Mariner and Managed Identity for Docker/Alpine

---

include/vcpkg/binarycaching.h
src/vcpkg/binarycaching.cpp

`BinaryProviders::nuget_repo` wasn't getting set anywhere, even though `BinaryCache::push_success()` uses it.
Also removed `BinaryConfigParserState::nuget_repo_info` which was unused.
Without this change, pushing any package into my GHE nuget cache resulted in these kinds of errors (started happening 3+ months ago on my Ubuntu 20.04 GitHub Actions runner):
```
Pushing vcpkg-cmake-config_x64-linux.2022.2.6-vcpkga66b0ae909b0dfb01b299ab9de46b1e919ddf11d8565c40906a893993d6b3ce8.nupkg to 'https://nuget.git.[redacted]'...
PUT https://nuget.git.[redacted]
WARNING: No destination repository detected. Ensure the source project has a 'RepositoryUrl' property defined. If you're using a nuspec file, ensure that it has a repository element with the required 'type' and 'url' attributes.
BadRequest …
```

Fix binary caching push failures (set `BinaryProviders::nuget_repo`) & remove unused field

---

src/vcpkg-test/dependinfo-graphs.cpp
src/vcpkg/commands.depend-info.cpp

Make test format more readable for humans with line breaks. (Note: https://learn.microsoft.com/en-us/vcpkg/commands/depend-info#dot doesn't show literal output.)
Use pristine package names via quotes.
Use "Sans" font.
Output for `ableton-link`:
~~~dot
digraph G{ rankdir=LR; node [fontname=Sans]; edge [minlen=3]; overlap=false;
"ableton";
"ableton" -> "ableton-link";
"ableton-link";
"ableton-link" -> "asio";
"ableton-link" -> "vcpkg-cmake";
"ableton-link" -> "vcpkg-cmake-config";
"asio";
"asio" -> "vcpkg-cmake";
"asio" -> "vcpkg-cmake-config";
"vcpkg-cmake";
"vcpkg-cmake-config";
"2 singletons...";
}
~~~
Wish list:
- Drop the "singletons" comment node.
- Top-bottom rankdir, which is the default format for dot, also for mermaid.
(Users can override it with `dot -Grankdir=TB`.) Output:

Improve `depend-info --dot` output

---

azure-pipelines/end-to-end-tests-dir/usage.ps1
src/vcpkg/commands.install.cpp

Follow pattern from CMake packages. In particular, indent with `append_indent()`.
Fixes mixed indentation when a port has both CMake and pkg-config (and copied like that into `usage` files, e.g.):
~~~
libosdp provides CMake targets:
find_package(LibOSDP CONFIG REQUIRED)
target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:libosdp::osdp>,libosdp::osdp,libosdp::osdpstatic>)
libosdp provides pkg-config modules:
libosdp
~~~
~~~
^^^

Unify usage hint formatting

---

include/vcpkg/commands.build.h
src/vcpkg/commands.build.cpp

- Store files as vector of Path right away.
This is semantically more correct and saves extra string copies.
- Turn `external_toolchain_file` into a Path
- Drive by: Don't leak i outside the loop

Paths in PrebuildInfo should be `Path` instead of `std::string`

---

src/vcpkg/commands.depend-info.cpp

Enables feature control for dependencies, as in 
~~~
$ vcpkg depend-info proj[core,tiff] tiff[core]
vcpkg-cmake: 
vcpkg-cmake-config: 
liblzma: vcpkg-cmake, vcpkg-cmake-config
zlib: vcpkg-cmake
nlohmann-json: vcpkg-cmake, vcpkg-cmake-config
sqlite3[json1, tool]: vcpkg-cmake, vcpkg-cmake-config
tiff[zip, lzma]: liblzma, vcpkg-cmake, vcpkg-cmake-config, zlib
proj[tiff]: nlohmann-json, sqlite3, tiff, vcpkg-cmake, vcpkg-cmake-config
~~~
Fixes https://github.com/microsoft/vcpkg/issues/36604.
For this to work reasonably, it is necessary to make `depend-info` triplet-aware, so this is included in this PR in the following way.
- To retain current output for native targets, the default triplet is never appended.
- For non-native targets, host packages are generically labeled `:host` (instead of …

Enable multi-package `depend-info`, track triplets

---

include/vcpkg/base/strings.h
src/vcpkg-test/strings.cpp
src/vcpkg/base/strings.cpp
src/vcpkg/postbuildlint.cpp

This should have the effect of disabling this on macOS which hopefully fixes the Python2 hang.
Related: https://github.com/microsoft/vcpkg-tool/pull/1255

Disable experimental boyer_moore_horspool_searcher.

---

CMakePresets.json

[scripts/bootrap.sh](https://github.com/microsoft/vcpkg/blob/master/scripts/bootstrap.sh) does some rather interesting composition of a cmake call around [lines 214](https://github.com/microsoft/vcpkg/blob/master/scripts/bootstrap.sh#L214) which results in having to use `eval` to get rid of the double-escaping of some strings.
Further, the ninja-specific multi-task build job rules are quite nasty and probably don't provide us with anything that passing `--parallel` to `cmake --build` could also do.
Add a CMakePreset.json representing the cmake invokation of `bootstrap.sh`, and replace the ninja specific code by `--build` - or - if the ninja specialization has to stay, derive a ninja multi-tasking preset from the regular, which allows simplifying the bootstrap script, as well as invoking …

[vcpkg-tool] Add a cmake preset for boostrap-vcpkg.sh

---

src/vcpkg/commands.format-manifest.cpp

Amends #1346.
Fix abort in debug builds where an empty `origin` was passed into `SpdxLicenseExpressionParser`, cf. https://github.com/microsoft/vcpkg-tool/pull/1346#discussion_r1548919401.
Fix wrong direction in debug output when converting `CONTROL` files.

`<unsaved>` is an origin: Fix `format-manifest` command

---

src/vcpkg/commands.depend-info.cpp

Just https://github.com/microsoft/vcpkg-tool/pull/1371/commits/8361878a4bc4dab9c5dcae6344974e12d76fd160
Depends on (for now, includes) #1369 and #1370.
Example:
~~~
vcpkg depend-info proj:arm64-linux proj tiff[core] --triplet x64-linux-dynamic --dot | dot -Tpng -oimg.png && xdg-open img.png
~~~
Output:

Colorize multi-triplet dot graphs

---

src/vcpkg/commands.build.cpp

The generated issue bodies lack a second newline after the command, resulting in this slightly odd formatting:
This should fix the issue by adding another newline.

Style: Use double newlines in generated issue body

---

src/vcpkg/commands.portsdiff.cpp

There is no need to actually calculate the difference between 2 commits if they are the same.

[portsdiff] Optimize for identical commits

---

docs/artifact.schema.json
docs/vcpkg-configuration.schema.json
docs/vcpkg-schema-definitions.schema.json
docs/vcpkg.schema.json

The `$id` fields in all JSON schemas were wrongly referring to a non-existent `master` branch. This isn't too bad because GitHub has some magic to fall back to the default branch when non-existent `master` branches are requested, but it is still incorrect. Fix it.

Use correct branch name in json schema ids

---

src/vcpkg-test/spdx.cpp
src/vcpkg/spdx.cpp

Fixed version export in spdx module.
Current behavior: `Tool: vcpkg-$hash`
New behavior: `Tool: vcpkg-$version-$hash` like in [Curl module](https://github.com/microsoft/vcpkg-tool/blob/968db4d0d2d2b210d5c825351648886cf67e306c/src/vcpkg/base/downloads.cpp#L607).
Perhaps there should only be $version, without $hash: `Tool: vcpkg-$version`.

Fixed version export in spdx module

---

azure-pipelines/e2e-ports/overlays/vcpkg-header-only/portfile.cmake
azure-pipelines/e2e-ports/overlays/vcpkg-header-only/vcpkg.json
azure-pipelines/end-to-end-tests-dir/usage.ps1
src/vcpkg/commands.install.cpp

This regression is from PR #1368.
The wrong message as below:
```
bext-sml is header-only and can be used from CMake via:
find_path(BEXT_SML_INCLUDE_DIRS ")boost/sml.hpp")
target_include_directories(main PRIVATE ${BEXT_SML_INCLUDE_DIRS})
```

Fix wrong Header-only usage message

---

src/vcpkg/base/checks.cpp

Fixes #38883 
Before:
```
➜  vcpkg git:(test-features) ✗ ./vcpkg x-package-info libtorch
This command requires --x-jsonnote: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```
After:
```
➜  vcpkg git:(test-features) ✗ vcpkg x-package-info libtorch                                   
This command requires --x-json
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

Add missing new line

---

src/vcpkg/binarycaching.cpp

This fixes https://github.com/microsoft/vcpkg/issues/31932
Previously, when using the AWS S3 binary cache, every cache miss triggered the following message:
```
warning: error: aws failed with exit code: (1).
```
This was both noisy and misleading (because it was not an actual error).
Now AWS cache misses are treated silently, the same way as cache misses from the local cache are.
> [!NOTE]
> I don't have access to either Google Cloud Storage or Tencent Cloud Object Storage sources, so I don't know whether the same kind of issue happens there too; in any case, fixing those should be easy using the newly introduced interface. (Their `stat()` and `download_file()` methods need to be adapted to return `CacheResult::miss` in the relevant cases.)

AWS S3 cache miss should not issue warning

---

src/vcpkg/archives.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/postbuildlint.cpp
src/vcpkg/registries.cpp
src/vcpkg/vcpkgpaths.cpp

I found some hardcoding when I read the source of vcpkg search, seems ```contractual-constants``` is a new file and lots of hardcoding is not removed, like ```CONTROL``` and ```BUILD_INFO``` , and I only removed ```.DS_Store``` now.

Remove hardcoding ".DS_Store"

---

src/vcpkg/base/downloads.cpp

This is a proposition to solve the issue reported in this https://github.com/microsoft/vcpkg/discussions/38827.
This replaces the first proposed implementation in https://github.com/microsoft/vcpkg-tool/pull/1410, following suggestions of @BillyONeal : curl is now used instead of winhttp for download as soon as we have credentials in the URL provided for HTTP proxy (through the HTTPS_PROXY environment variable).
**Status:**
- Quick implementation to check that it is a better way to go than previous implementation.
Just checking for "@" in the proxy URL, which might need some refinement ? not obvious though.
- Successfully tested with squid proxy in test env
- Question: should we use curl download as soon as a proxy url is defined ? that would eliminate some code from the winhttp download …

Use curl for download on windows when proxy auth is required

---

src/vcpkg/tools.cpp

This pull request rewrites #1418 without adding any new function for regex matching. Instead, it uses the `nuget help -ForceEnglishOutput` command instead of just the plain `nuget` command used to detect its version.
Fixes microsoft/vcpkg#38940.

Add "-ForceEnglishOutput" flag to the NuGet help command in tools.cpp

---

include/vcpkg/base/message-data.inc.h
locales/messages.json

It seems export command gives wrong help message for specifying output directory.
```
C:\Users\myd7349>vcpkg export edflib --directory D:\edflib
error: unexpected switch: --directory
vcpkg export <port names> [--nuget] [--directory=out_dir]
vcpkg export zlib zlib:x64-windows boost --nuget
Options:
...
```

Fix export command usage

---

azure-pipelines/signing.yml

Blocked by https://dev.azure.com/twcdot/Data/_workitems/edit/128379

Disable CodeQL until the hang is fixed

---

src/vcpkg/platform-expression.cpp

Since https://github.com/microsoft/vcpkg-tool/pull/1226 there is a mips64 identifier, but it is not handled which causes vcpkg to crash.

Fix crash if `"platform": "mips64"` is used

---

include/vcpkg/base/message-data.inc.h
locales/messages.json
src/vcpkg-test/configparser.cpp
src/vcpkg/binarycaching.cpp

Fixes https://github.com/microsoft/vcpkg/issues/39871

Http binary cache: One must use the {sha} variable if other variables are used.

---

azure-pipelines/end-to-end-tests-dir/post-build-checks.ps1
include/vcpkg/base/message-data.inc.h
locales/messages.json
src/vcpkg/postbuildlint.cpp

@autoantwort points out that it makes sense for those to be clickable.
He also wants us to drop the note: prefix from newlines if we aren't attached to a tty; I'm not sure if that is correct.

Restore printing full paths to files containing absolute paths.

---

include/vcpkg/dependencies.h
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/commands.set-installed.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/dependencies.cpp

print_plan does 2 things. First, it formats the action plan and prints it to the console. Second, if there were removals in the plan and the intent is not recursive, it terminates vcpkg. A function named 'print' should not be terminating vcpkg.
Moreover, only one caller actually desires this terminating behavior: the install command. All other users hard coded a value of true.
This suggests that the decision to terminate should be localized to that one caller rather than spread over everything.

Make print_plan actually print.

---

src/vcpkg/commands.portsdiff.cpp

Fixes https://github.com/microsoft/vcpkg/issues/40030
The portsdiff command output lacks a space between the port name and version. This modification adds a space between the output name and version.
before fixing：
After：

Optimize the output of portsdiff command

---

azure-pipelines/end-to-end-tests-dir/post-build-checks.ps1
include/vcpkg/base/message-data.inc.h
locales/messages.json
src/vcpkg/binarycaching.cpp
src/vcpkg/commands.add-version.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/registries.cpp
src/vcpkg/vcpkgpaths.cpp

* In https://github.com/microsoft/vcpkg-tool/pull/1455 I missed making absolute lowercase.
* In https://github.com/microsoft/vcpkg-tool/pull/1408 a lot of whitespace was missed leading to output like
error: building vtk:x64-linux failed with: BUILD_FAILEDSee https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.

Fix several console output nitpicks.

---

.github/workflows/pr.yaml
azure-pipelines/json-schema-tests-dir/json-schema-bvt.test.ps1
azure-pipelines/json-schema-tests-dir/vcpkg-ports-json.test.ps1
azure-pipelines/json-schema-tests.ps1
docs/artifact.schema.json
docs/vcpkg-configuration.schema.json
docs/vcpkg-schema-definitions.schema.json
docs/vcpkg.schema.json
include/vcpkg/base/jsonreader.h
src/vcpkg-test/registries.cpp
src/vcpkg/base/json.cpp
src/vcpkg/configuration.cpp

Fix microsoft/vcpkg/issues/39259 for package pattern with an optional trailing *.
* Add `definitions/reserved-name` for reuse
- Vcpkg reserved name by `^(core|default)$`
- Win32 filesystem reserved name by a loose pattern `^(con|prn|aux|nul|com[0-9]|lpt[0-9])(\\.[^.]+)*$`, which include `COM0` and `LPT0`. See [documents](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions)
* Add `definitions/package-pattern` to fix optional trailing `*`
- Pattern of `^([a-z0-9]+-)*([a-z0-9]+[*]?|[*])$` to [match wildcard or ‘boost*’ or ‘boost-*’](https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-configuration-json#registry-packages)
* Replace `definitions/port-name` with `definitions/identifier`
- Pattern of `port-name` matches 'dot-separated identifier'. No …

Fix package pattern in json schema configuration registry

---

docs/vcpkg-schema-definitions.schema.json

Related: https://github.com/microsoft/vcpkg/issues/30939

Allow "baseline" in filesystem registries.

---

include/vcpkg/base/message-data.inc.h
locales/messages.json

Previous message said `The zlib contains 42 files`. Now says `The port 'zlib' contains 42 files`

Fix grammar in HashPortManyFiles warning message

---

azure-pipelines/end-to-end-tests-dir/ci.ps1
src/vcpkg/commands.ci.cpp

Related: https://github.com/microsoft/vcpkg/issues/40124

Change the exit code to nonzero when there are ci regressions.

---

azure-pipelines/e2e-ports/vcpkg-bad-spdx-license/portfile.cmake
azure-pipelines/e2e-ports/vcpkg-bad-spdx-license/vcpkg.json
azure-pipelines/end-to-end-tests-dir/build-test-ports.ps1
include/vcpkg/base/message-data.inc.h
include/vcpkg/fwd/sourceparagraph.h
include/vcpkg/metrics.h
include/vcpkg/paragraphs.h
include/vcpkg/portfileprovider.h
include/vcpkg/registries.h
include/vcpkg/sourceparagraph.h
locales/messages.json
src/vcpkg/commands.build-external.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/commands.check-support.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.depend-info.cpp
src/vcpkg/commands.env.cpp
src/vcpkg/commands.export.cpp
src/vcpkg/commands.find.cpp
src/vcpkg/commands.format-manifest.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/commands.package-info.cpp
src/vcpkg/commands.remove.cpp
src/vcpkg/commands.set-installed.cpp
src/vcpkg/commands.update.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/portfileprovider.cpp
src/vcpkg/registries.cpp
src/vcpkg/sourceparagraph.cpp

Resolves https://github.com/microsoft/vcpkg/issues/24084
Resolves https://github.com/microsoft/vcpkg/issues/34095
The root cause of this bug is the separation between the BaselineProvider and the PortfileProvider. For the built in registry, to determine what the baseline version for the builtin registry is, we must load and parse the requested port to read what version is declared in its JSON/CONTROL file. However, the interface by which the registry tells the calling code what to do passed only the directory with the port inside:
```c++
struct RegistryEntry
{
// This forces BuiltinRegistry to parse the JSON/CONTROL
virtual ExpectedL<View<Version>> get_port_versions() const = 0;
// This forces the caller to parse the JSON/CONTROL
virtual ExpectedL<PortLocation> get_version(const Version& …
```

Fix doubled warnings being printed for manifest warnings when loading ports.

---

src/vcpkg-test/input.cpp
src/vcpkg/input.cpp

Fixes https://github.com/microsoft/vcpkg/issues/10120
Triplets specified together with ports, e.g. `zlib:x64-windows` are restricted to lowercase alphanumeric characters and hyphens. However, triplets passed using `--triplet` or `--host-triplet` weren't checked for this requirement.
This PR resolves this inconsistency by adding validation of triplet names to `check_triplet`.

Disallow invalid triplet names passed via `--triplet`

---

azure-pipelines/end-to-end-tests-dir/upgrade.ps1
azure-pipelines/end-to-end-tests-prelude.ps1

* Removes the hack added in https://github.com/microsoft/vcpkg-tool/pull/1477
* Tests the condition fixed by https://github.com/microsoft/vcpkg-tool/pull/1473
I extracted this from https://github.com/microsoft/vcpkg-tool/pull/1486

upgrade.ps1: Test without needing a whole git clone

---

CMakeLists.txt
src/closes-exit-minus-one.c
src/vcpkg-test/system.process.cpp

Add test program `closes-exit-int-min.c` to return exit code with negative value `-1`, expected `-1` for `windows`, expected 255 for `unix`.
Failed as expected before #1489

Test cmd_execute with negative exit code

---

include/vcpkg/base/util.h
include/vcpkg/metrics.h
src/vcpkg-test/metrics.cpp
src/vcpkg-test/specifier.cpp
src/vcpkg/base/hash.cpp
src/vcpkg/base/messages.cpp
src/vcpkg/base/system.mac.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/cmakevars.cpp
src/vcpkg/metrics.cpp
src/vcpkg/vcpkgcmdarguments.cpp

std::array is actually not that cheap to compile and we did not really need it in these cases. ( https://raw.githubusercontent.com/ned14/stl-header-heft/master/graphs/msvs-2019.png )
The remaining place we still use it is in tools.cpp where it represents a version breakdown; that change was invasive so I've separated this off for now.

Remove unnecessary use of std::array

---

src/vcpkg/base/system.process.cpp

Fixes https://github.com/microsoft/vcpkg/issues/41199
Thank you @tmp64 for identifying why the problem exists :)
[The old code](https://github.com/microsoft/vcpkg-tool/commit/d3fc35774f86782f356ef0f9352ba857fa57302e#diff-33cf7c311a76d4a838f91b078c2f8cbc984557379f7b345a268ec6deb665a91eL672) was also case insensitive, because `get_environment_variable` is case insensitive

Fix regression on windows: Env var names are case insensitive

---

src/vcpkg/archives.cpp

Enable extracting 7zNNNN-x64.exe with win32_extract_self_extracting_7z

---

include/vcpkg/base/message-data.inc.h
locales/messages.json
src/vcpkg-test/cmd-parser.cpp
src/vcpkg/base/cmd-parser.cpp

Before / after:
```console
PS D:\vcpkg\test> ..\vcpkg.exe new --application
PS D:\vcpkg\test> ..\vcpkg.exe add rapidjson
error: the command 'add' requires between 2 and 18446744073709551615 arguments, inclusive, but 1 were provided
[...]
PS D:\vcpkg\test> D:\vcpkg-tool\out\build\Win-x64-Debug-WithArtifacts\vcpkg.exe add rapidjson
error: the command 'add' requires at least 2 arguments, but 1 were provided
```

Add a better error message for unlimited argument commands.

---

src/vcpkg-test/system.process.cpp

WIFEXITED requires <sys/wait.h> header. On some platforms, the transitive includes have this symbol, but not all.
Specifically, this fixes building on FreeBSD.

Fix missing includes

---

azure-pipelines/end-to-end-tests-dir/build-test-ports.ps1
azure-pipelines/end-to-end-tests-dir/ci-verify-versions.ps1
azure-pipelines/end-to-end-tests-dir/cli.ps1
azure-pipelines/end-to-end-tests-dir/env-passthrough.ps1
azure-pipelines/end-to-end-tests-dir/post-build-checks.ps1
azure-pipelines/end-to-end-tests-dir/usage.ps1
azure-pipelines/end-to-end-tests-dir/versions.ps1
azure-pipelines/end-to-end-tests-prelude.ps1

Extracted from https://github.com/microsoft/vcpkg-tool/pull/1514
Rather than each test case inventing their own way of dealing with the Windows/Linux \`r\`n vs \`n difference, this change just always makes the output collection functions to do that transformation.

Commonize \r\n / \n handling in test cases.

---

include/vcpkg/base/json.h
src/vcpkg/base/json.cpp
src/vcpkg/binarycaching.cpp
src/vcpkg/bundlesettings.cpp
src/vcpkg/commands.set-installed.cpp
src/vcpkg/configuration.cpp
src/vcpkg/configure-environment.cpp
src/vcpkg/sourceparagraph.cpp
src/vcpkg/spdx.cpp
src/vcpkg/vcpkgpaths.cpp

Extracted from https://github.com/microsoft/vcpkg-tool/pull/1514
This avoids some check/confirm anti-patterns and discourages null-dereference prone code like `*example.get()`. Example:
https://github.com/microsoft/vcpkg-tool/blob/ad7b71c9fc939fbeda446592d41d829d02be0724/src/vcpkg/commands.set-installed.cpp#L62

Add "maybe" operations to JSON.

---

include/vcpkg/base/contractual-constants.h
include/vcpkg/base/fmt.h
include/vcpkg/base/graphs.h
include/vcpkg/binaryparagraph.h
include/vcpkg/statusparagraph.h
include/vcpkg/versions.h
src/vcpkg/binaryparagraph.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.export.cpp
src/vcpkg/commands.list.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/export.prefab.cpp
src/vcpkg/metrics.cpp
src/vcpkg/packagespec.cpp
src/vcpkg/spdx.cpp
src/vcpkg/statusparagraph.cpp
src/vcpkg/versions.cpp

Extracted from https://github.com/microsoft/vcpkg-tool/pull/1514

Apply the normal "to_string" pattern in more places.

---

include/vcpkg/paragraphs.h
src/vcpkg/paragraphs.cpp
src/vcpkg/registries.cpp

The last two paths in try_load_port translated a nonexistent port directory or missing CONTROL file into errors, which is the try_load_port_required interface. No path returned the "nullptr scfl" result.
The only caller of try_load_port in registries.cpp therefore clearly wanted the "_required" behavior.

Fix try_load_port to match its documented interface.

---

include/vcpkg/commands.build.h
include/vcpkg/spdx.h
src/vcpkg-test/spdx.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/spdx.cpp

Extracted from https://github.com/microsoft/vcpkg-tool/pull/1514
We were paying to package the object up into a value, then unpackage it.

Make SPDX resource heuristics an object rather than a value.

---

include/vcpkg/commands.build.h
include/vcpkg/commands.set-installed.h
src/vcpkg/commands.build-external.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/commands.set-installed.cpp
src/vcpkg/commands.upgrade.cpp

Extracted from https://github.com/microsoft/vcpkg-tool/pull/1514/
build_package never prints usage so the setting should not be there.

Remove PrintUsage from BuildPackageOptions.

---

include/vcpkg/commands.find.h
include/vcpkg/portfileprovider.h
include/vcpkg/vcpkgpaths.h
src/vcpkg/commands.build-external.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/commands.check-support.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.depend-info.cpp
src/vcpkg/commands.env.cpp
src/vcpkg/commands.export.cpp
src/vcpkg/commands.find.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/commands.package-info.cpp
src/vcpkg/commands.remove.cpp
src/vcpkg/commands.set-installed.cpp
src/vcpkg/commands.update.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/portfileprovider.cpp
src/vcpkg/vcpkgpaths.cpp

This work is part of resolving https://github.com/microsoft/vcpkg/issues/30942 / https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1979597
When overlay directories from the config were added in https://github.com/microsoft/vcpkg-tool/pull/743 this added a condition where VcpkgPaths took responsibility to tack on the relative path, transforming those paths that come from the config into absolute paths. I did not realize at the time that this block was repeating machinery already present in IOverlayProvider family. The difference is that, there, it always assumed the prefix would be original_cwd.
As part of adding overlay-port-dirs, I needed to add the same kind of prefix handling as overlay-ports get, thus pointing this out to me. It doesn't make sense to keep two independent ways to …

Move merging original_cwd into overlay directories into VcpkgPaths.

---

CMakeLists.txt

Our Optional<T&> and Expected<T&> trip over the false positive described in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107532 , where there are temporary Optional or Expecteds that return references to things outside of their own lifetime that trip the warning.
(I tried to edit vcpkg-tool on Ubuntu 24.04 which comes with GCC 13, triggering this)

Disable -Wno-dangling-reference on GCC 13.

---

src/vcpkg/base/system.process.cpp

The warning is intended to detect accidentally running malicious code where a value rather than code is expected, for example the 'shellshock' bug. If we were trying to communicate what should be sanitized data between processes this warning would be appropriate, but this is used for things like `vcpkg env` which is intended to run arbitrary user-supplied shell input.
It's possible that there are places in vcpkg which would use this function inappropriately; effectively, the analysis needs to bubble up to the code that calls the execute_process\* family, but CodeQL doesn't appear to understand this.

Suppress meaningless CodeQL warning.

---

include/vcpkg/base/downloads.h
src/vcpkg/base/downloads.cpp
src/vcpkg/commands.set-installed.cpp

I was trying to use `dependencygraph` feature in my company, and found the following GitHub Action step was not updating the dependency of the repository.
```yaml
- name: "Run vcpkg(install)"
run: vcpkg install --triplet "x64-windows"
env:
GITHUB_TOKEN: ${{ secrets.GHE_ACCESS_TOKEN }}
VCPKG_FEATURE_FLAGS: "...,dependencygraph"
```
With `--debug`, I found the curl has failed with bad credential.
```log
[DEBUG] 1032: CreateProcessW(curl -w "\nfcfad8a3-bb68-4a54-ad00-dab1ff671ed2%{http_code}" -X POST -H "Accept: application/vnd.github+json" -H "Authorization: ***" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/luncliff/experiment-repo/dependency-graph/snapshots -d @-)
[DEBUG] 1032: Unexpected WriteFileEx partial success: 7A
[DEBUG]   % Total    % Received % Xferd  Average …
```

Use `GITHUB_SERVER_URL` to change GitHub API host for dependency graph submission

---

.github/workflows/build.yaml
azure-pipelines/e2e-specs/autocomplete-posh-vcpkg.Tests.ps1
azure-pipelines/end-to-end-tests-dir/autocomplete-posh-vcpkg.ps1
scripts/posh-vcpkg.psd1
scripts/posh-vcpkg.psm1
vcpkg-init/mint-standalone-bundle.ps1

Fixes for https://github.com/microsoft/vcpkg/issues/38184
The function `TabExpansion` is [not supported by PowerShell 7.4.0](https://github.com/PowerShell/PowerShell/issues/20930), which breaks the `posh-vcpkg.psm1` for `vcpkg integrate powershell`.
Use `Register-ArgumentCompleter` instead of `TabExpansion` to fix it.
* vcpkg-init
+ Move `posh-vcpkg` module to non-version directory
* posh-vcpkg
+ Update `posh-vcpkg.psd1` minimum version from 5.0 to [5.1](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/cmdlet-versions?view=powershell-7.4#:~:text=Register%2DCimIndicationEvent)
+ Replace intercepting `TabExpansion` with `Register-ArgumentCompleter`
* pipeline
+ Import module `Pester` for e2e tests
* e2e
+ Add `end-to-end-tests-dir/autocomplete-posh-vcpkg.ps1`
+ Add …

[scripts/posh-vcpkg] Change TabExpansion to Register-ArgumentCompleter

---

src/vcpkg/tools.cpp

Related: https://github.com/microsoft/vcpkg/issues/21218

Add Alpine's search path for Ninja.

---

src/vcpkg/tools.cpp

Prevents https://github.com/microsoft/vcpkg/issues/43063
See https://github.com/microsoft/vcpkg/issues/43063#issuecomment-2571442622

Don't use non functional cmake versions

---

azure-pipelines/e2e-ports/vcpkg-test-x-script/portfile.cmake
src/test-script-asset-cache.c
src/vcpkg/base/downloads.cpp
src/vcpkg/commands.download.cpp

A large customer took a dependency on our happening to use lowercase SHA512s most of the time, and were broken when recent changes to vcpkgTools.xml contained capitalized SHA512s. This change always lowercases the SHA before invoking the x-script.

Ensure x-script's SHA is tolower'd.

---

azure-pipelines/end-to-end-tests-dir/fetch.ps1
src/vcpkg/tools.cpp

Might fix https://github.com/microsoft/vcpkg/issues/39921

7-zip: Consider copies on the system.

---

src/vcpkg/binarycaching.cpp

I recently tried to use the `VCPKG_BINARY_SOURCES` setting to set `clear;x-gha,readwrite` in our GitHub Actions workflow and couldn't get vcpkg to upload to the cache successfully. Proxying vcpkg I noticed that the Content-Range header was off by one causing the cache server to return:
```http
HTTP/2 400 Bad Request
Content-Length: 295
Content-Type: application/json; charset=utf-8
Date: Wed, 15 Jan 2025 02:35:10 GMT
Server: Kestrel
Cache-Control: no-store,no-cache
Pragma: no-cache
...
X-Frame-Options: SAMEORIGIN
{"$id":"1","innerException":null,"message":"The size of the content did not match the Content-Range header","typeName":"Microsoft.Azure.DevOps.ArtifactCache.WebApi.InvalidChunkException, Microsoft.Azure.DevOps.ArtifactCache.WebApi","typeKey":"InvalidChunkException","errorCode":0,"e …
```

Fix GitHub Actions Cache setting an incorrect Content-Range header

---

azure-pipelines/e2e-ports/broken-manifests/broken-duplicate-overrides/portfile.cmake
azure-pipelines/e2e-ports/broken-manifests/broken-duplicate-overrides/vcpkg.json
azure-pipelines/end-to-end-tests-dir/build-test-ports.ps1
include/vcpkg/base/jsonreader.h
include/vcpkg/base/message-data.inc.h
include/vcpkg/configuration.h
include/vcpkg/registries-parsing.h
include/vcpkg/registries.h
locales/messages.json
src/vcpkg-test/configmetadata.cpp
src/vcpkg-test/registries.cpp
src/vcpkg/configuration.cpp
src/vcpkg/registries.cpp
src/vcpkg/sourceparagraph.cpp
src/vcpkg/tools.cpp

Also makes Json::IDeserializer no longer need a virtual dtor.
Before (first one wins):
```
PS D:\test> type vcpkg.json
{
"dependencies": [
"zlib"
],
"overrides": [{"name": "zlib", "version": "1.2.13"}, {"name": "zlib", "version": "1.3.1"}]
}
[...]
Installing 2/2 zlib:x64-windows@1.2.13...
Building zlib:x64-windows@1.2.13...
C:\Users\bion\AppData\Local\vcpkg\registries\git-trees\ad5a49006f73b45b715299515f31164131b51982: info: installing overlay port from here
-- Using cached madler-zlib-v1.2.13.tar.gz.
-- Extracting source D:/vcpkg-downloads/madler-zlib-v1.2.13.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-skip-building-examples.patch
-- Applying patch 0003-build-static-or-shared-not-both.patch
-- Applying patch …
```

Emit an error for duplicate overrides.

---

azure-pipelines/end-to-end-tests-dir/manifests.ps1
azure-pipelines/end-to-end-tests-dir/overlays.ps1
azure-pipelines/end-to-end-tests-prelude.ps1
docs/manifest-info.schema.json
include/vcpkg/base/contractual-constants.h
src/vcpkg/commands.set-installed.cpp

This PR introduces the generation of a manifest_info.json file in the vcpkg_installed directory for projects using a manifest (vcpkg.json). This file contains the absolute path to the manifest file that was used to generate the corresponding vcpkg_installed tree.
https://devdiv.visualstudio.com/DevDiv/_backlogs/backlog/Vcpkg%20Package%20Manager/Stories?System.AssignedTo=javiermat%40microsoft.com&System.State=Active%2CIn%20Progress%2CProposed%2CCommitted&workitem=2253211

Add manifest-info.json to record manifest path in vcpkg_installed

---

.github/workflows/pr.yaml

Resolves failures like:
https://github.com/microsoft/vcpkg-tool/pull/1568/checks
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Update upload-artifact to v4.

---

include/vcpkg/tools.test.h

btw I find it wired that the header is called `tools.test.h`

fix includes

---

src/vcpkg/commands.install.cpp

Partial response to https://github.com/microsoft/vcpkg/issues/40158

Don't emit the 'vs prompt' warning when targeting arm64ec from an arm64 developer command prompt.

---

include/vcpkg/archives.h
include/vcpkg/base/files.h
src/vcpkg-test/files.cpp
src/vcpkg/archives.cpp
src/vcpkg/base/files.cpp
src/vcpkg/configure-environment.cpp
src/vcpkg/tools.cpp
src/vcpkg/vcpkgpaths.cpp

This *might* workaround some failures reported by internal customers.

Improve resiliency of concurrent use the downloads directory.

---

src/tls12-download.c

Resolves https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2342038 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2342019
Demonstration:
https://live.sysinternals.com/RootkitRevealer.exe was released in 2006 and thus can't have a SHA-2 cert. https://live.sysinternals.com/autoruns.exe  was released in 2020 and therefore has a SHA-2 cert.
```
PS D:\vcpkg-tool\out\build\Win-x64-Debug-WithArtifacts> .\tls12-download.exe
Usage: tls12-download.exe DOMAIN RELATIVE-PATH OUT-FILE
PS D:\vcpkg-tool\out\build\Win-x64-Debug-WithArtifacts> .\tls12-download.exe live.sysinternals.com /RootkitRevealer.exe out.exe
Downloading https://live.sysinternals.com/RootkitRevealer.exe -> out.exe... done.
Validating signature... failed! 0x80096002 Deleted!
```
We failed to download …

tls12-download.exe: Enforce that the signing cert uses SHA-2.

---

src/vcpkg/base/system.process.cpp

For me, this fixed debugging with lldb under macOS on AppleSilicon.
This is also a general pattern found other code bases, including well-established
code bases like the dpkg source code:
- https://git.dpkg.org/cgit/dpkg/dpkg.git/tree/utils/start-stop-daemon.c?h=1.22.15#n564
- v1.22.15 is the latest version at time of commit
Note that the above link actually compares the return value of waitpid
against all negative values (`child < 0`). This was made to pacify
static anlyzers in commit 5601b476929a896e1ab67e66e1192d5a90346e75 and
is not any more correct than comparison against the documented return
value of `-1` for error.
- https://git.dpkg.org/cgit/dpkg/dpkg.git/commit/?id=5601b476929a896e1ab67e66e1192d5a90346e75

Check errno after waitpid for EINTR

---

include/vcpkg/commands.install.h
include/vcpkg/postbuildlint.h
src/vcpkg/commands.build.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/postbuildlint.cpp

... rather than attempting to rederive it several times. This clears the way for several actions that want to install the same package name with different feature sets (in #802 ) to not step on each others' toes.
The remaining callers of `VcpkgPaths::package_dir` are all doing so to purge that directory when they will *not* be building it, and in #802 will need to be taught to purge everything following the disambiguating pattern used.

Always use InstallPlanAction::package_dir

---

azure-pipelines/end-to-end-tests-dir/asset-caching.ps1
include/vcpkg/base/message-data.inc.h
locales/messages.json
src/vcpkg/base/downloads.cpp

The message is currently shows when storing to an asset cache
```
Asset cache miss; trying authoritative source https://github.com/tbeu/matio/archive/v1.5.28.tar.gz
Successfully downloaded tbeu-matio-v1.5.28.tar.gz, storing to https://s3.hilton.rwth-aachen.de/assetcache/358318a249e22f5228516309d267593b8da9005de015dc0f59645fbfd7a5001e10be9144f32437acc2f6921d952e03adbaf8b9ca5b6620e191346bb569c04780
Store success
```
or when using a http binary cache
```
Store success
Completed submission of unicorn:arm64-osx@2.1.1 to 2 binary cache(s) in 15 s
Store success
Completed submission of unqlite:arm64-osx@1.1.9#2 to 2 binary cache(s) in 462 ms
Store success
Completed submission of utfz:arm64-osx@1.2#4 to 2 binary cache(s) in 231 ms
Store success
Completed submission of …
```

Remove "Store success" message.

---

src/vcpkg/commands.test-features.cpp

I somehow missed that as a stealth merge conflict

test-features: Wait for async complete of binary cache at end of command

---

azure-pipelines/end-to-end-tests-prelude.ps1
src/vcpkg/base/git.cpp

PR testing in https://github.com/microsoft/vcpkg-tool/pull/1616 passed twice but now CI is failing because git isn't detecting changes.
I don't know exactly why, but issuing a random `git status` after editing the files seems to fix it. I'm guessing it's some sort of race on Ubuntu when mtime doesn't move forward by 1 second that is confusing git, which normally only has 1 second resolution; but I really have no idea.

Try to improve ubuntu test lab reliability

---

include/vcpkg/base/downloads.h
src/vcpkg/base/downloads.cpp
src/vcpkg/commands.download.cpp
src/vcpkg/configure-environment.cpp
src/vcpkg/tools.cpp

Combines with https://github.com/microsoft/vcpkg/pull/44537 to preserve the whole FILENAME in console output.

Use relative paths in downloads output.

---

azure-pipelines/end-to-end-tests-dir/e2e-registry.ps1
include/vcpkg/base/message-data.inc.h
include/vcpkg/dependencies.h
include/vcpkg/fwd/portfileprovider.h
include/vcpkg/paragraphs.h
include/vcpkg/portfileprovider.h
include/vcpkg/sourceparagraph.h
locales/messages.json
src/vcpkg-test/dependencies.cpp
src/vcpkg/commands.add-version.cpp
src/vcpkg/commands.autocomplete.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/commands.ci-verify-versions.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.format-manifest.cpp
src/vcpkg/commands.install.cpp
src/vcpkg/commands.set-installed.cpp
src/vcpkg/commands.upgrade.cpp
src/vcpkg/dependencies.cpp
src/vcpkg/paragraphs.cpp
src/vcpkg/portfileprovider.cpp
src/vcpkg/registries.cpp
src/vcpkg/sourceparagraph.cpp

Related: https://github.com/microsoft/vcpkg-tool/pull/1379#discussion_r1567944235
Previously, we are loading ports from outside the builtin ports directory, so we would refer to these as 'overlays' even when they actually come from versioning / registries.
Couple of examples follow.
Before:
```
C:\Dev\vcpkg-tool\out\build\Win-x64-Debug-WithArtifacts\vcpkg-shell.ps1 install --triplet x86-windows --x-buildtrees-root=C:\Dev\work\testing\buildtrees --x-install-root=C:\Dev\work\testing\installed --x-packages-root=C:\Dev\work\testing\packages --feature-flags=registries,manifests
Detecting compiler hash for triplet x86-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.43.34808/bin/Hostx64/x86/cl.exe
The following packages will be built and …
```

Fix referring to registry ports as 'overlays'

---

cmake/CMakeRC_cmake_4.patch
cmake/FindCMakeRC.cmake

Because the version of CMakeRC that vcpkg depends on is so old, it has  a `cmake_minimum_required(VERSION 3.3)`; this is not valid now that CMake 4 has come out.
There are three options for fixing this:
- just add a maximum version in a patch
- start using a later version; unfortunately, this is not possible without changing how CMakeRC is downloaded, since the last tagged version of CMakeRC is from 2018
- Just pull CMakeRC into the tree. Given that the last tagged version is from _seven_ years ago, this seems entirely reasonable, but I didn't want to do that work without someone telling me that that was what they wanted.
I chose the first option since it's the simplest one.

[CMakeRC] support CMake 4.0

---

src/vcpkg/base/downloads.cpp

Curl writes progress information to stderr and write-out strings to stdout. Vcpkg uses single pipe for both stdout and stdin, so it's possible that the output will be garbled.
We don't really need progress information here, only error messages.

Don't track curl progress when performing bulk operations

---

azure-pipelines/end-to-end-tests-dir/asset-caching.ps1
azure-pipelines/end-to-end-tests-dir/clean-after-build.ps1
azure-pipelines/end-to-end-tests-prelude.ps1
src/test-script-asset-cache.c
src/vcpkg/base/downloads.cpp

Resolves a report that we broke Terrapin Retrieval Tool in https://github.com/microsoft/vcpkg-tool/pull/1618

Always pass an absolute path to x-script destinations.

---

azure-pipelines/end-to-end-tests-dir/artifacts.ps1
azure-pipelines/end-to-end-tests-prelude.ps1
azure-pipelines/end-to-end-tests.ps1

... rather than the ps1 wrapper, by default.
This seems appropriate given that vcpkg-artifacts doesn't seem to be going anywhere soon.

Speed up tests slightly by using the exe directly

---

src/vcpkg/base/downloads.cpp

Fixes https://github.com/microsoft/vcpkg/issues/44832

windows: Fix crash when curl is used to download assets

---

include/vcpkg/base/files.h
include/vcpkg/base/git.h
src/vcpkg/base/files.cpp
src/vcpkg/base/git.cpp
src/vcpkg/commands.test-features.cpp
src/vcpkg/vcpkgpaths.cpp

Fixes https://github.com/microsoft/vcpkg/issues/44803
Fixes https://github.com/microsoft/vcpkg/issues/44819

Fix recent git commands to work back on 2.7.4.

---

cmake/FindCMakeRC.cmake

Require Git only if the `VCPKG_DEPENDENCY_CMAKERC` option is disabled.
This will fix the build with the packaged version of CMakeRC after #1632:
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
Could NOT find Git (missing: GIT_EXECUTABLE)
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
/usr/share/cmake/Modules/FindGit.cmake:128 (find_package_handle_standard_args)
cmake/FindCMakeRC.cmake:14 (find_package)
CMakeLists.txt:197 (find_package)
-- Configuring incomplete, errors occurred!
```
With this fix it builds correctly:
```
Wrote: /builddir/build/RPMS/vcpkg-2025.04.07-2.fc43.x86_64.rpm
Wrote: /builddir/build/RPMS/vcpkg-debugsource-2025.04.07-2.fc43.x86_64.rpm
Wrote: …
```

Fixed packaged build with external CMakeRC

---

.github/workflows/build.yaml
azure-pipelines/end-to-end-tests-dir/asset-caching.ps1

Example, macOS failing due to 1 retry no longer being '1 retries' on newer macOS: https://github.com/microsoft/vcpkg-tool/actions/runs/14419755806/job/40440838600?pr=1646
Example, CI failing due to CodeQL apparently not running on arm64-linux: https://github.com/microsoft/vcpkg-tool/actions/runs/14369288728/job/40289110856

Fix macOS PR and CI build failure, and CodeQL arm64-linux failure.

---

.github/workflows/build.yaml
azure-pipelines/signing.yml

Notably, this switches us to Apple Silicon for both test and build labs, which should hopefully speed up test runs and/or reduce wait time for getting a machine to run the tests.

Adopt macOS 14 for PR and Release builds

---

src/vcpkg/binarycaching.cpp

Initial install:
￼
 After cache download:
￼
Permissions not preserved!
Changing to zip contents…
 Original Install: 
￼
**Observe the write permissions.**
 Installing from binary cache:
￼
Permissions preserved!

Preserve permissions using upkg

---

CMakeLists.txt

Fixes running `make test` in a linux system with curl localizations.

Force LC_ALL=C for test execution

---

include/vcpkg/base/files.h
include/vcpkg/commands.build.h
src/vcpkg/base/files.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/commands.ci.cpp
src/vcpkg/commands.test-features.cpp

Fixes https://github.com/microsoft/vcpkg/pull/45070#issuecomment-2809826609 where logs from a previous run were copied into the logs folder

BuildLogsRecorder: Only copy new log files

---

src/vcpkg/commands.build.cpp

This helps debugging build failures since the buildtrees folder is not removed in that case.

--clean-buildtrees-after-build: Only clean on success 

---

src/vcpkg/base/files.cpp
src/vcpkg/binarycaching.cpp

Fixes https://github.com/microsoft/vcpkg/issues/45130
Please note that there is already code in place to handle `std::errc::cross_device_link` for binary caching:
https://github.com/microsoft/vcpkg-tool/blob/d092b51ab6eb219e9af393d29214eeb4ad9f4750/src/vcpkg/binarycaching.cpp#L232-L249
However, copy-and-delete was only tried after calling `fs.rename_or_delete()` which tries to move the file after increasing timeouts. I decided to not move the copy-and-delete behavior to `fs.rename_or_delete()` because the file is first copied to a temproary location in `binarycaching.cpp`.
Files on different filesystems can't be renamed:
Linux: https://man7.org/linux/man-pages/man2/rename.2.html
Windows seems to support moving files but not folders across devices: …

Optimize rename_or_delete to stop retrying after EXDEV

---

azure-pipelines/e2e-ports/vcpkg-depends-on-fail/portfile.cmake
azure-pipelines/e2e-ports/vcpkg-depends-on-fail/vcpkg.json
azure-pipelines/e2e-ports/vcpkg-fail-if-depended-upon/vcpkg.json
azure-pipelines/end-to-end-tests-dir/build-test-ports.ps1
include/vcpkg/commands.build.h
src/vcpkg/commands.build.cpp

Before:
```
.\vcpkg.exe install vcpkg-depends-on-fail[x] --overlay-ports C:\Dev\vcpkg-tool\azure-pipelines\e2e-ports --keep-going --binarysource clear
[...]
error: building vcpkg-depends-on-fail:x64-windows failed with: CASCADED_DUE_TO_MISSING_DEPENDENCIES
due to the following missing dependencies:
vcpkg-fail-if-depended-upon[a]:x64-windows
vcpkg-fail-if-depended-upon[core]:x64-windows
vcpkg-fail-if-depended-upon[b]:x64-windows
vcpkg-fail-if-depended-upon[core]:x64-windows
```
After:
```
.\vcpkg.exe install vcpkg-depends-on-fail[x] --overlay-ports C:\Dev\vcpkg-tool\azure-pipelines\e2e-ports --keep-going --binarysource clear
[...]
error: building vcpkg-depends-on-fail:x64-windows failed with: CASCADED_DUE_TO_MISSING_DEPENDENCIES
due to the following missing dependencies: …
```

Merge cascaded failure feature dependencies together.

---

src/vcpkg/base/files.cpp

Fixes 10.1 seconds delay for each file write operation across devices, e.g. for `FilesWriteBinaryProvider`.
Fixes https://github.com/microsoft/vcpkg/issues/45130.

Fix cross-device rename_or_delete

---

azure-pipelines/e2e-assets/format-manifest-malformed/bad-feature-name.json
azure-pipelines/end-to-end-tests-dir/format-manifest.ps1
include/vcpkg/base/jsonreader.h
src/vcpkg/base/json.cpp
src/vcpkg/sourceparagraph.cpp

When a feature name is invalid, report the error as part of the feature name rather than as part of the overall features block.
Before and after demonstration:
```
PS C:\Dev\vcpkg-tool\out\build\Win-x64-Debug-WithArtifacts> type C:\Dev\vcpkg-tool\azure-pipelines\e2e-ports\vcpkg-requires-feature\vcpkg.json
{
"name": "vcpkg-requires-feature",
"version": "0",
"features": {
"a": {
"description": "Feature A"
},
"b": {
"description": "Feature B"
},
"b_required": {
"description": "This feature needs to be turned on for the port to build"
},
"c": {
"description": "Feature C"
}
}
}
PS C:\Dev\vcpkg-tool\out\build\Win-x64-Debug-WithArtifacts> C:\Dev\vcpkg\vcpkg.exe format-manifest C:\Dev\vcpkg-tool\azure-pipelines\e2e-ports\vcpkg-requires-feature\vcpkg.json …
```

Improve invalid feature name reporting

---

azure-pipelines/end-to-end-tests-dir/test-features.ps1
azure-pipelines/end-to-end-tests-prelude.ps1
include/vcpkg/ci-feature-baseline.h
src/vcpkg/ci-feature-baseline.cpp
src/vcpkg/commands.test-features.cpp

We don't want to enforce the cascade list for the curated registry.
See also:
* https://github.com/microsoft/vcpkg/pull/45176#issuecomment-2826401801
* https://github.com/microsoft/vcpkg/pull/45270

x-feature-test: Only enforce cascades in baseline when used with --all

---

src/vcpkg/base/downloads.cpp

fixes setting HTTTP<S>_PROXY environment variable with a trailing '/' results in no ability to download #45678

Remove trailing '/' from environment HTTP_PROXY variable fixes #45678

---

CMakeLists.txt
docs/vcpkg-tools.schema.json
include/vcpkg/tools.test.h
src/vcpkg-test/tools.cpp
src/vcpkg/base/files.cpp
src/vcpkg/base/system.cpp
src/vcpkg/base/system.mac.cpp
src/vcpkg/base/system.process.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/platform-expression.cpp
src/vcpkg/tools.cpp

This adds support for building and using vcpkg-tool on Solaris and illumos systems. The intent is to get the rest of vcpkg working. The majority of the work is in the `vcpkg::get_user_mac_hash` implementation using interfaces available in Solaris 8 and later. Tests pass with clang 18 on illumos/amd64.

Add platform support for Solaris and illumos

---

include/vcpkg/base/downloads.h
include/vcpkg/base/message-data.inc.h
include/vcpkg/binarycaching.h
locales/messages.json
src/vcpkg-test/configparser.cpp
src/vcpkg-test/downloads.cpp
src/vcpkg/base/downloads.cpp
src/vcpkg/binarycaching.cpp

Alternative to #1658.
Curl is still used for artifacts below the max single write limit (5 GB) and for all downloads. Fetching and uploading azcopy via vcpkg-tools.json (https://github.com/microsoft/vcpkg/pull/45461/commits/c178e5494f9c9a4beaf76f28b09a5ec1b0df1b5f) doesn't need azcopy.

Use azcopy for uploading large artifacts

---

src/vcpkg/commands.build.cpp
src/vcpkg/platform-expression.cpp

This commit adds support for visionOS as a platform.
There is a downstream set of changes in the vcpkg repo that adds a toolchain. I'm not entirely sure how to coordinate the changes but I'll open a PR in the base repo as well.

Add support for visionOS platform

---

locales/messages.cs.json
locales/messages.de.json
locales/messages.es.json
locales/messages.fr.json
locales/messages.it.json
locales/messages.ja.json
locales/messages.ko.json
locales/messages.pl.json
locales/messages.pt-BR.json
locales/messages.ru.json
locales/messages.tr.json
locales/messages.zh-Hans.json
locales/messages.zh-Hant.json

Localized file check-in by OneLocBuild Task: Build definition ID 15684: Build ID 11966727

---

src/vcpkg/commands.build.cpp

It is often helpful to know which cmake version was used (3.x vs 4.x)

include cmake version in autogenerated github issue

---

locales/messages.cs.json
locales/messages.de.json
locales/messages.es.json
locales/messages.fr.json
locales/messages.it.json
locales/messages.ja.json
locales/messages.ko.json
locales/messages.pl.json
locales/messages.pt-BR.json
locales/messages.ru.json
locales/messages.tr.json
locales/messages.zh-Hans.json
locales/messages.zh-Hant.json

Localized file check-in by OneLocBuild Task: Build definition ID 15684: Build ID 12078116

---

include/vcpkg/base/files.h
src/vcpkg/base/files.cpp
src/vcpkg/binarycaching.cpp

This fixes https://github.com/microsoft/vcpkg/issues/33714, but for windows. 7zip restores file times by default and there is no way to disable it.
This currently breaks our build at work. We use grpc and the generated headers has to match with the version of grpc that is currently in use. We use the following target but it is not triggered since the last modification date of the restored grpc tool (ProtocExe) is older than the headers:
```xml
<Target Name="GrpcGenerateCode" BeforeTargets="ClCompile"
Inputs="@(NormalizedProtoFile);$(ProtocExe)"
Outputs="@(_GrpcGeneratedHeaders);@(_GrpcGeneratedSources)">
...
</Target>
```
After this PR it worked as expected.

binarycaching: also don't restore file times on windows

---

include/vcpkg/base/contractual-constants.h
include/vcpkg/spdx.h
src/vcpkg-test/spdx.cpp
src/vcpkg/commands.build.cpp
src/vcpkg/spdx.cpp

Also remove repetition of relationships. These are no longer present in v3 of the SPDX spec. Keeping these relationships would also make the SBOM very noisy.

[spdx] Add installed package files to SPDX SBOM file

---

locales/messages.cs.json
locales/messages.de.json
locales/messages.es.json
locales/messages.fr.json
locales/messages.it.json
locales/messages.ja.json
locales/messages.pl.json
locales/messages.pt-BR.json
locales/messages.ru.json
locales/messages.tr.json
locales/messages.zh-Hans.json
locales/messages.zh-Hant.json

Localized file check-in by OneLocBuild Task: Build definition ID 15684: Build ID 12253873

---

src/vcpkg.cpp

Makes sure that we collect some data points before exiting when failing to parse a command name

Collect telemetry before exit

---

CMakeLists.txt

Hopefully resolves build failures like: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=12288570
```console
: && /usr/bin/g++ --sysroot=/crossrootfs/arm64 -isystem /crossrootfs/arm64/usr/include/aarch64-linux-gnu/c++/9 -isystem /crossrootfs/arm64/usr/include/c++/9 -B/crossrootfs/arm64/usr/lib/aarch64-linux-gnu/ -isystem /crossrootfs/arm64/usr/lib/gcc/aarch64-linux-gnu/9/include-fixed -isystem /crossrootfs/arm64/usr/lib/gcc/aarch64-linux-gnu/9/include -isystem /crossrootfs/arm64/usr/include/aarch64-linux-gnu -isystem /crossrootfs/arm64/usr/include -static-libgcc -nostdinc -static-libstdc++ -L/crossrootfs/arm64/usr/lib/gcc/aarch64-linux-gnu/9/ -Wall -Wextra -Wpedantic -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-redundant-move -Wmissing-declarations …
```

Add CMAKE_DL_LIBS for dlopen/dlsym.

---

.vscode/launch.json
CMakePresets.json
azure-pipelines/e2e-ports/broken-symlink/portfile.cmake
azure-pipelines/e2e-ports/broken-symlink/src/CMakeLists.txt
azure-pipelines/e2e-ports/broken-symlink/src/hello-broken-symlink.h
azure-pipelines/e2e-ports/broken-symlink/src/hello.cpp
azure-pipelines/e2e-ports/broken-symlink/src/hello.def
azure-pipelines/e2e-ports/broken-symlink/vcpkg.json
azure-pipelines/end-to-end-tests-dir/regression-ports.ps1
src/vcpkg/base/files.cpp
src/vcpkg/commands.build.cpp

#1744 introduced a lot of regressions into how vcpkg installs ports, particularly around handling symlinks and files we can't read.
Previously, all calls to the filesystem looking at the packages tree explicitly ignored errors. However, in #1744 recursive directory enumeration and opening the files to write hashes was added with the "crash on error" VCPKG_LINE_INFO forms.
This exposed some latent bugs in how we handle symlinks in recursive enumeration (which is good!).

2025-08-29 Regressions Fixes

---

locales/messages.cs.json
locales/messages.de.json
locales/messages.es.json
locales/messages.fr.json
locales/messages.it.json
locales/messages.ja.json
locales/messages.ko.json
locales/messages.pl.json
locales/messages.pt-BR.json
locales/messages.ru.json
locales/messages.tr.json
locales/messages.zh-Hans.json
locales/messages.zh-Hant.json

Localized file check-in by OneLocBuild Task: Build definition ID 15684: Build ID 12531007
