microsoft/vcpkg-tool

src/vcpkg-test/dependencies.cpp, src/vcpkg/dependencies.cpp
=> [vcpkg] Fix failure to install features for non-string, non-relaxed scheme dependencies

include/vcpkg/base/unicode.h, src/vcpkg/base/unicode.cpp
Fixes issue microsoft/vcpkg#16405
=> fix UB in make_error_code(utf8_errc)

azure-pipelines/Format-CxxCode.ps1
This is just a way to get slightly more information out of the script.
=> add clang-format version to format-cxxcode

src/vcpkg/dependencies.cpp
fixes microsoft/vcpkg#17269
cc @klalumiere
=> hopefully fix crash in constraints

src/vcpkg/commands.integrate.cpp
=> fixing vcpkg help from `vcpkg integrate fish` to `vcpkg integrate x-fish`.

include/vcpkg/base/downloads.h, include/vcpkg/binarycaching.h, src/vcpkg-test/configparser.cpp, src/vcpkg/base/downloads.cpp, src/vcpkg/binarycaching.cpp, src/vcpkg/help.cpp
=> Add x-block-origin for Asset Caching

src/vcpkg/install.cpp
Adds hashed version values to install plan metrics.
=> [metrics] Suffix ":version" to install plan metrics

src/vcpkg/commands.search.cpp
This PR adjusts the formatting of the `search` command to never trim package names+versions. While this can sometimes be uglier, this is needed because those pieces of information are critical to use the packages.
Fixes https://github.com/microsoft/vcpkg/issues/16286
Before:
```
$ vcpkg search azure
azure-c-shared-ut... 2020-12-09#1     Azure C SDKs common code
azure-c-shared-utility[public-prev... Azure C SDKs common code (public preview)
azure-core-cpp       1.0.0-beta.8#1   Microsoft Azure Core SDK for C++
azure-core-cpp[curl]                  LibCURL HTTP transport implementation
azure-core-cpp[http]                  All HTTP transport implementations available on the platform
azure-core-cpp[winhttp]               WinHTTP HTTP transport implementation
azure-identity-cpp …
```
=> [search] Do not trim package names nor versions from search output

include/vcpkg/base/files.h, src/vcpkg/base/files.cpp, src/vcpkg/vcpkgpaths.cpp
This is a fix for https://github.com/microsoft/vcpkg/issues/17475 .
=> Add retry mechanism

azure-pipelines/pipelines.yml, src/vcpkg/base/files.cpp
Fixes https://github.com/microsoft/vcpkg/issues/19022
=> Fix build failure on GCC 7.

src/vcpkg/vcpkgpaths.cpp
=> fix check for ignore_lock_failures

.clang-format, CMakeLists.txt, src/tls12-download.c
=> Add signature validation to tls12-download.exe.

include/vcpkg/base/jsonreader.h, src/vcpkg-test/registries.cpp
=> Change array_elements to return empty vector rather than nullopt.

src/vcpkg/base/downloads.cpp
Fixes https://discord.com/channels/400588936151433218/687365466422902841/877318874817785926
=> For asset cache put opertions to file:// the http status code is 0, but this is not an error

.clang-format, include/vcpkg/base/files.h, src/tls12-download.c, src/vcpkg-test/files.cpp, src/vcpkg/base/files.cpp, src/vcpkg/commands.integrate.cpp, src/vcpkg/metrics.cpp
According to the ci the code is currently wrongly formatted
=> Format code with clang-format 12

include/vcpkg/vcpkgcmdarguments.h, src/vcpkg-test/arguments.cpp, src/vcpkg-test/binarycaching.cpp, src/vcpkg/binarycaching.cpp, src/vcpkg/commands.xdownload.cpp, src/vcpkg/vcpkgcmdarguments.cpp, src/vcpkg/vcpkgpaths.cpp
Closing https://discord.com/channels/400588936151433218/687365466422902841/877303084940918814
=> [asset caching] Add cli parameter to pass asset sources

include/catch2/catch.hpp
Fixes https://github.com/microsoft/vcpkg/issues/18799
=> Update catch2 to v2.13.7 (fixes arm64 mac builds)

src/vcpkg.cpp
Especially useful when you have long running commands and fixes https://github.com/microsoft/vcpkg/issues/18217
=> Use user friendly time format for total elapsed time

azure-pipelines/end-to-end-tests-dir/ci.ps1, src/vcpkg/commands.ci.cpp
... in support of asserting about cascade count requested in https://github.com/microsoft/vcpkg/pull/20074#issuecomment-916565430
=> [ci] Add --x-skipped-cascade-count 

include/pch.h, src/vcpkg.cpp
set LC_ALL to a utf-8 compatible locale if possible.
Fixes the same problem as microsoft/vcpkg#20060
=> Add locale setting

azure-pipelines/end-to-end-tests-dir/env-tools.ps1, src/vcpkg/base/files.cpp
Resolves https://github.com/microsoft/vcpkg/issues/19552 and adds a test.
=> Treat nonexistent directories as if they are empty.

src/vcpkg/commands.civerifyversions.cpp
This removes the check for "the version in the thing is the latest".
=> [vcpkg] rolling back versions should be allowed

src/vcpkg/base/files.cpp
This PR is part of the std::filesystem removal-on-POSIX project.
=> Add posix-native current_path().

include/vcpkg/base/files.h, src/vcpkg-test/files.cpp, src/vcpkg/base/files.cpp
This PR is part of the std::filesystem removal-on-POSIX project.
=> Add posix native remove, remove_all, and remove_all_inside.

src/vcpkg-test/files.cpp, src/vcpkg/base/files.cpp
This PR is part of the std::filesystem removal-on-POSIX project.
* rename
* is_directory
* is_regular_file
* is_empty
* create_directory
* create_directories
* create_symlink
* create_directory_symlink
* status
* symlink_status
=> Add more posix-native misc things.

src/vcpkg-test/files.cpp, src/vcpkg/base/files.cpp
This is the root cause of https://github.com/microsoft/vcpkg/issues/21107
=> Fix find_file_recursively_up when starting from a file.

src/vcpkg/sourceparagraph.cpp
Fixes https://github.com/microsoft/vcpkg-tool/pull/184#issuecomment-955008436
=> Add serialization of supports expressions in features

src/vcpkg/build.cpp
Fixed swapped output of repo and tool revision on build errors.
E.g.: here https://github.com/microsoft/vcpkg/issues/21146
CC @autoantwort
=> Fix reported repo and tool version

azure-pipelines/pipelines.yml
This is adopted from the my open source AZP CI for another project. Hope it works with vcpkg-tool CI.
=> [ci] Analyze test coverage for gcc/linux

src/vcpkg/base/files.cpp
=> Fix build on FreeBSD

src/vcpkg/base/downloads.cpp, src/vcpkg/commands.xdownload.cpp
Fixes: https://github.com/microsoft/vcpkg/issues/17756
=> Hash: Make verification case-insensitive

src/vcpkg/commands.hash.cpp
Fixes: https://github.com/microsoft/vcpkg/issues/4791
=> [vcpkg-hash] use current working directory to get a file

src/vcpkg/configure-environment.cpp
(or something else would be ok -- just add a double-dash style switch at the end of the whole command `--whatever`)
(I'm assuming that this one-line is how you'd do it )
=> Add a  parameter to tell CE that it's being called from VCPKG.EXE

include/vcpkg/sourceparagraph.h, src/vcpkg-test/manifests.cpp, src/vcpkg/sourceparagraph.cpp
=> [manifests] add $comments to features object

src/vcpkg/platform-expression.cpp
Closes https://github.com/microsoft/vcpkg/issues/22080
=> Improve format of platform expressions

src/vcpkg/build.cpp
Currently only usages of functions that were used in the portfile.cmake are found, extend this search to all cmake files in the port dir.
For example the old/new openssl `vcpkg_abi_info.txt` file:
https://www.diffchecker.com/Q24UBpJB
=> abi entries: Detect all used functions from scripts/cmake

CMakeLists.txt, azure-pipelines/signing.yml, cmake/Findfmt.cmake
Resolves https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1445633/
=> Enable /W3 in fmt to pass SDL checks.

src/vcpkg/platform-expression.cpp
"Close"/Implements https://github.com/microsoft/vcpkg/discussions/21964
=> platform expressions: add freebsd and openbsd

src/vcpkg/base/system.process.cpp
According to https://linux.die.net/man/3/pclose:
> The pclose() function waits for the associated process to terminate and returns the exit status of the command as returned by wait4(2). 
And from https://linux.die.net/man/2/wait4:
> Return Value
As for waitpid(2).  
And from https://linux.die.net/man/2/waitpid:
> WIFEXITED(status)  
> ____ returns true if the child terminated normally, that is, by calling exit(3) or _exit(2), or by returning from main(). 
WEXITSTATUS(status)  
____ returns the exit status of the child. This consists of the least significant 8 bits of the status argument that the child specified in a call to exit(3) or _exit(2) or as the argument for a return statement in main(). This macro should only be employed if WIFEXITED returned true. 
WIFSIGNALED(status)  
____ …
=> cmd_execute_and_stream_data: Determine right exit codes

src/vcpkg/base/files.cpp
Should address https://github.com/microsoft/vcpkg/issues/21557 after a tool update.
=> Support files greater than 2GiB in size in copy_file on Linux.

cmake/Findfmt.cmake, src/vcpkg/sourceparagraph.cpp
Fixes https://github.com/microsoft/vcpkg/issues/23110
=> update fmt to 8.1.1 and fix build

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220224183434953 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220224183434953 to main

src/vcpkg/build.cpp
to workaround the regression caused by #350
=> Add Z_ to VCPKG_CHAINLOAD_TOOLCHAIN_FILE

src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225135211178 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225135211178 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226134835648 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226134835648 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226135250745 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226135250745 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226135101244 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226135101244 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226134959915 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226134959915 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226134921211 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226134921211 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226134856070 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220226134856070 to main

src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225134925398 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225134925398 to main

src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225134850514 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225134850514 to main

src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225134827740 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225134827740 to main

src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225134809729 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225134809729 to main

src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225135024340 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220225135024340 to main

src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220228134842342 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220228134842342 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220303134756207 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220303134756207 to main

src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/ru/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220304134831856 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220304134831856 to main

src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220306134843422 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220306134843422 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220308134737900 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220308134737900 to main

src/vcpkg/vcpkgpaths.cpp
Extracted from https://github.com/microsoft/vcpkg-tool/pull/404
=> Deduplicate extract_tar_cmake in vcpkgpaths.cpp.

src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220313124814379 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220313124814379 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220314124737594 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220314124737594 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220323124817777 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220323124817777 to main

src/localization/de/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220324124824174 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220324124824174 to main

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220326124809302 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220326124809302 to main

src/localization/es/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220327124842450 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220327124842450 to main

src/localization/ru/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220328124721733 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220328124721733 to main

include/vcpkg/base/sortedvector.h, include/vcpkg/base/stringview.h, include/vcpkg/ci-baseline.h, include/vcpkg/fwd/ci-baseline.h, src/vcpkg-test/ci-baseline.cpp, src/vcpkg/ci-baseline.cpp, src/vcpkg/commands.ci.cpp
=> [ci] allow skipping `=fail`

src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220401124901273 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220401124901273 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220402125036597 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220402125036597 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220403125429675 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220403125429675 to main

src/localization/ja/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220405124753775 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220405124753775 to main

src/vcpkg/install.cpp
=> [telemetry] add install_manifest_mode

src/localization/de/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220407124831819 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220407124831819 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220408124908893 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220408124908893 to main

src/localization/ja/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220409124843916 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220409124843916 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/ko/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220410124823276 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220410124823276 to main

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220411124837102 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220411124837102 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220413172922698 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220413172922698 to main

src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220414125206022 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220414125206022 to main

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220415125015538 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220415125015538 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220416124851554 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220416124851554 to main

src/localization/cs/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220417124800038 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220417124800038 to main

src/localization/ja/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220418172155876 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220418172155876 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220422124925317 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220422124925317 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220423173053817 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220423173053817 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220428124759469 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220428124759469 to main

src/localization/ja/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220430124805938 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220430124805938 to main

src/vcpkg/postbuildlint.cpp
Fixes https://github.com/microsoft/vcpkg/issues/24124
=> postbuildcheck: do not suggest invalid cmake

src/vcpkg/base/files.cpp
=> Fall back to read/write if sendfile fails with EINVAL or ENOSYS

src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220521141327349 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220521141327349 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220522133845503 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220522133845503 to main

src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220523133559495 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220523133559495 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220525134303090 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220525134303090 to main

src/localization/cs/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220526184516604 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220526184516604 to main

src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220528131550175 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220528131550175 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220529132321731 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220529132321731 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220609130250106 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220609130250106 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220610124855125 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220610124855125 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220616124939543 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220616124939543 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220706124937103 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220706124937103 to main

src/localization/de/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/ru/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220709125107477 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220709125107477 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220710124917550 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220710124917550 to main

src/vcpkg-in-development.ps1
This problem was discovered by @qarni ; many thanks to her in helping to run it down.
=> Add the $IsWindows workaround from the normal vcpkg scripts to the in-development script.

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220715125008511 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220715125008511 to main

src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220717124937166 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220717124937166 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220721130236326 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220721130236326 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220723125252462 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220723125252462 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220724124902761 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220724124902761 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220727124946594 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220727124946594 to main

src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220728124938235 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220728124938235 to main

CMakeLists.txt
Fixes https://dev.azure.com/vcpkg/public/_build/results?buildId=76301&view=logs&j=0bfd6f0f-4614-56f6-965c-10b2fc29bf11&t=f39e0752-0c2f-50e1-c3c7-7cb37bd6c2d9
=> Fix Build Break

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220810124919097 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220810124919097 to main

src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220811124858274 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220811124858274 to main

src/localization/ja/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220812125024152 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220812125024152 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220819125033927 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220819125033927 to main

src/vcpkg/base/messages.cpp, src/vcpkg/commands.civerifyversions.cpp, src/vcpkg/commands.find.cpp
Resolves  https://github.com/microsoft/vcpkg/issues/26415
This regressed in https://github.com/microsoft/vcpkg-tool/commit/107754ff90120f28417a30e86e56048e4884fd44
=> Fix fmt format strings.

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220820125613651 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220820125613651 to main

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220821124835809 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220821124835809 to main

src/localization/pt-BR/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220822133741794 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220822133741794 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220823125127437 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220823125127437 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220824125004601 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220824125004601 to main

ce/ce/yaml/Options.ts
Cherry picked from https://github.com/microsoft/vcpkg-tool/pull/672/
=> Fix recent-ish regression that broke reading files without options blocks.

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220825132801715 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220825132801715 to main

include/vcpkg/base/graphs.h, src/vcpkg/base/cofffilereader.cpp, src/vcpkg/dependencies.cpp, src/vcpkg/xunitwriter.cpp
- Add default destructors where possible
- Remove `using namespace std;`
=> Add default destructors

ce/ce/registries/artifact-index.ts, ce/ce/registries/indexer.ts, ce/test/core/index-tests.ts, ce/test/core/regression-tests.ts
reported as https://github.com/microsoft/vcpkg-ce-catalog/pull/33
=> Fix regression in loading old index.yaml

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220911125225460 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20220911125225460 to main

ce/ce/amf/demands.ts, ce/ce/amf/metadata-file.ts, ce/ce/artifacts/SetOfDemands.ts, ce/ce/interfaces/metadata/demands.ts, ce/ce/interfaces/metadata/metadata-format.ts, docs/artifact.schema.json, docs/vcpkg-configuration.schema.json, docs/vcpkg-schema-definitions.schema.json, src/vcpkg-test/configmetadata.cpp, src/vcpkg/configuration.cpp
This field was never connected to anything.
=> Delete the 'see-also' element from artifacts.

include/vcpkg/commands.zpreregistertelemetry.h, include/vcpkg/metrics.h, src/vcpkg-test/metrics.cpp, src/vcpkg/commands.cpp, src/vcpkg/commands.zpreregistertelemetry.cpp, src/vcpkg/metrics.cpp
=> [telemetry] Add internal command to pre-register metrics

azure-pipelines/end-to-end-tests-dir/binarycaching.ps1, azure-pipelines/end-to-end-tests-dir/bundles.ps1
Because mono is not available on arm64 macs
=> Fix e2e tests on arm64 macs

cmake/Findfmt.cmake
from https://github.com/microsoft/vcpkg-tool/pull/679/
Competing resolution of https://github.com/microsoft/vcpkg-tool/pull/686/
=> Revert the addition of extra FMT variables

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221006132736682 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221006132736682 to main

src/localization/de/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221007125328832 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221007125328832 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221008132126773 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221008132126773 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221009132252902 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221009132252902 to main

src/vcpkg/archives.cpp, src/vcpkg/base/json.cpp, src/vcpkg/base/strings.cpp, src/vcpkg/binaryparagraph.cpp, src/vcpkg/build.cpp, src/vcpkg/commands.check-support.cpp, src/vcpkg/commands.ci.cpp, src/vcpkg/commands.civerifyversions.cpp, src/vcpkg/commands.find.cpp, src/vcpkg/commands.format-manifest.cpp, src/vcpkg/commands.integrate.cpp, src/vcpkg/dependencies.cpp, src/vcpkg/portfileprovider.cpp, src/vcpkg/remove.cpp, src/vcpkg/tools.cpp, src/vcpkg/vcpkgcmdarguments.cpp
`"\n"` makes an extra call to `strlen`.
I either put it in single quotes or used `Debug::println`.
=> Put single chars in single quotes

CMakeLists.txt
=> cmake_minimum_required needs ... not ..

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221013124952717 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221013124952717 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221014132849090 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221014132849090 to main

ce/ce/cli/command-line.ts, ce/ce/cli/commands/acquire-project.ts, ce/ce/cli/commands/acquire.ts, ce/ce/cli/commands/activate.ts, ce/ce/cli/commands/add.ts, ce/ce/cli/commands/deactivate.ts, ce/ce/cli/commands/find.ts, ce/ce/cli/commands/generate-msbuild-props.ts, ce/ce/cli/commands/remove.ts, ce/ce/cli/commands/update.ts, ce/ce/cli/commands/use.ts, ce/ce/cli/switches/project.ts, ce/ce/session.ts, include/vcpkg/vcpkgpaths.h, src/vcpkg/configure-environment.cpp, src/vcpkg/vcpkgpaths.cpp
Reverts microsoft/vcpkg-tool#731
=> Revert "Delete --project from all vcpkg-artifacts commands"

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221021125035653 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221021125035653 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221022130506840 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221022130506840 to main

src/localization/cs/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221023124952249 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221023124952249 to main

src/vcpkg/vcpkgcmdarguments.cpp
Adds a new CI vendor to our detection
=> [telemetry] Detect TeamCity CI

src/vcpkg/commands.civerifyversions.cpp, src/vcpkg/dependencies.cpp, src/vcpkg/vcpkgpaths.cpp
You can dereference the smart pointer directly.
=> Remove unneeded get()

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221028125009567 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221028125009567 to main

src/vcpkg/archives.cpp, src/vcpkg/base/files.cpp, src/vcpkg/base/json.cpp, src/vcpkg/base/parse.cpp, src/vcpkg/binarycaching.cpp, src/vcpkg/dependencies.cpp, src/vcpkg/portfileprovider.cpp, src/vcpkg/registries.cpp, src/vcpkg/tools.cpp
So let's remove them where they are not needed
=> std::move has no effect on const variables

src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221029125604311 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221029125604311 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221031125000983 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221031125000983 to main

src/localization/es/messages.json.lcl, src/localization/ja/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221101125052818 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221101125052818 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221102125011858 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221102125011858 to main

src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221103125047845 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221103125047845 to main

src/vcpkg/binarycaching.cpp
Fixes https://github.com/microsoft/vcpkg/issues/26651
See #795
=> Fix segfault

src/vcpkg/install.cpp
Removal is not an error! (+ a few additional ones)
closes https://github.com/microsoft/vcpkg/issues/27588
=> Fix --keep-going in manifest mode.

azure-pipelines/end-to-end-tests-dir/format-manifest.ps1
It now needs 7.5 instead of 187 seconds on my pc
=> e2e tests: Massively speed up format check

src/localization/cs/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221201135054540 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221201135054540 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221202134949346 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221202134949346 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221207135144968 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221207135144968 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221209135302882 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221209135302882 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221211135108714 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221211135108714 to main

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221212140708331 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221212140708331 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221214135127526 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221214135127526 to main

docs/vcpkg-configuration.schema.json
See https://github.com/microsoft/vcpkg/blob/master/docs/users/registries.md#configuration-overlay-ports
=> Add overlays to configuration schema

src/localization/de/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221215143831212 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221215143831212 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221218135301789 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221218135301789 to main

src/localization/ru/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221220142524327 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20221220142524327 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230104135737886 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230104135737886 to main

azure-pipelines/end-to-end-tests-dir/build-test-ports.ps1
Noticed while trying to implement a new test.
=> Fix broken e2e test

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230112141535264 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230112141535264 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230113135538513 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230113135538513 to main

src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230115135202673 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230115135202673 to main

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230122135132412 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230122135132412 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230123135302443 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230123135302443 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230202135120982 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230202135120982 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230210135352181 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230210135352181 to main

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230212140914254 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230212140914254 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230213135423957 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230213135423957 to main

azure-pipelines/Create-PRDiff.ps1, azure-pipelines/pipelines.yml, locales/messages.json
See https://github.com/microsoft/vcpkg-tool/pull/853#issuecomment-1428055077
=> Fix ci format check 

src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230214135721104 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230214135721104 to main

src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230215135122475 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230215135122475 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230216135406480 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230216135406480 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/ru/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230218135312661 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230218135312661 to main

src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230219135252250 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230219135252250 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230220135347244 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230220135347244 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230224141001408 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230224141001408 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230226135655861 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230226135655861 to main

ce/ce/cli/command-line.ts, ce/ce/cli/commands/activate.ts, ce/ce/cli/commands/deactivate.ts, ce/ce/cli/commands/use.ts, ce/ce/cli/project.ts, ce/ce/session.ts, src/vcpkg/configure-environment.cpp
* Move determining where previous environment json should go into the exe.
* (Drive by) fix vcpkg deactivate not working with use.
=> Artifacts: Don't create previous environment JSONs in VCPKG_ROOT.

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230301135243806 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230301135243806 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230302135409530 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230302135409530 to main

src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230309135243720 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230309135243720 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230310135240747 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230310135240747 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230311140327136 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230311140327136 to main

src/localization/cs/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230312125721257 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230312125721257 to main

src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230317125209922 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230317125209922 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230318125606781 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230318125606781 to main

src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230319125216495 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230319125216495 to main

src/vcpkg/commands.dependinfo.cpp
Fixes https://github.com/microsoft/vcpkg-tool/pull/909#issuecomment-1475058792
=> fix crash in depend-info --dot

src/vcpkg/commands.integrate.cpp
Fixes https://github.com/microsoft/vcpkg/issues/30283
=> Fix crash in integrate-install powershell

CMakeLists.txt
The file pch.cpp was removed in https://github.com/microsoft/vcpkg-tool/pull/961
=> Fix target format

src/localization/de/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230321125211688 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230321125211688 to main

vcpkg-init/mint-standalone-bundle.ps1, vcpkg-init/vcpkg.props, vcpkg-init/vcpkg.targets
The difference between current vcpkg master and here is recorded as https://github.com/microsoft/vcpkg/pull/30373
=> Disable classic mode integration in standalone bundles.

src/localization/cs/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230324130222206 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230324130222206 to main

src/vcpkg/base/downloads.cpp
Resolves https://github.com/microsoft/vcpkg-tool/pull/947#issuecomment-1488679052
=> Curl: Don't print a newline after every character.

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230402125203783 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230402125203783 to main

src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230403125138759 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230403125138759 to main

src/localization/de/messages.json.lcl, src/localization/pl/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230404125317673 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230404125317673 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230406130624544 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230406130624544 to main

azure-pipelines/signing.yml
This resulted in sign check failures trying to insert into VS: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=7595943&view=results
=> Don't deploy .ps1 files from 'semver'.

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230408125759903 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230408125759903 to main

src/vcpkg/postbuildlint.cpp
As requested by @Neumann-A in https://discord.com/channels/400588936151433218/687365466422902841/1095253298770104390
=> Also check for absolute paths to download dir

src/vcpkg/commands.setinstalled.cpp
Same as #1013 but without controversial options
=> #1013 \ {controversial options}

src/vcpkg-test/cmd-parser.cpp, src/vcpkg/base/cmd-parser.cpp
=> Fix response files with blank lines.

include/vcpkg/base/files.h, src/vcpkg/base/files.cpp, src/vcpkg/commands.edit.cpp, src/vcpkg/postbuildlint.cpp
Fixes https://github.com/microsoft/vcpkg/issues/31198
=> Add missing output to stdout log

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230503125219432 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230503125219432 to main

src/localization/de/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230504125252791 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230504125252791 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230505125236407 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230505125236407 to main

include/vcpkg/metrics.h, include/vcpkg/vcpkgcmdarguments.h, src/vcpkg/metrics.cpp, src/vcpkg/vcpkgcmdarguments.cpp
This will help us differentiate between different Action pipeline runs
=> telemetry: track actions environmental variable

include/vcpkg/base/system.process.h, include/vcpkg/metrics.h, src/vcpkg-test/cgroup-parser.cpp, src/vcpkg-test/metrics.cpp, src/vcpkg/base/system.process.cpp, src/vcpkg/metrics.cpp
Tracks calling process hierarchy, useful to determine usage in different IDEs and environments.
=> [telemetry] Track process tree

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230516125502267 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230516125502267 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230515125934568 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230515125934568 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230512125451372 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230512125451372 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230511125352986 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230511125352986 to main

azure-pipelines/signing.yml, docs/vcpkg_tool_release_process.md
Resolves https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1757074 "vcpkg symbols aren't automatically published"
=> Publish symbols automatically.

include/vcpkg/base/util.h, include/vcpkg/commands.build.h, src/vcpkg-test/dependencies.cpp, src/vcpkg-test/mockcmakevarsprovider.cpp, src/vcpkg-test/util.cpp, src/vcpkg/cmakevars.cpp, src/vcpkg/commands.build.cpp, src/vcpkg/commands.export.cpp, src/vcpkg/commands.install.cpp, src/vcpkg/configuration.cpp, src/vcpkg/dependencies.cpp
While reviewing https://github.com/microsoft/vcpkg-tool/pull/989/ I nerd sniped myself into looking for other instances of this pattern. Ultimately I proved to myself that I should *not* make a comment, but proving that required doing this work anyway...
=> Add / use map utilities.

azure-pipelines/signing.yml
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7806757
Just let build failures record the thing rather than trying to do specific bug filing.
=> Delete TSA uploads.

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230525125247817 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230525125247817 to main

src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230601125706756 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230601125706756 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230602125345761 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230602125345761 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230604125813629 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230604125813629 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230605125354757 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230605125354757 to main

src/localization/de/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230615125055747 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230615125055747 to main

src/vcpkg/commands.install.cpp
Fixes https://github.com/microsoft/vcpkg/issues/30443
=> Show elapsed time even in the case of a build failure

docs/vcpkg-schema-definitions.schema.json, docs/vcpkg.schema.json
Was missing in https://github.com/microsoft/vcpkg-tool/pull/1096
=> Update schema definition

src/vcpkg/commands.format-manifest.cpp
Fixes https://github.com/microsoft/vcpkg/issues/31537
=> format-manifest: Add missing new line

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230707125226857 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230707125226857 to main

include/vcpkg/base/message-data.inc.h, locales/messages.json
I missed CR comments in https://github.com/microsoft/vcpkg-tool/pull/1104
=> Cleanup HashPortManyFiles warning.

src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230709125043185 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230709125043185 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230710125207435 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230710125207435 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230712125158326 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230712125158326 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230711125355710 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230711125355710 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230731125208815 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230731125208815 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230802125135959 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230802125135959 to main

src/localization/cs/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230803125344474 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230803125344474 to main

vcpkg-artifacts/installers/nuget.ts, vcpkg-artifacts/installers/untar.ts, vcpkg-artifacts/installers/unzip.ts, vcpkg-artifacts/registries/RemoteRegistry.ts, vcpkg-artifacts/vcpkg.ts
fixes https://github.com/microsoft/vcpkg/issues/32962
=> "strip" should not be required

docs/vcpkg_tool_release_process.md
Documents the release process change as of https://github.com/microsoft/vcpkg/pull/32885
=> Update tool release process for script

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230814125102093 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230814125102093 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230824125225310 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230824125225310 to main

src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230825125109814 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230825125109814 to main

src/localization/cs/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230828125146047 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230828125146047 to main

src/localization/cs/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230827125133606 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230827125133606 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230901125430094 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230901125430094 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230904125211384 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230904125211384 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230903125209807 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230903125209807 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230902125110337 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230902125110337 to main

src/vcpkg/base/files.cpp
=> Bug fix: Read/WriteFilePointer add missing copy of path

src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230908125042732 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230908125042732 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230911125158165 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230911125158165 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230910125125049 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230910125125049 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230913125807728 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230913125807728 to main

src/localization/cs/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230914125106022 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230914125106022 to main

src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230920125032192 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230920125032192 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230922125000926 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20230922125000926 to main

include/vcpkg/base/stringview.h, src/vcpkg/base/stringview.cpp, src/vcpkg/binarycaching.cpp, src/vcpkg/commands.bootstrap-standalone.cpp, src/vcpkg/commands.build.cpp, src/vcpkg/commands.ci.cpp, src/vcpkg/commands.integrate.cpp, src/vcpkg/export.chocolatey.cpp, src/vcpkg/export.prefab.cpp, src/vcpkg/postbuildlint.cpp, src/vcpkg/tools.cpp, src/vcpkg/triplet.cpp
- More constexpr for StringView
- Add missing override
- std::move(Path)
See commits for more details.
=> Various small fixes

src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231003125130554 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231003125130554 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231004125142345 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231004125142345 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231005125026057 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231005125026057 to main

src/localization/de/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231006125227646 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231006125227646 to main

include/vcpkg/base/files.h, src/vcpkg/base/files.cpp
Extracted from https://github.com/microsoft/vcpkg-tool/pull/1210
=> Add try_find_file_recursively_up

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231019125108551 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231019125108551 to main

docs/vcpkg_tool_release_process.md
Regression test for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1906521
=> Add test for artifacts activation in Visual Studio

src/localization/de/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231025125122916 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231025125122916 to main

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231103125335776 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231103125335776 to main

src/vcpkg/base/json.cpp
Fixes https://github.com/microsoft/vcpkg/issues/34877
=> Fix Comparison of Json::Value

include/vcpkg/base/strings.h
Fixes https://github.com/microsoft/vcpkg-tool/pull/1255#issuecomment-1793280296
=> std::experimental::boyer_moore_horspool_searcher is deprecated

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231107135241697 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231107135241697 to main

azure-pipelines/signing.yml
As requested by MicroBuild folks.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8628004&view=results demonstration working build
=> Update Signing Tasks for Azure Pipelines

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231122135439425 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231122135439425 to main

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ru/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231129135316331 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231129135316331 to main

src/localization/de/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231130135709153 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231130135709153 to main

src/vcpkg/commands.install.cpp
between https://github.com/microsoft/vcpkg-tool/pull/1293 and https://github.com/microsoft/vcpkg-tool/pull/1292
=> Fix stealth merge conflict 

src/localization/cs/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231206135211644 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231206135211644 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231219135112047 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20231219135112047 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240129183714094 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240129183714094 to main

src/localization/ja/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240130164716932 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240130164716932 to main

azure-pipelines/localization.yml
This change was requested by MS internal policy folks.
=> Convert localization.yml to 1ES Templates

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ko/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240131165816446 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240131165816446 to main

azure-pipelines/signing.yml, vcpkg-init/mint-standalone-bundle.ps1
This is an internal compliance ask of the vcpkg team.
Example build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9311251&view=logs&j=4cdc4065-f43d-507c-ee4e-5b139a5033dc&t=07e7a3b8-7638-5eac-04cb-963fb3791397
=> Adopt 1ES Pipeline Templates

.github/workflows/build.yaml
until https://dev.azure.com/twcdot/Data/_workitems/edit/128379 is fixed
=> Temporarily disable CodeQL for C++

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240427125508870 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240427125508870 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240428125750868 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240428125750868 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240429125329245 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240429125329245 to main

src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240501130704803 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240501130704803 to main

src/vcpkg/visualstudio.cpp
https://devdiv.visualstudio.com/DevDiv/_backlogs/backlog/Vcpkg%20Package%20Manager/Stories?workitem=2049383&System.AssignedTo=javiermat%40microsoft.com
=> Add support for VS 2022 using VS170COMNTOOLS environment variable

src/vcpkg/commands.set-installed.cpp
According to https://discord.com/channels/400588936151433218/687365466422902841/1240006232463642714 the rest of the logic should be setup up.
=> Add missing switch --keep-going to x-set-installed

src/localization/ru/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240609130727339 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240609130727339 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240612125315598 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240612125315598 to main

azure-pipelines/end-to-end-tests.ps1
=> end-to-end-tests: Backup/restore GITHUB_ACTIONS

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240626130446321 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240626130446321 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240625140548507 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240625140548507 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240702125338139 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240702125338139 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240717171712082 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240717171712082 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240730010624147 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240730010624147 to main

azure-pipelines/end-to-end-tests-dir/ci.ps1, src/vcpkg/commands.ci.cpp
https://github.com/microsoft/vcpkg-tool/pull/1468 didn't work in testing: https://dev.azure.com/vcpkg/public/_build/results?buildId=105566&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=7922e5c4-0103-5f8f-ad17-45ce9bb98e80
=> Actually make the exit code nonzero for regressions.

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240801131211674 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240801131211674 to main

src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240802131143615 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240802131143615 to main

.github/workflows/build.yaml, azure-pipelines/signing.yml
now that https://dev.azure.com/twcdot/Data/_workitems/edit/128379 is fixed.
GitHub Actions run: https://github.com/microsoft/vcpkg-tool/actions/runs/10117628787
Signed run (in progress as of this writing): https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9949877&view=results
=> Re-enable CodeQL 

src/vcpkg/postbuildlint.cpp
Related https://github.com/microsoft/vcpkg/pull/41062
=> Ban $/include/module.modulemap

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240925125314152 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240925125314152 to main

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240926125225148 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240926125225148 to main

src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240927125218337 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20240927125218337 to main

vcpkg-artifacts/artifacts/activation.ts
Should fix https://github.com/microsoft/vcpkg/issues/36025
=> Fix unset on POSIX.

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241002125125959 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241002125125959 to main

src/localization/cs/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241003125335816 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241003125335816 to main

src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241008234846681 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241008234846681 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241022125345221 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241022125345221 to main

include/vcpkg/base/optional.h, src/vcpkg-test/optional.cpp
Extracted from https://github.com/microsoft/vcpkg-tool/pull/1490/ as it's unclear when that change will land.
=> Allow constexpr optionals.

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241108135410664 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241108135410664 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241112135237686 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241112135237686 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241113135200936 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241113135200936 to main

src/localization/cs/messages.json.lcl, src/localization/it/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241114135149746 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241114135149746 to main

docs/vcpkg_registry_release_process.md, docs/vcpkg_tool_release_process.md
Update the tool and registry release docs to the status quo.
=> Update release processes.

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241231184111610 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20241231184111610 to main

include/vcpkg/vcpkgpaths.h
=> fix includes

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250107135312324 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250107135312324 to main

azure-pipelines/end-to-end-tests-dir/asset-caching.ps1, include/vcpkg/base/strings.h, src/vcpkg/base/downloads.cpp, src/vcpkg/base/strings.cpp
Same as https://github.com/microsoft/vcpkg-tool/pull/1564 but for azurl as well.
=> Transform SHA512s to lowercase for azurl.

src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250120135914465 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250120135914465 to main

src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250130135427445 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250130135427445 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250207135318189 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250207135318189 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250307135109381 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250307135109381 to main

azure-pipelines/signing.yml
The apiscan team said they would break this soon; this should fix it.
=> Set the version field differently for apiscan

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250314125047829 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250314125047829 to main

src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250322125119488 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250322125119488 to main

src/localization/cs/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/tr/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250323125053693 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250323125053693 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250329125026019 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250329125026019 to main

src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250330125046061 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250330125046061 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250412124858344 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250412124858344 to main

src/localization/pl/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250413124954532 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250413124954532 to main

src/vcpkg/commands.test-features.cpp
2 in https://github.com/microsoft/vcpkg/pull/44788#issuecomment-2794670136
=> test-features: failure exit code if tests fail

src/vcpkg/commands.build.cpp, src/vcpkg/commands.test-features.cpp
Point 1 in https://github.com/microsoft/vcpkg/pull/44788#issuecomment-2794670136
=> test-features: Only create the tested-spec.txt file if a feature test fails

.github/workflows/build.yaml
Hopefully resolves build failure like https://github.com/microsoft/vcpkg-tool/actions/runs/14739614463/job/41374129708?pr=1661
=> Remove lukka/get-cmake and use the one in the Actions image instead

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250505124802403 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250505124802403 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250606125944797 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250606125944797 to main

locales/messages.cs.json, locales/messages.de.json, locales/messages.es.json, locales/messages.fr.json, locales/messages.it.json, locales/messages.ja.json, locales/messages.ko.json, locales/messages.pl.json, locales/messages.pt-BR.json, locales/messages.ru.json, locales/messages.tr.json, locales/messages.zh-Hans.json, locales/messages.zh-Hant.json
=> Localized file check-in by OneLocBuild Task: Build definition ID 15684: Build ID 11775386

locales/messages.it.json, locales/messages.pl.json, locales/messages.zh-Hans.json
=> Localized file check-in by OneLocBuild Task: Build definition ID 15684: Build ID 12094509

locales/messages.cs.json, locales/messages.de.json, locales/messages.es.json, locales/messages.fr.json, locales/messages.it.json, locales/messages.ja.json, locales/messages.ko.json, locales/messages.pl.json, locales/messages.pt-BR.json, locales/messages.ru.json, locales/messages.tr.json, locales/messages.zh-Hans.json, locales/messages.zh-Hant.json
=> Localized file check-in by OneLocBuild Task: Build definition ID 15684: Build ID 12222854

src/vcpkg/commands.build.cpp, src/vcpkg/platform-expression.cpp
This is taking the same approach as here: https://github.com/microsoft/vcpkg-tool/pull/1681/files
=> Add support for tvOS and watchOS platforms

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/fr/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250823124922426 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250823124922426 to main

src/localization/ko/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250824124759069 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250824124759069 to main

src/localization/cs/messages.json.lcl, src/localization/de/messages.json.lcl, src/localization/es/messages.json.lcl, src/localization/it/messages.json.lcl, src/localization/ja/messages.json.lcl, src/localization/ko/messages.json.lcl, src/localization/pl/messages.json.lcl, src/localization/pt-BR/messages.json.lcl, src/localization/ru/messages.json.lcl, src/localization/tr/messages.json.lcl, src/localization/zh-Hans/messages.json.lcl, src/localization/zh-Hant/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250910124810695 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20250910124810695 to main

src/localization/it/messages.json.lcl
LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20251005151732348 to main with localized lcls
=> LEGO: Pull request from juno/hb_cb3056d7-d122-4ef4-8657-e36080a7f8c6_20251005151732348 to main
